/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.vanbanphapquy.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.vanbanphapquy.model.Capbanhanh;
import vn.dnict.vanbanphapquy.service.CapbanhanhService;
import vn.dnict.vanbanphapquy.service.CapbanhanhServiceUtil;
import vn.dnict.vanbanphapquy.service.persistence.CapbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.CoquanbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LinhvucvanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LoaivanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.VanbanphapquyPersistence;
import vn.dnict.vanbanphapquy.service.persistence.dinhkemfilePersistence;

/**
 * Provides the base implementation for the capbanhanh remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.vanbanphapquy.service.impl.CapbanhanhServiceImpl}.
 * </p>
 *
 * @author BinhNT
 * @see vn.dnict.vanbanphapquy.service.impl.CapbanhanhServiceImpl
 * @generated
 */
public abstract class CapbanhanhServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, CapbanhanhService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CapbanhanhService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CapbanhanhServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CapbanhanhService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		capbanhanhService = (CapbanhanhService)aopProxy;

		_setServiceUtilService(capbanhanhService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CapbanhanhService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Capbanhanh.class;
	}

	protected String getModelClassName() {
		return Capbanhanh.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = capbanhanhPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(CapbanhanhService capbanhanhService) {
		try {
			Field field = CapbanhanhServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, capbanhanhService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected vn.dnict.vanbanphapquy.service.CapbanhanhLocalService
		capbanhanhLocalService;

	protected CapbanhanhService capbanhanhService;

	@Reference
	protected CapbanhanhPersistence capbanhanhPersistence;

	@Reference
	protected CoquanbanhanhPersistence coquanbanhanhPersistence;

	@Reference
	protected dinhkemfilePersistence dinhkemfilePersistence;

	@Reference
	protected LinhvucvanbanPersistence linhvucvanbanPersistence;

	@Reference
	protected LoaivanbanPersistence loaivanbanPersistence;

	@Reference
	protected VanbanphapquyPersistence vanbanphapquyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}