/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.vanbanphapquy.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.vanbanphapquy.model.Coquanbanhanh;
import vn.dnict.vanbanphapquy.service.CoquanbanhanhLocalService;
import vn.dnict.vanbanphapquy.service.CoquanbanhanhLocalServiceUtil;
import vn.dnict.vanbanphapquy.service.persistence.CapbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.CoquanbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LinhvucvanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LoaivanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.VanbanphapquyPersistence;
import vn.dnict.vanbanphapquy.service.persistence.dinhkemfilePersistence;

/**
 * Provides the base implementation for the coquanbanhanh local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.vanbanphapquy.service.impl.CoquanbanhanhLocalServiceImpl}.
 * </p>
 *
 * @author BinhNT
 * @see vn.dnict.vanbanphapquy.service.impl.CoquanbanhanhLocalServiceImpl
 * @generated
 */
public abstract class CoquanbanhanhLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CoquanbanhanhLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CoquanbanhanhLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CoquanbanhanhLocalServiceUtil</code>.
	 */

	/**
	 * Adds the coquanbanhanh to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CoquanbanhanhLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param coquanbanhanh the coquanbanhanh
	 * @return the coquanbanhanh that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Coquanbanhanh addCoquanbanhanh(Coquanbanhanh coquanbanhanh) {
		coquanbanhanh.setNew(true);

		return coquanbanhanhPersistence.update(coquanbanhanh);
	}

	/**
	 * Creates a new coquanbanhanh with the primary key. Does not add the coquanbanhanh to the database.
	 *
	 * @param id the primary key for the new coquanbanhanh
	 * @return the new coquanbanhanh
	 */
	@Override
	@Transactional(enabled = false)
	public Coquanbanhanh createCoquanbanhanh(long id) {
		return coquanbanhanhPersistence.create(id);
	}

	/**
	 * Deletes the coquanbanhanh with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CoquanbanhanhLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the coquanbanhanh
	 * @return the coquanbanhanh that was removed
	 * @throws PortalException if a coquanbanhanh with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Coquanbanhanh deleteCoquanbanhanh(long id) throws PortalException {
		return coquanbanhanhPersistence.remove(id);
	}

	/**
	 * Deletes the coquanbanhanh from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CoquanbanhanhLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param coquanbanhanh the coquanbanhanh
	 * @return the coquanbanhanh that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Coquanbanhanh deleteCoquanbanhanh(Coquanbanhanh coquanbanhanh) {
		return coquanbanhanhPersistence.remove(coquanbanhanh);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Coquanbanhanh.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return coquanbanhanhPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.CoquanbanhanhModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return coquanbanhanhPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.CoquanbanhanhModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return coquanbanhanhPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return coquanbanhanhPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return coquanbanhanhPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Coquanbanhanh fetchCoquanbanhanh(long id) {
		return coquanbanhanhPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the coquanbanhanh with the primary key.
	 *
	 * @param id the primary key of the coquanbanhanh
	 * @return the coquanbanhanh
	 * @throws PortalException if a coquanbanhanh with the primary key could not be found
	 */
	@Override
	public Coquanbanhanh getCoquanbanhanh(long id) throws PortalException {
		return coquanbanhanhPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(coquanbanhanhLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Coquanbanhanh.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			coquanbanhanhLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Coquanbanhanh.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(coquanbanhanhLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Coquanbanhanh.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return coquanbanhanhPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return coquanbanhanhLocalService.deleteCoquanbanhanh(
			(Coquanbanhanh)persistedModel);
	}

	public BasePersistence<Coquanbanhanh> getBasePersistence() {
		return coquanbanhanhPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return coquanbanhanhPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the coquanbanhanhs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.CoquanbanhanhModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of coquanbanhanhs
	 * @param end the upper bound of the range of coquanbanhanhs (not inclusive)
	 * @return the range of coquanbanhanhs
	 */
	@Override
	public List<Coquanbanhanh> getCoquanbanhanhs(int start, int end) {
		return coquanbanhanhPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of coquanbanhanhs.
	 *
	 * @return the number of coquanbanhanhs
	 */
	@Override
	public int getCoquanbanhanhsCount() {
		return coquanbanhanhPersistence.countAll();
	}

	/**
	 * Updates the coquanbanhanh in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CoquanbanhanhLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param coquanbanhanh the coquanbanhanh
	 * @return the coquanbanhanh that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Coquanbanhanh updateCoquanbanhanh(Coquanbanhanh coquanbanhanh) {
		return coquanbanhanhPersistence.update(coquanbanhanh);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CoquanbanhanhLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		coquanbanhanhLocalService = (CoquanbanhanhLocalService)aopProxy;

		_setLocalServiceUtilService(coquanbanhanhLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CoquanbanhanhLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Coquanbanhanh.class;
	}

	protected String getModelClassName() {
		return Coquanbanhanh.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = coquanbanhanhPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CoquanbanhanhLocalService coquanbanhanhLocalService) {

		try {
			Field field = CoquanbanhanhLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, coquanbanhanhLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CapbanhanhPersistence capbanhanhPersistence;

	protected CoquanbanhanhLocalService coquanbanhanhLocalService;

	@Reference
	protected CoquanbanhanhPersistence coquanbanhanhPersistence;

	@Reference
	protected dinhkemfilePersistence dinhkemfilePersistence;

	@Reference
	protected LinhvucvanbanPersistence linhvucvanbanPersistence;

	@Reference
	protected LoaivanbanPersistence loaivanbanPersistence;

	@Reference
	protected VanbanphapquyPersistence vanbanphapquyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}