/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.vanbanphapquy.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.vanbanphapquy.model.Loaivanban;
import vn.dnict.vanbanphapquy.service.LoaivanbanLocalService;
import vn.dnict.vanbanphapquy.service.LoaivanbanLocalServiceUtil;
import vn.dnict.vanbanphapquy.service.persistence.CapbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.CoquanbanhanhPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LinhvucvanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.LoaivanbanPersistence;
import vn.dnict.vanbanphapquy.service.persistence.VanbanphapquyPersistence;
import vn.dnict.vanbanphapquy.service.persistence.dinhkemfilePersistence;

/**
 * Provides the base implementation for the loaivanban local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.vanbanphapquy.service.impl.LoaivanbanLocalServiceImpl}.
 * </p>
 *
 * @author BinhNT
 * @see vn.dnict.vanbanphapquy.service.impl.LoaivanbanLocalServiceImpl
 * @generated
 */
public abstract class LoaivanbanLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, LoaivanbanLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LoaivanbanLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LoaivanbanLocalServiceUtil</code>.
	 */

	/**
	 * Adds the loaivanban to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoaivanbanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loaivanban the loaivanban
	 * @return the loaivanban that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Loaivanban addLoaivanban(Loaivanban loaivanban) {
		loaivanban.setNew(true);

		return loaivanbanPersistence.update(loaivanban);
	}

	/**
	 * Creates a new loaivanban with the primary key. Does not add the loaivanban to the database.
	 *
	 * @param id the primary key for the new loaivanban
	 * @return the new loaivanban
	 */
	@Override
	@Transactional(enabled = false)
	public Loaivanban createLoaivanban(long id) {
		return loaivanbanPersistence.create(id);
	}

	/**
	 * Deletes the loaivanban with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoaivanbanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the loaivanban
	 * @return the loaivanban that was removed
	 * @throws PortalException if a loaivanban with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Loaivanban deleteLoaivanban(long id) throws PortalException {
		return loaivanbanPersistence.remove(id);
	}

	/**
	 * Deletes the loaivanban from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoaivanbanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loaivanban the loaivanban
	 * @return the loaivanban that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Loaivanban deleteLoaivanban(Loaivanban loaivanban) {
		return loaivanbanPersistence.remove(loaivanban);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Loaivanban.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return loaivanbanPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.LoaivanbanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return loaivanbanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.LoaivanbanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return loaivanbanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return loaivanbanPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return loaivanbanPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Loaivanban fetchLoaivanban(long id) {
		return loaivanbanPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the loaivanban with the primary key.
	 *
	 * @param id the primary key of the loaivanban
	 * @return the loaivanban
	 * @throws PortalException if a loaivanban with the primary key could not be found
	 */
	@Override
	public Loaivanban getLoaivanban(long id) throws PortalException {
		return loaivanbanPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(loaivanbanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Loaivanban.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			loaivanbanLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Loaivanban.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(loaivanbanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Loaivanban.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return loaivanbanPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return loaivanbanLocalService.deleteLoaivanban(
			(Loaivanban)persistedModel);
	}

	public BasePersistence<Loaivanban> getBasePersistence() {
		return loaivanbanPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return loaivanbanPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the loaivanbans.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.vanbanphapquy.model.impl.LoaivanbanModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of loaivanbans
	 * @param end the upper bound of the range of loaivanbans (not inclusive)
	 * @return the range of loaivanbans
	 */
	@Override
	public List<Loaivanban> getLoaivanbans(int start, int end) {
		return loaivanbanPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of loaivanbans.
	 *
	 * @return the number of loaivanbans
	 */
	@Override
	public int getLoaivanbansCount() {
		return loaivanbanPersistence.countAll();
	}

	/**
	 * Updates the loaivanban in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoaivanbanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loaivanban the loaivanban
	 * @return the loaivanban that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Loaivanban updateLoaivanban(Loaivanban loaivanban) {
		return loaivanbanPersistence.update(loaivanban);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			LoaivanbanLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		loaivanbanLocalService = (LoaivanbanLocalService)aopProxy;

		_setLocalServiceUtilService(loaivanbanLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LoaivanbanLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Loaivanban.class;
	}

	protected String getModelClassName() {
		return Loaivanban.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = loaivanbanPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		LoaivanbanLocalService loaivanbanLocalService) {

		try {
			Field field = LoaivanbanLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, loaivanbanLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected CapbanhanhPersistence capbanhanhPersistence;

	@Reference
	protected CoquanbanhanhPersistence coquanbanhanhPersistence;

	@Reference
	protected dinhkemfilePersistence dinhkemfilePersistence;

	@Reference
	protected LinhvucvanbanPersistence linhvucvanbanPersistence;

	protected LoaivanbanLocalService loaivanbanLocalService;

	@Reference
	protected LoaivanbanPersistence loaivanbanPersistence;

	@Reference
	protected VanbanphapquyPersistence vanbanphapquyPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}