/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package lichcoquan.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Lichcoquan service. Represents a row in the &quot;lcq_lichcoquan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>lichcoquan.service.model.impl.LichcoquanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>lichcoquan.service.model.impl.LichcoquanImpl</code>.
 * </p>
 *
 * @author BinhNT
 * @see Lichcoquan
 * @generated
 */
@ProviderType
public interface LichcoquanModel extends BaseModel<Lichcoquan>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a lichcoquan model instance should use the {@link Lichcoquan} interface instead.
	 */

	/**
	 * Returns the primary key of this lichcoquan.
	 *
	 * @return the primary key of this lichcoquan
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this lichcoquan.
	 *
	 * @param primaryKey the primary key of this lichcoquan
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the lich congtac ID of this lichcoquan.
	 *
	 * @return the lich congtac ID of this lichcoquan
	 */
	public long getLichCongtacId();

	/**
	 * Sets the lich congtac ID of this lichcoquan.
	 *
	 * @param lichCongtacId the lich congtac ID of this lichcoquan
	 */
	public void setLichCongtacId(long lichCongtacId);

	/**
	 * Returns the company ID of this lichcoquan.
	 *
	 * @return the company ID of this lichcoquan
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this lichcoquan.
	 *
	 * @param companyId the company ID of this lichcoquan
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this lichcoquan.
	 *
	 * @return the user ID of this lichcoquan
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this lichcoquan.
	 *
	 * @param userId the user ID of this lichcoquan
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this lichcoquan.
	 *
	 * @return the user uuid of this lichcoquan
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this lichcoquan.
	 *
	 * @param userUuid the user uuid of this lichcoquan
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the content of this lichcoquan.
	 *
	 * @return the content of this lichcoquan
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this lichcoquan.
	 *
	 * @param content the content of this lichcoquan
	 */
	public void setContent(String content);

	/**
	 * Returns the create date of this lichcoquan.
	 *
	 * @return the create date of this lichcoquan
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this lichcoquan.
	 *
	 * @param createDate the create date of this lichcoquan
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the tungay of this lichcoquan.
	 *
	 * @return the tungay of this lichcoquan
	 */
	public Date getTungay();

	/**
	 * Sets the tungay of this lichcoquan.
	 *
	 * @param tungay the tungay of this lichcoquan
	 */
	public void setTungay(Date tungay);

	/**
	 * Returns the denngay of this lichcoquan.
	 *
	 * @return the denngay of this lichcoquan
	 */
	public Date getDenngay();

	/**
	 * Sets the denngay of this lichcoquan.
	 *
	 * @param denngay the denngay of this lichcoquan
	 */
	public void setDenngay(Date denngay);

	/**
	 * Returns the trangthai of this lichcoquan.
	 *
	 * @return the trangthai of this lichcoquan
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this lichcoquan.
	 *
	 * @param trangthai the trangthai of this lichcoquan
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the banhanh of this lichcoquan.
	 *
	 * @return the banhanh of this lichcoquan
	 */
	public int getBanhanh();

	/**
	 * Sets the banhanh of this lichcoquan.
	 *
	 * @param banhanh the banhanh of this lichcoquan
	 */
	public void setBanhanh(int banhanh);

	/**
	 * Returns the tuan of this lichcoquan.
	 *
	 * @return the tuan of this lichcoquan
	 */
	public int getTuan();

	/**
	 * Sets the tuan of this lichcoquan.
	 *
	 * @param tuan the tuan of this lichcoquan
	 */
	public void setTuan(int tuan);

	/**
	 * Returns the nam of this lichcoquan.
	 *
	 * @return the nam of this lichcoquan
	 */
	public int getNam();

	/**
	 * Sets the nam of this lichcoquan.
	 *
	 * @param nam the nam of this lichcoquan
	 */
	public void setNam(int nam);

}