/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package cms.quanlyvideo.service.base;

import cms.quanlyvideo.model.ChuDe;
import cms.quanlyvideo.service.ChuDeService;
import cms.quanlyvideo.service.ChuDeServiceUtil;
import cms.quanlyvideo.service.persistence.ChuDePersistence;
import cms.quanlyvideo.service.persistence.ChuDeVideoPersistence;
import cms.quanlyvideo.service.persistence.VideoPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the chu de remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link cms.quanlyvideo.service.impl.ChuDeServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see cms.quanlyvideo.service.impl.ChuDeServiceImpl
 * @generated
 */
public abstract class ChuDeServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, ChuDeService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ChuDeService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ChuDeServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		ChuDeServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ChuDeService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		chuDeService = (ChuDeService)aopProxy;

		ChuDeServiceUtil.setService(chuDeService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ChuDeService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ChuDe.class;
	}

	protected String getModelClassName() {
		return ChuDe.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = chuDePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected cms.quanlyvideo.service.ChuDeLocalService chuDeLocalService;

	protected ChuDeService chuDeService;

	@Reference
	protected ChuDePersistence chuDePersistence;

	@Reference
	protected ChuDeVideoPersistence chuDeVideoPersistence;

	@Reference
	protected VideoPersistence videoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		ChuDeServiceBaseImpl.class);

}