/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.tintuc.model.News_AttachFile;
import vn.dnict.tintuc.service.News_AttachFileLocalService;
import vn.dnict.tintuc.service.News_AttachFileLocalServiceUtil;
import vn.dnict.tintuc.service.persistence.News_ActivityPersistence;
import vn.dnict.tintuc.service.persistence.News_Article2CategoryPersistence;
import vn.dnict.tintuc.service.persistence.News_ArticlePersistence;
import vn.dnict.tintuc.service.persistence.News_AttachFilePersistence;
import vn.dnict.tintuc.service.persistence.News_BinhLuanPersistence;
import vn.dnict.tintuc.service.persistence.News_CategoriesPersistence;
import vn.dnict.tintuc.service.persistence.News_LogPersistence;
import vn.dnict.tintuc.service.persistence.News_NguonTinPersistence;
import vn.dnict.tintuc.service.persistence.News_SubcategoriesPersistence;
import vn.dnict.tintuc.service.persistence.News_TypePersistence;
import vn.dnict.tintuc.service.persistence.News_rolePersistence;

/**
 * Provides the base implementation for the news_ attach file local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.tintuc.service.impl.News_AttachFileLocalServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see vn.dnict.tintuc.service.impl.News_AttachFileLocalServiceImpl
 * @generated
 */
public abstract class News_AttachFileLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   News_AttachFileLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>News_AttachFileLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>News_AttachFileLocalServiceUtil</code>.
	 */

	/**
	 * Adds the news_ attach file to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect News_AttachFileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param news_AttachFile the news_ attach file
	 * @return the news_ attach file that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public News_AttachFile addNews_AttachFile(News_AttachFile news_AttachFile) {
		news_AttachFile.setNew(true);

		return news_AttachFilePersistence.update(news_AttachFile);
	}

	/**
	 * Creates a new news_ attach file with the primary key. Does not add the news_ attach file to the database.
	 *
	 * @param id the primary key for the new news_ attach file
	 * @return the new news_ attach file
	 */
	@Override
	@Transactional(enabled = false)
	public News_AttachFile createNews_AttachFile(long id) {
		return news_AttachFilePersistence.create(id);
	}

	/**
	 * Deletes the news_ attach file with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect News_AttachFileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the news_ attach file
	 * @return the news_ attach file that was removed
	 * @throws PortalException if a news_ attach file with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public News_AttachFile deleteNews_AttachFile(long id)
		throws PortalException {

		return news_AttachFilePersistence.remove(id);
	}

	/**
	 * Deletes the news_ attach file from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect News_AttachFileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param news_AttachFile the news_ attach file
	 * @return the news_ attach file that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public News_AttachFile deleteNews_AttachFile(
		News_AttachFile news_AttachFile) {

		return news_AttachFilePersistence.remove(news_AttachFile);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			News_AttachFile.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return news_AttachFilePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.tintuc.model.impl.News_AttachFileModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return news_AttachFilePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.tintuc.model.impl.News_AttachFileModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return news_AttachFilePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return news_AttachFilePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return news_AttachFilePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public News_AttachFile fetchNews_AttachFile(long id) {
		return news_AttachFilePersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the news_ attach file with the primary key.
	 *
	 * @param id the primary key of the news_ attach file
	 * @return the news_ attach file
	 * @throws PortalException if a news_ attach file with the primary key could not be found
	 */
	@Override
	public News_AttachFile getNews_AttachFile(long id) throws PortalException {
		return news_AttachFilePersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(news_AttachFileLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(News_AttachFile.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			news_AttachFileLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(News_AttachFile.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(news_AttachFileLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(News_AttachFile.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return news_AttachFilePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return news_AttachFileLocalService.deleteNews_AttachFile(
			(News_AttachFile)persistedModel);
	}

	public BasePersistence<News_AttachFile> getBasePersistence() {
		return news_AttachFilePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return news_AttachFilePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the news_ attach files.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>vn.dnict.tintuc.model.impl.News_AttachFileModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of news_ attach files
	 * @param end the upper bound of the range of news_ attach files (not inclusive)
	 * @return the range of news_ attach files
	 */
	@Override
	public List<News_AttachFile> getNews_AttachFiles(int start, int end) {
		return news_AttachFilePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of news_ attach files.
	 *
	 * @return the number of news_ attach files
	 */
	@Override
	public int getNews_AttachFilesCount() {
		return news_AttachFilePersistence.countAll();
	}

	/**
	 * Updates the news_ attach file in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect News_AttachFileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param news_AttachFile the news_ attach file
	 * @return the news_ attach file that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public News_AttachFile updateNews_AttachFile(
		News_AttachFile news_AttachFile) {

		return news_AttachFilePersistence.update(news_AttachFile);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			News_AttachFileLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		news_AttachFileLocalService = (News_AttachFileLocalService)aopProxy;

		_setLocalServiceUtilService(news_AttachFileLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return News_AttachFileLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return News_AttachFile.class;
	}

	protected String getModelClassName() {
		return News_AttachFile.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = news_AttachFilePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		News_AttachFileLocalService news_AttachFileLocalService) {

		try {
			Field field =
				News_AttachFileLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, news_AttachFileLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected News_ActivityPersistence news_ActivityPersistence;

	@Reference
	protected News_ArticlePersistence news_ArticlePersistence;

	@Reference
	protected News_Article2CategoryPersistence news_Article2CategoryPersistence;

	protected News_AttachFileLocalService news_AttachFileLocalService;

	@Reference
	protected News_AttachFilePersistence news_AttachFilePersistence;

	@Reference
	protected News_BinhLuanPersistence news_BinhLuanPersistence;

	@Reference
	protected News_CategoriesPersistence news_CategoriesPersistence;

	@Reference
	protected News_LogPersistence news_LogPersistence;

	@Reference
	protected News_NguonTinPersistence news_NguonTinPersistence;

	@Reference
	protected News_rolePersistence news_rolePersistence;

	@Reference
	protected News_SubcategoriesPersistence news_SubcategoriesPersistence;

	@Reference
	protected News_TypePersistence news_TypePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}