/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.service.base;

import com.contact.model.PhongBan;
import com.contact.service.PhongBanService;
import com.contact.service.PhongBanServiceUtil;
import com.contact.service.persistence.CanBoPersistence;
import com.contact.service.persistence.PhongBanPersistence;
import com.contact.service.persistence.ToChucPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the phong ban remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.contact.service.impl.PhongBanServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.contact.service.impl.PhongBanServiceImpl
 * @generated
 */
public abstract class PhongBanServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, PhongBanService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PhongBanService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PhongBanServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		PhongBanServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PhongBanService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		phongBanService = (PhongBanService)aopProxy;

		PhongBanServiceUtil.setService(phongBanService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PhongBanService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PhongBan.class;
	}

	protected String getModelClassName() {
		return PhongBan.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = phongBanPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected CanBoPersistence canBoPersistence;

	@Reference
	protected com.contact.service.PhongBanLocalService phongBanLocalService;

	protected PhongBanService phongBanService;

	@Reference
	protected PhongBanPersistence phongBanPersistence;

	@Reference
	protected ToChucPersistence toChucPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		PhongBanServiceBaseImpl.class);

}