/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package lichcoquan.service.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import lichcoquan.service.model.CmsLichCoQuan;
import lichcoquan.service.service.CmsLichCoQuanLocalService;
import lichcoquan.service.service.CmsLichCoQuanLocalServiceUtil;
import lichcoquan.service.service.persistence.CmsLichCoQuanPersistence;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cms lich co quan local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link lichcoquan.service.service.impl.CmsLichCoQuanLocalServiceImpl}.
 * </p>
 *
 * @author BinhNT
 * @see lichcoquan.service.service.impl.CmsLichCoQuanLocalServiceImpl
 * @generated
 */
public abstract class CmsLichCoQuanLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CmsLichCoQuanLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CmsLichCoQuanLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CmsLichCoQuanLocalServiceUtil</code>.
	 */

	/**
	 * Adds the cms lich co quan to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CmsLichCoQuanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cmsLichCoQuan the cms lich co quan
	 * @return the cms lich co quan that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CmsLichCoQuan addCmsLichCoQuan(CmsLichCoQuan cmsLichCoQuan) {
		cmsLichCoQuan.setNew(true);

		return cmsLichCoQuanPersistence.update(cmsLichCoQuan);
	}

	/**
	 * Creates a new cms lich co quan with the primary key. Does not add the cms lich co quan to the database.
	 *
	 * @param lichCongtacId the primary key for the new cms lich co quan
	 * @return the new cms lich co quan
	 */
	@Override
	@Transactional(enabled = false)
	public CmsLichCoQuan createCmsLichCoQuan(long lichCongtacId) {
		return cmsLichCoQuanPersistence.create(lichCongtacId);
	}

	/**
	 * Deletes the cms lich co quan with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CmsLichCoQuanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param lichCongtacId the primary key of the cms lich co quan
	 * @return the cms lich co quan that was removed
	 * @throws PortalException if a cms lich co quan with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CmsLichCoQuan deleteCmsLichCoQuan(long lichCongtacId)
		throws PortalException {

		return cmsLichCoQuanPersistence.remove(lichCongtacId);
	}

	/**
	 * Deletes the cms lich co quan from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CmsLichCoQuanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cmsLichCoQuan the cms lich co quan
	 * @return the cms lich co quan that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CmsLichCoQuan deleteCmsLichCoQuan(CmsLichCoQuan cmsLichCoQuan) {
		return cmsLichCoQuanPersistence.remove(cmsLichCoQuan);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CmsLichCoQuan.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return cmsLichCoQuanPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>lichcoquan.service.model.impl.CmsLichCoQuanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return cmsLichCoQuanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>lichcoquan.service.model.impl.CmsLichCoQuanModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return cmsLichCoQuanPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return cmsLichCoQuanPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return cmsLichCoQuanPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CmsLichCoQuan fetchCmsLichCoQuan(long lichCongtacId) {
		return cmsLichCoQuanPersistence.fetchByPrimaryKey(lichCongtacId);
	}

	/**
	 * Returns the cms lich co quan with the primary key.
	 *
	 * @param lichCongtacId the primary key of the cms lich co quan
	 * @return the cms lich co quan
	 * @throws PortalException if a cms lich co quan with the primary key could not be found
	 */
	@Override
	public CmsLichCoQuan getCmsLichCoQuan(long lichCongtacId)
		throws PortalException {

		return cmsLichCoQuanPersistence.findByPrimaryKey(lichCongtacId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(cmsLichCoQuanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CmsLichCoQuan.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("lichCongtacId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			cmsLichCoQuanLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CmsLichCoQuan.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"lichCongtacId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(cmsLichCoQuanLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CmsLichCoQuan.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("lichCongtacId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cmsLichCoQuanPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return cmsLichCoQuanLocalService.deleteCmsLichCoQuan(
			(CmsLichCoQuan)persistedModel);
	}

	public BasePersistence<CmsLichCoQuan> getBasePersistence() {
		return cmsLichCoQuanPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return cmsLichCoQuanPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the cms lich co quans.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>lichcoquan.service.model.impl.CmsLichCoQuanModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of cms lich co quans
	 * @param end the upper bound of the range of cms lich co quans (not inclusive)
	 * @return the range of cms lich co quans
	 */
	@Override
	public List<CmsLichCoQuan> getCmsLichCoQuans(int start, int end) {
		return cmsLichCoQuanPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of cms lich co quans.
	 *
	 * @return the number of cms lich co quans
	 */
	@Override
	public int getCmsLichCoQuansCount() {
		return cmsLichCoQuanPersistence.countAll();
	}

	/**
	 * Updates the cms lich co quan in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CmsLichCoQuanLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param cmsLichCoQuan the cms lich co quan
	 * @return the cms lich co quan that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CmsLichCoQuan updateCmsLichCoQuan(CmsLichCoQuan cmsLichCoQuan) {
		return cmsLichCoQuanPersistence.update(cmsLichCoQuan);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CmsLichCoQuanLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cmsLichCoQuanLocalService = (CmsLichCoQuanLocalService)aopProxy;

		_setLocalServiceUtilService(cmsLichCoQuanLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CmsLichCoQuanLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CmsLichCoQuan.class;
	}

	protected String getModelClassName() {
		return CmsLichCoQuan.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = cmsLichCoQuanPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CmsLichCoQuanLocalService cmsLichCoQuanLocalService) {

		try {
			Field field = CmsLichCoQuanLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, cmsLichCoQuanLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected CmsLichCoQuanLocalService cmsLichCoQuanLocalService;

	@Reference
	protected CmsLichCoQuanPersistence cmsLichCoQuanPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}