/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package lichcoquan.service.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import lichcoquan.service.model.CmsLichCoQuan;
import lichcoquan.service.service.CmsLichCoQuanService;
import lichcoquan.service.service.CmsLichCoQuanServiceUtil;
import lichcoquan.service.service.persistence.CmsLichCoQuanPersistence;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the cms lich co quan remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link lichcoquan.service.service.impl.CmsLichCoQuanServiceImpl}.
 * </p>
 *
 * @author BinhNT
 * @see lichcoquan.service.service.impl.CmsLichCoQuanServiceImpl
 * @generated
 */
public abstract class CmsLichCoQuanServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, CmsLichCoQuanService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CmsLichCoQuanService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CmsLichCoQuanServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CmsLichCoQuanService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		cmsLichCoQuanService = (CmsLichCoQuanService)aopProxy;

		_setServiceUtilService(cmsLichCoQuanService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CmsLichCoQuanService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CmsLichCoQuan.class;
	}

	protected String getModelClassName() {
		return CmsLichCoQuan.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = cmsLichCoQuanPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		CmsLichCoQuanService cmsLichCoQuanService) {

		try {
			Field field = CmsLichCoQuanServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, cmsLichCoQuanService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected lichcoquan.service.service.CmsLichCoQuanLocalService
		cmsLichCoQuanLocalService;

	protected CmsLichCoQuanService cmsLichCoQuanService;

	@Reference
	protected CmsLichCoQuanPersistence cmsLichCoQuanPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}