/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlquangcao.model.impl;

import vn.dnict.qlquangcao.model.BangQuangCao;
import vn.dnict.qlquangcao.service.BangQuangCaoLocalServiceUtil;

/**
 * The extended model base implementation for the BangQuangCao service. Represents a row in the &quot;cw_quangcao_banner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BangQuangCaoImpl}.
 * </p>
 *
 * @author dnict
 * @see BangQuangCaoImpl
 * @see BangQuangCao
 * @generated
 */
public abstract class BangQuangCaoBaseImpl
	extends BangQuangCaoModelImpl implements BangQuangCao {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bang quang cao model instance should use the <code>BangQuangCao</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BangQuangCaoLocalServiceUtil.addBangQuangCao(this);
		}
		else {
			BangQuangCaoLocalServiceUtil.updateBangQuangCao(this);
		}
	}

}