/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlquangcao.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlquangcao.model.NhomKH;
import vn.dnict.qlquangcao.model.NhomKHModel;
import vn.dnict.qlquangcao.model.NhomKHSoap;

/**
 * The base model implementation for the NhomKH service. Represents a row in the &quot;cw_quangcao_nhomkhachhang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NhomKHModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NhomKHImpl}.
 * </p>
 *
 * @author dnict
 * @see NhomKHImpl
 * @generated
 */
@JSON(strict = true)
public class NhomKHModelImpl
	extends BaseModelImpl<NhomKH> implements NhomKHModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nhom kh model instance should use the <code>NhomKH</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_quangcao_nhomkhachhang";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"nguoitao", Types.BIGINT},
		{"ten", Types.VARCHAR}, {"nguoidaidien", Types.VARCHAR},
		{"logo", Types.VARCHAR}, {"mota", Types.VARCHAR},
		{"diachi", Types.VARCHAR}, {"sdt", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"ngaytao", Types.TIMESTAMP},
		{"daxoa", Types.INTEGER}, {"trangthai", Types.INTEGER},
		{"ngaysua", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoitao", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nguoidaidien", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mota", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("diachi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sdt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ngaytao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("daxoa", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("trangthai", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ngaysua", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_quangcao_nhomkhachhang (id_ LONG not null primary key,companyId LONG,groupId LONG,nguoitao LONG,ten VARCHAR(75) null,nguoidaidien VARCHAR(75) null,logo VARCHAR(75) null,mota VARCHAR(75) null,diachi VARCHAR(75) null,sdt VARCHAR(75) null,email VARCHAR(75) null,ngaytao DATE null,daxoa INTEGER,trangthai INTEGER,ngaysua DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_quangcao_nhomkhachhang";

	public static final String ORDER_BY_JPQL = " ORDER BY nhomKH.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_quangcao_nhomkhachhang.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static NhomKH toModel(NhomKHSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NhomKH model = new NhomKHImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setNguoitao(soapModel.getNguoitao());
		model.setTen(soapModel.getTen());
		model.setNguoidaidien(soapModel.getNguoidaidien());
		model.setLogo(soapModel.getLogo());
		model.setMota(soapModel.getMota());
		model.setDiachi(soapModel.getDiachi());
		model.setSdt(soapModel.getSdt());
		model.setEmail(soapModel.getEmail());
		model.setNgaytao(soapModel.getNgaytao());
		model.setDaxoa(soapModel.getDaxoa());
		model.setTrangthai(soapModel.getTrangthai());
		model.setNgaysua(soapModel.getNgaysua());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<NhomKH> toModels(NhomKHSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NhomKH> models = new ArrayList<NhomKH>(soapModels.length);

		for (NhomKHSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public NhomKHModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NhomKH.class;
	}

	@Override
	public String getModelClassName() {
		return NhomKH.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NhomKH, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NhomKH, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NhomKH, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((NhomKH)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NhomKH, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NhomKH, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NhomKH)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NhomKH, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NhomKH, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<NhomKH, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<NhomKH, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NhomKH, Object>>();

		attributeGetterFunctions.put("id", NhomKH::getId);
		attributeGetterFunctions.put("companyId", NhomKH::getCompanyId);
		attributeGetterFunctions.put("groupId", NhomKH::getGroupId);
		attributeGetterFunctions.put("nguoitao", NhomKH::getNguoitao);
		attributeGetterFunctions.put("ten", NhomKH::getTen);
		attributeGetterFunctions.put("nguoidaidien", NhomKH::getNguoidaidien);
		attributeGetterFunctions.put("logo", NhomKH::getLogo);
		attributeGetterFunctions.put("mota", NhomKH::getMota);
		attributeGetterFunctions.put("diachi", NhomKH::getDiachi);
		attributeGetterFunctions.put("sdt", NhomKH::getSdt);
		attributeGetterFunctions.put("email", NhomKH::getEmail);
		attributeGetterFunctions.put("ngaytao", NhomKH::getNgaytao);
		attributeGetterFunctions.put("daxoa", NhomKH::getDaxoa);
		attributeGetterFunctions.put("trangthai", NhomKH::getTrangthai);
		attributeGetterFunctions.put("ngaysua", NhomKH::getNgaysua);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<NhomKH, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<NhomKH, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NhomKH, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<NhomKH, Long>)NhomKH::setId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<NhomKH, Long>)NhomKH::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<NhomKH, Long>)NhomKH::setGroupId);
		attributeSetterBiConsumers.put(
			"nguoitao", (BiConsumer<NhomKH, Long>)NhomKH::setNguoitao);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<NhomKH, String>)NhomKH::setTen);
		attributeSetterBiConsumers.put(
			"nguoidaidien",
			(BiConsumer<NhomKH, String>)NhomKH::setNguoidaidien);
		attributeSetterBiConsumers.put(
			"logo", (BiConsumer<NhomKH, String>)NhomKH::setLogo);
		attributeSetterBiConsumers.put(
			"mota", (BiConsumer<NhomKH, String>)NhomKH::setMota);
		attributeSetterBiConsumers.put(
			"diachi", (BiConsumer<NhomKH, String>)NhomKH::setDiachi);
		attributeSetterBiConsumers.put(
			"sdt", (BiConsumer<NhomKH, String>)NhomKH::setSdt);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<NhomKH, String>)NhomKH::setEmail);
		attributeSetterBiConsumers.put(
			"ngaytao", (BiConsumer<NhomKH, Date>)NhomKH::setNgaytao);
		attributeSetterBiConsumers.put(
			"daxoa", (BiConsumer<NhomKH, Integer>)NhomKH::setDaxoa);
		attributeSetterBiConsumers.put(
			"trangthai", (BiConsumer<NhomKH, Integer>)NhomKH::setTrangthai);
		attributeSetterBiConsumers.put(
			"ngaysua", (BiConsumer<NhomKH, Date>)NhomKH::setNgaysua);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getNguoitao() {
		return _nguoitao;
	}

	@Override
	public void setNguoitao(long nguoitao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoitao = nguoitao;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@JSON
	@Override
	public String getNguoidaidien() {
		if (_nguoidaidien == null) {
			return "";
		}
		else {
			return _nguoidaidien;
		}
	}

	@Override
	public void setNguoidaidien(String nguoidaidien) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoidaidien = nguoidaidien;
	}

	@JSON
	@Override
	public String getLogo() {
		if (_logo == null) {
			return "";
		}
		else {
			return _logo;
		}
	}

	@Override
	public void setLogo(String logo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logo = logo;
	}

	@JSON
	@Override
	public String getMota() {
		if (_mota == null) {
			return "";
		}
		else {
			return _mota;
		}
	}

	@Override
	public void setMota(String mota) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mota = mota;
	}

	@JSON
	@Override
	public String getDiachi() {
		if (_diachi == null) {
			return "";
		}
		else {
			return _diachi;
		}
	}

	@Override
	public void setDiachi(String diachi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_diachi = diachi;
	}

	@JSON
	@Override
	public String getSdt() {
		if (_sdt == null) {
			return "";
		}
		else {
			return _sdt;
		}
	}

	@Override
	public void setSdt(String sdt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sdt = sdt;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public Date getNgaytao() {
		return _ngaytao;
	}

	@Override
	public void setNgaytao(Date ngaytao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaytao = ngaytao;
	}

	@JSON
	@Override
	public int getDaxoa() {
		return _daxoa;
	}

	@Override
	public void setDaxoa(int daxoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_daxoa = daxoa;
	}

	@JSON
	@Override
	public int getTrangthai() {
		return _trangthai;
	}

	@Override
	public void setTrangthai(int trangthai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trangthai = trangthai;
	}

	@JSON
	@Override
	public Date getNgaysua() {
		return _ngaysua;
	}

	@Override
	public void setNgaysua(Date ngaysua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaysua = ngaysua;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NhomKH.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NhomKH toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NhomKH>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NhomKHImpl nhomKHImpl = new NhomKHImpl();

		nhomKHImpl.setId(getId());
		nhomKHImpl.setCompanyId(getCompanyId());
		nhomKHImpl.setGroupId(getGroupId());
		nhomKHImpl.setNguoitao(getNguoitao());
		nhomKHImpl.setTen(getTen());
		nhomKHImpl.setNguoidaidien(getNguoidaidien());
		nhomKHImpl.setLogo(getLogo());
		nhomKHImpl.setMota(getMota());
		nhomKHImpl.setDiachi(getDiachi());
		nhomKHImpl.setSdt(getSdt());
		nhomKHImpl.setEmail(getEmail());
		nhomKHImpl.setNgaytao(getNgaytao());
		nhomKHImpl.setDaxoa(getDaxoa());
		nhomKHImpl.setTrangthai(getTrangthai());
		nhomKHImpl.setNgaysua(getNgaysua());

		nhomKHImpl.resetOriginalValues();

		return nhomKHImpl;
	}

	@Override
	public int compareTo(NhomKH nhomKH) {
		int value = 0;

		if (getId() < nhomKH.getId()) {
			value = -1;
		}
		else if (getId() > nhomKH.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NhomKH)) {
			return false;
		}

		NhomKH nhomKH = (NhomKH)object;

		long primaryKey = nhomKH.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NhomKH> toCacheModel() {
		NhomKHCacheModel nhomKHCacheModel = new NhomKHCacheModel();

		nhomKHCacheModel.id = getId();

		nhomKHCacheModel.companyId = getCompanyId();

		nhomKHCacheModel.groupId = getGroupId();

		nhomKHCacheModel.nguoitao = getNguoitao();

		nhomKHCacheModel.ten = getTen();

		String ten = nhomKHCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			nhomKHCacheModel.ten = null;
		}

		nhomKHCacheModel.nguoidaidien = getNguoidaidien();

		String nguoidaidien = nhomKHCacheModel.nguoidaidien;

		if ((nguoidaidien != null) && (nguoidaidien.length() == 0)) {
			nhomKHCacheModel.nguoidaidien = null;
		}

		nhomKHCacheModel.logo = getLogo();

		String logo = nhomKHCacheModel.logo;

		if ((logo != null) && (logo.length() == 0)) {
			nhomKHCacheModel.logo = null;
		}

		nhomKHCacheModel.mota = getMota();

		String mota = nhomKHCacheModel.mota;

		if ((mota != null) && (mota.length() == 0)) {
			nhomKHCacheModel.mota = null;
		}

		nhomKHCacheModel.diachi = getDiachi();

		String diachi = nhomKHCacheModel.diachi;

		if ((diachi != null) && (diachi.length() == 0)) {
			nhomKHCacheModel.diachi = null;
		}

		nhomKHCacheModel.sdt = getSdt();

		String sdt = nhomKHCacheModel.sdt;

		if ((sdt != null) && (sdt.length() == 0)) {
			nhomKHCacheModel.sdt = null;
		}

		nhomKHCacheModel.email = getEmail();

		String email = nhomKHCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			nhomKHCacheModel.email = null;
		}

		Date ngaytao = getNgaytao();

		if (ngaytao != null) {
			nhomKHCacheModel.ngaytao = ngaytao.getTime();
		}
		else {
			nhomKHCacheModel.ngaytao = Long.MIN_VALUE;
		}

		nhomKHCacheModel.daxoa = getDaxoa();

		nhomKHCacheModel.trangthai = getTrangthai();

		Date ngaysua = getNgaysua();

		if (ngaysua != null) {
			nhomKHCacheModel.ngaysua = ngaysua.getTime();
		}
		else {
			nhomKHCacheModel.ngaysua = Long.MIN_VALUE;
		}

		return nhomKHCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NhomKH, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NhomKH, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NhomKH, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((NhomKH)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NhomKH, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NhomKH, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NhomKH, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NhomKH)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NhomKH>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					NhomKH.class, ModelWrapper.class);

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private long _nguoitao;
	private String _ten;
	private String _nguoidaidien;
	private String _logo;
	private String _mota;
	private String _diachi;
	private String _sdt;
	private String _email;
	private Date _ngaytao;
	private int _daxoa;
	private int _trangthai;
	private Date _ngaysua;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NhomKH, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NhomKH)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("nguoitao", _nguoitao);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("nguoidaidien", _nguoidaidien);
		_columnOriginalValues.put("logo", _logo);
		_columnOriginalValues.put("mota", _mota);
		_columnOriginalValues.put("diachi", _diachi);
		_columnOriginalValues.put("sdt", _sdt);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("ngaytao", _ngaytao);
		_columnOriginalValues.put("daxoa", _daxoa);
		_columnOriginalValues.put("trangthai", _trangthai);
		_columnOriginalValues.put("ngaysua", _ngaysua);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("nguoitao", 8L);

		columnBitmasks.put("ten", 16L);

		columnBitmasks.put("nguoidaidien", 32L);

		columnBitmasks.put("logo", 64L);

		columnBitmasks.put("mota", 128L);

		columnBitmasks.put("diachi", 256L);

		columnBitmasks.put("sdt", 512L);

		columnBitmasks.put("email", 1024L);

		columnBitmasks.put("ngaytao", 2048L);

		columnBitmasks.put("daxoa", 4096L);

		columnBitmasks.put("trangthai", 8192L);

		columnBitmasks.put("ngaysua", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NhomKH _escapedModel;

}