/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlquangcao.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlquangcao.model.ViTriDanhMuc;
import vn.dnict.qlquangcao.model.ViTriDanhMucModel;
import vn.dnict.qlquangcao.model.ViTriDanhMucSoap;

/**
 * The base model implementation for the ViTriDanhMuc service. Represents a row in the &quot;cw_quangcao_vitridanhmuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ViTriDanhMucModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViTriDanhMucImpl}.
 * </p>
 *
 * @author dnict
 * @see ViTriDanhMucImpl
 * @generated
 */
@JSON(strict = true)
public class ViTriDanhMucModelImpl
	extends BaseModelImpl<ViTriDanhMuc> implements ViTriDanhMucModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vi tri danh muc model instance should use the <code>ViTriDanhMuc</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_quangcao_vitridanhmuc";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"nguoitao", Types.BIGINT},
		{"ten", Types.VARCHAR}, {"cssClass", Types.VARCHAR},
		{"kichthuoc", Types.VARCHAR}, {"ngaytao", Types.TIMESTAMP},
		{"daxoa", Types.INTEGER}, {"trangthai", Types.INTEGER},
		{"ngaysua", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoitao", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cssClass", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("kichthuoc", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ngaytao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("daxoa", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("trangthai", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ngaysua", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_quangcao_vitridanhmuc (id_ LONG not null primary key,companyId LONG,groupId LONG,nguoitao LONG,ten VARCHAR(75) null,cssClass VARCHAR(75) null,kichthuoc VARCHAR(75) null,ngaytao DATE null,daxoa INTEGER,trangthai INTEGER,ngaysua DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_quangcao_vitridanhmuc";

	public static final String ORDER_BY_JPQL = " ORDER BY viTriDanhMuc.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_quangcao_vitridanhmuc.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ViTriDanhMuc toModel(ViTriDanhMucSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ViTriDanhMuc model = new ViTriDanhMucImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setNguoitao(soapModel.getNguoitao());
		model.setTen(soapModel.getTen());
		model.setCssClass(soapModel.getCssClass());
		model.setKichthuoc(soapModel.getKichthuoc());
		model.setNgaytao(soapModel.getNgaytao());
		model.setDaxoa(soapModel.getDaxoa());
		model.setTrangthai(soapModel.getTrangthai());
		model.setNgaysua(soapModel.getNgaysua());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ViTriDanhMuc> toModels(ViTriDanhMucSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ViTriDanhMuc> models = new ArrayList<ViTriDanhMuc>(
			soapModels.length);

		for (ViTriDanhMucSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ViTriDanhMucModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ViTriDanhMuc.class;
	}

	@Override
	public String getModelClassName() {
		return ViTriDanhMuc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ViTriDanhMuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ViTriDanhMuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViTriDanhMuc, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ViTriDanhMuc)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ViTriDanhMuc, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ViTriDanhMuc, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ViTriDanhMuc)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ViTriDanhMuc, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ViTriDanhMuc, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ViTriDanhMuc, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ViTriDanhMuc, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ViTriDanhMuc, Object>>();

		attributeGetterFunctions.put("id", ViTriDanhMuc::getId);
		attributeGetterFunctions.put("companyId", ViTriDanhMuc::getCompanyId);
		attributeGetterFunctions.put("groupId", ViTriDanhMuc::getGroupId);
		attributeGetterFunctions.put("nguoitao", ViTriDanhMuc::getNguoitao);
		attributeGetterFunctions.put("ten", ViTriDanhMuc::getTen);
		attributeGetterFunctions.put("cssClass", ViTriDanhMuc::getCssClass);
		attributeGetterFunctions.put("kichthuoc", ViTriDanhMuc::getKichthuoc);
		attributeGetterFunctions.put("ngaytao", ViTriDanhMuc::getNgaytao);
		attributeGetterFunctions.put("daxoa", ViTriDanhMuc::getDaxoa);
		attributeGetterFunctions.put("trangthai", ViTriDanhMuc::getTrangthai);
		attributeGetterFunctions.put("ngaysua", ViTriDanhMuc::getNgaysua);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ViTriDanhMuc, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ViTriDanhMuc, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ViTriDanhMuc, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<ViTriDanhMuc, Long>)ViTriDanhMuc::setId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ViTriDanhMuc, Long>)ViTriDanhMuc::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ViTriDanhMuc, Long>)ViTriDanhMuc::setGroupId);
		attributeSetterBiConsumers.put(
			"nguoitao",
			(BiConsumer<ViTriDanhMuc, Long>)ViTriDanhMuc::setNguoitao);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<ViTriDanhMuc, String>)ViTriDanhMuc::setTen);
		attributeSetterBiConsumers.put(
			"cssClass",
			(BiConsumer<ViTriDanhMuc, String>)ViTriDanhMuc::setCssClass);
		attributeSetterBiConsumers.put(
			"kichthuoc",
			(BiConsumer<ViTriDanhMuc, String>)ViTriDanhMuc::setKichthuoc);
		attributeSetterBiConsumers.put(
			"ngaytao",
			(BiConsumer<ViTriDanhMuc, Date>)ViTriDanhMuc::setNgaytao);
		attributeSetterBiConsumers.put(
			"daxoa", (BiConsumer<ViTriDanhMuc, Integer>)ViTriDanhMuc::setDaxoa);
		attributeSetterBiConsumers.put(
			"trangthai",
			(BiConsumer<ViTriDanhMuc, Integer>)ViTriDanhMuc::setTrangthai);
		attributeSetterBiConsumers.put(
			"ngaysua",
			(BiConsumer<ViTriDanhMuc, Date>)ViTriDanhMuc::setNgaysua);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getNguoitao() {
		return _nguoitao;
	}

	@Override
	public void setNguoitao(long nguoitao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoitao = nguoitao;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@JSON
	@Override
	public String getCssClass() {
		if (_cssClass == null) {
			return "";
		}
		else {
			return _cssClass;
		}
	}

	@Override
	public void setCssClass(String cssClass) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cssClass = cssClass;
	}

	@JSON
	@Override
	public String getKichthuoc() {
		if (_kichthuoc == null) {
			return "";
		}
		else {
			return _kichthuoc;
		}
	}

	@Override
	public void setKichthuoc(String kichthuoc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_kichthuoc = kichthuoc;
	}

	@JSON
	@Override
	public Date getNgaytao() {
		return _ngaytao;
	}

	@Override
	public void setNgaytao(Date ngaytao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaytao = ngaytao;
	}

	@JSON
	@Override
	public int getDaxoa() {
		return _daxoa;
	}

	@Override
	public void setDaxoa(int daxoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_daxoa = daxoa;
	}

	@JSON
	@Override
	public int getTrangthai() {
		return _trangthai;
	}

	@Override
	public void setTrangthai(int trangthai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trangthai = trangthai;
	}

	@JSON
	@Override
	public Date getNgaysua() {
		return _ngaysua;
	}

	@Override
	public void setNgaysua(Date ngaysua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaysua = ngaysua;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ViTriDanhMuc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ViTriDanhMuc toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ViTriDanhMuc>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ViTriDanhMucImpl viTriDanhMucImpl = new ViTriDanhMucImpl();

		viTriDanhMucImpl.setId(getId());
		viTriDanhMucImpl.setCompanyId(getCompanyId());
		viTriDanhMucImpl.setGroupId(getGroupId());
		viTriDanhMucImpl.setNguoitao(getNguoitao());
		viTriDanhMucImpl.setTen(getTen());
		viTriDanhMucImpl.setCssClass(getCssClass());
		viTriDanhMucImpl.setKichthuoc(getKichthuoc());
		viTriDanhMucImpl.setNgaytao(getNgaytao());
		viTriDanhMucImpl.setDaxoa(getDaxoa());
		viTriDanhMucImpl.setTrangthai(getTrangthai());
		viTriDanhMucImpl.setNgaysua(getNgaysua());

		viTriDanhMucImpl.resetOriginalValues();

		return viTriDanhMucImpl;
	}

	@Override
	public int compareTo(ViTriDanhMuc viTriDanhMuc) {
		long primaryKey = viTriDanhMuc.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ViTriDanhMuc)) {
			return false;
		}

		ViTriDanhMuc viTriDanhMuc = (ViTriDanhMuc)object;

		long primaryKey = viTriDanhMuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ViTriDanhMuc> toCacheModel() {
		ViTriDanhMucCacheModel viTriDanhMucCacheModel =
			new ViTriDanhMucCacheModel();

		viTriDanhMucCacheModel.id = getId();

		viTriDanhMucCacheModel.companyId = getCompanyId();

		viTriDanhMucCacheModel.groupId = getGroupId();

		viTriDanhMucCacheModel.nguoitao = getNguoitao();

		viTriDanhMucCacheModel.ten = getTen();

		String ten = viTriDanhMucCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			viTriDanhMucCacheModel.ten = null;
		}

		viTriDanhMucCacheModel.cssClass = getCssClass();

		String cssClass = viTriDanhMucCacheModel.cssClass;

		if ((cssClass != null) && (cssClass.length() == 0)) {
			viTriDanhMucCacheModel.cssClass = null;
		}

		viTriDanhMucCacheModel.kichthuoc = getKichthuoc();

		String kichthuoc = viTriDanhMucCacheModel.kichthuoc;

		if ((kichthuoc != null) && (kichthuoc.length() == 0)) {
			viTriDanhMucCacheModel.kichthuoc = null;
		}

		Date ngaytao = getNgaytao();

		if (ngaytao != null) {
			viTriDanhMucCacheModel.ngaytao = ngaytao.getTime();
		}
		else {
			viTriDanhMucCacheModel.ngaytao = Long.MIN_VALUE;
		}

		viTriDanhMucCacheModel.daxoa = getDaxoa();

		viTriDanhMucCacheModel.trangthai = getTrangthai();

		Date ngaysua = getNgaysua();

		if (ngaysua != null) {
			viTriDanhMucCacheModel.ngaysua = ngaysua.getTime();
		}
		else {
			viTriDanhMucCacheModel.ngaysua = Long.MIN_VALUE;
		}

		return viTriDanhMucCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ViTriDanhMuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ViTriDanhMuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViTriDanhMuc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ViTriDanhMuc)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ViTriDanhMuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ViTriDanhMuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ViTriDanhMuc, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ViTriDanhMuc)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ViTriDanhMuc>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ViTriDanhMuc.class, ModelWrapper.class);

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private long _nguoitao;
	private String _ten;
	private String _cssClass;
	private String _kichthuoc;
	private Date _ngaytao;
	private int _daxoa;
	private int _trangthai;
	private Date _ngaysua;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ViTriDanhMuc, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ViTriDanhMuc)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("nguoitao", _nguoitao);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("cssClass", _cssClass);
		_columnOriginalValues.put("kichthuoc", _kichthuoc);
		_columnOriginalValues.put("ngaytao", _ngaytao);
		_columnOriginalValues.put("daxoa", _daxoa);
		_columnOriginalValues.put("trangthai", _trangthai);
		_columnOriginalValues.put("ngaysua", _ngaysua);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("nguoitao", 8L);

		columnBitmasks.put("ten", 16L);

		columnBitmasks.put("cssClass", 32L);

		columnBitmasks.put("kichthuoc", 64L);

		columnBitmasks.put("ngaytao", 128L);

		columnBitmasks.put("daxoa", 256L);

		columnBitmasks.put("trangthai", 512L);

		columnBitmasks.put("ngaysua", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ViTriDanhMuc _escapedModel;

}