/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CanBo service. Represents a row in the &quot;cms_lienhe_canbo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.contact.model.impl.CanBoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.contact.model.impl.CanBoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CanBo
 * @generated
 */
@ProviderType
public interface CanBoModel extends BaseModel<CanBo>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a can bo model instance should use the {@link CanBo} interface instead.
	 */

	/**
	 * Returns the primary key of this can bo.
	 *
	 * @return the primary key of this can bo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this can bo.
	 *
	 * @param primaryKey the primary key of this can bo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the canbo ID of this can bo.
	 *
	 * @return the canbo ID of this can bo
	 */
	public long getCanboId();

	/**
	 * Sets the canbo ID of this can bo.
	 *
	 * @param canboId the canbo ID of this can bo
	 */
	public void setCanboId(long canboId);

	/**
	 * Returns the company ID of this can bo.
	 *
	 * @return the company ID of this can bo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this can bo.
	 *
	 * @param companyId the company ID of this can bo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this can bo.
	 *
	 * @return the group ID of this can bo
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this can bo.
	 *
	 * @param groupId the group ID of this can bo
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the ten of this can bo.
	 *
	 * @return the ten of this can bo
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this can bo.
	 *
	 * @param ten the ten of this can bo
	 */
	public void setTen(String ten);

	/**
	 * Returns the chuc vu of this can bo.
	 *
	 * @return the chuc vu of this can bo
	 */
	@AutoEscape
	public String getChucVu();

	/**
	 * Sets the chuc vu of this can bo.
	 *
	 * @param chucVu the chuc vu of this can bo
	 */
	public void setChucVu(String chucVu);

	/**
	 * Returns the phongban_id of this can bo.
	 *
	 * @return the phongban_id of this can bo
	 */
	public long getPhongban_id();

	/**
	 * Sets the phongban_id of this can bo.
	 *
	 * @param phongban_id the phongban_id of this can bo
	 */
	public void setPhongban_id(long phongban_id);

	/**
	 * Returns the sdt of this can bo.
	 *
	 * @return the sdt of this can bo
	 */
	@AutoEscape
	public String getSdt();

	/**
	 * Sets the sdt of this can bo.
	 *
	 * @param sdt the sdt of this can bo
	 */
	public void setSdt(String sdt);

	/**
	 * Returns the email of this can bo.
	 *
	 * @return the email of this can bo
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this can bo.
	 *
	 * @param email the email of this can bo
	 */
	public void setEmail(String email);

	/**
	 * Returns the tinh trang of this can bo.
	 *
	 * @return the tinh trang of this can bo
	 */
	public long getTinhTrang();

	/**
	 * Sets the tinh trang of this can bo.
	 *
	 * @param tinhTrang the tinh trang of this can bo
	 */
	public void setTinhTrang(long tinhTrang);

	/**
	 * Returns the sap xep of this can bo.
	 *
	 * @return the sap xep of this can bo
	 */
	public int getSapXep();

	/**
	 * Sets the sap xep of this can bo.
	 *
	 * @param sapXep the sap xep of this can bo
	 */
	public void setSapXep(int sapXep);

	/**
	 * Returns the da xoa of this can bo.
	 *
	 * @return the da xoa of this can bo
	 */
	public long getDaXoa();

	/**
	 * Sets the da xoa of this can bo.
	 *
	 * @param daXoa the da xoa of this can bo
	 */
	public void setDaXoa(long daXoa);

	/**
	 * Returns the ngay tao of this can bo.
	 *
	 * @return the ngay tao of this can bo
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this can bo.
	 *
	 * @param ngayTao the ngay tao of this can bo
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this can bo.
	 *
	 * @return the ngay sua of this can bo
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this can bo.
	 *
	 * @param ngaySua the ngay sua of this can bo
	 */
	public void setNgaySua(Date ngaySua);

}