/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ToChuc service. Represents a row in the &quot;cms_lienhe_tochuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.contact.model.impl.ToChucModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.contact.model.impl.ToChucImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ToChuc
 * @generated
 */
@ProviderType
public interface ToChucModel extends BaseModel<ToChuc>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a to chuc model instance should use the {@link ToChuc} interface instead.
	 */

	/**
	 * Returns the primary key of this to chuc.
	 *
	 * @return the primary key of this to chuc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this to chuc.
	 *
	 * @param primaryKey the primary key of this to chuc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tochuc ID of this to chuc.
	 *
	 * @return the tochuc ID of this to chuc
	 */
	public long getTochucId();

	/**
	 * Sets the tochuc ID of this to chuc.
	 *
	 * @param tochucId the tochuc ID of this to chuc
	 */
	public void setTochucId(long tochucId);

	/**
	 * Returns the company ID of this to chuc.
	 *
	 * @return the company ID of this to chuc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this to chuc.
	 *
	 * @param companyId the company ID of this to chuc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this to chuc.
	 *
	 * @return the group ID of this to chuc
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this to chuc.
	 *
	 * @param groupId the group ID of this to chuc
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the ten of this to chuc.
	 *
	 * @return the ten of this to chuc
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this to chuc.
	 *
	 * @param ten the ten of this to chuc
	 */
	public void setTen(String ten);

	/**
	 * Returns the mo ta of this to chuc.
	 *
	 * @return the mo ta of this to chuc
	 */
	@AutoEscape
	public String getMoTa();

	/**
	 * Sets the mo ta of this to chuc.
	 *
	 * @param moTa the mo ta of this to chuc
	 */
	public void setMoTa(String moTa);

	/**
	 * Returns the tinh trang of this to chuc.
	 *
	 * @return the tinh trang of this to chuc
	 */
	public long getTinhTrang();

	/**
	 * Sets the tinh trang of this to chuc.
	 *
	 * @param tinhTrang the tinh trang of this to chuc
	 */
	public void setTinhTrang(long tinhTrang);

	/**
	 * Returns the sap xep of this to chuc.
	 *
	 * @return the sap xep of this to chuc
	 */
	public int getSapXep();

	/**
	 * Sets the sap xep of this to chuc.
	 *
	 * @param sapXep the sap xep of this to chuc
	 */
	public void setSapXep(int sapXep);

	/**
	 * Returns the da xoa of this to chuc.
	 *
	 * @return the da xoa of this to chuc
	 */
	public long getDaXoa();

	/**
	 * Sets the da xoa of this to chuc.
	 *
	 * @param daXoa the da xoa of this to chuc
	 */
	public void setDaXoa(long daXoa);

	/**
	 * Returns the ngay tao of this to chuc.
	 *
	 * @return the ngay tao of this to chuc
	 */
	public Date getNgayTao();

	/**
	 * Sets the ngay tao of this to chuc.
	 *
	 * @param ngayTao the ngay tao of this to chuc
	 */
	public void setNgayTao(Date ngayTao);

	/**
	 * Returns the ngay sua of this to chuc.
	 *
	 * @return the ngay sua of this to chuc
	 */
	public Date getNgaySua();

	/**
	 * Sets the ngay sua of this to chuc.
	 *
	 * @param ngaySua the ngay sua of this to chuc
	 */
	public void setNgaySua(Date ngaySua);

}