/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.vanbanphapquy.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Coquanbanhanh service. Represents a row in the &quot;cw_coquanbanhanh&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.dnict.vanbanphapquy.model.impl.CoquanbanhanhModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.dnict.vanbanphapquy.model.impl.CoquanbanhanhImpl</code>.
 * </p>
 *
 * @author BinhNT
 * @see Coquanbanhanh
 * @generated
 */
@ProviderType
public interface CoquanbanhanhModel
	extends BaseModel<Coquanbanhanh>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a coquanbanhanh model instance should use the {@link Coquanbanhanh} interface instead.
	 */

	/**
	 * Returns the primary key of this coquanbanhanh.
	 *
	 * @return the primary key of this coquanbanhanh
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this coquanbanhanh.
	 *
	 * @param primaryKey the primary key of this coquanbanhanh
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this coquanbanhanh.
	 *
	 * @return the ID of this coquanbanhanh
	 */
	public long getId();

	/**
	 * Sets the ID of this coquanbanhanh.
	 *
	 * @param id the ID of this coquanbanhanh
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this coquanbanhanh.
	 *
	 * @return the company ID of this coquanbanhanh
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this coquanbanhanh.
	 *
	 * @param companyId the company ID of this coquanbanhanh
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this coquanbanhanh.
	 *
	 * @return the group ID of this coquanbanhanh
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this coquanbanhanh.
	 *
	 * @param groupId the group ID of this coquanbanhanh
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the name of this coquanbanhanh.
	 *
	 * @return the name of this coquanbanhanh
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this coquanbanhanh.
	 *
	 * @param name the name of this coquanbanhanh
	 */
	public void setName(String name);

	/**
	 * Returns the code of this coquanbanhanh.
	 *
	 * @return the code of this coquanbanhanh
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this coquanbanhanh.
	 *
	 * @param code the code of this coquanbanhanh
	 */
	public void setCode(String code);

	/**
	 * Returns the status of this coquanbanhanh.
	 *
	 * @return the status of this coquanbanhanh
	 */
	public int getStatus();

	/**
	 * Sets the status of this coquanbanhanh.
	 *
	 * @param status the status of this coquanbanhanh
	 */
	public void setStatus(int status);

}