/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlgopy.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.qlgopy.model.emailTemplate;
import vn.dnict.qlgopy.service.emailTemplateService;
import vn.dnict.qlgopy.service.emailTemplateServiceUtil;
import vn.dnict.qlgopy.service.persistence.GopY_DinhKemPersistence;
import vn.dnict.qlgopy.service.persistence.HoiDapGopYPersistence;
import vn.dnict.qlgopy.service.persistence.emailTemplatePersistence;

/**
 * Provides the base implementation for the email template remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.qlgopy.service.impl.emailTemplateServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see vn.dnict.qlgopy.service.impl.emailTemplateServiceImpl
 * @generated
 */
public abstract class emailTemplateServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, emailTemplateService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>emailTemplateService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>emailTemplateServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		emailTemplateServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			emailTemplateService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		emailTemplateService = (emailTemplateService)aopProxy;

		emailTemplateServiceUtil.setService(emailTemplateService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return emailTemplateService.class.getName();
	}

	protected Class<?> getModelClass() {
		return emailTemplate.class;
	}

	protected String getModelClassName() {
		return emailTemplate.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = emailTemplatePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected vn.dnict.qlgopy.service.emailTemplateLocalService
		emailTemplateLocalService;

	protected emailTemplateService emailTemplateService;

	@Reference
	protected emailTemplatePersistence emailTemplatePersistence;

	@Reference
	protected GopY_DinhKemPersistence gopY_DinhKemPersistence;

	@Reference
	protected HoiDapGopYPersistence hoiDapGopYPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		emailTemplateServiceBaseImpl.class);

}