/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlquangcao.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.qlquangcao.model.BangQuangCao;
import vn.dnict.qlquangcao.service.BangQuangCaoService;
import vn.dnict.qlquangcao.service.BangQuangCaoServiceUtil;
import vn.dnict.qlquangcao.service.persistence.BangQuangCaoPersistence;
import vn.dnict.qlquangcao.service.persistence.NhomKHPersistence;
import vn.dnict.qlquangcao.service.persistence.ViTriDanhMucPersistence;

/**
 * Provides the base implementation for the bang quang cao remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.qlquangcao.service.impl.BangQuangCaoServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see vn.dnict.qlquangcao.service.impl.BangQuangCaoServiceImpl
 * @generated
 */
public abstract class BangQuangCaoServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, BangQuangCaoService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BangQuangCaoService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>BangQuangCaoServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		BangQuangCaoServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			BangQuangCaoService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		bangQuangCaoService = (BangQuangCaoService)aopProxy;

		BangQuangCaoServiceUtil.setService(bangQuangCaoService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BangQuangCaoService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BangQuangCao.class;
	}

	protected String getModelClassName() {
		return BangQuangCao.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = bangQuangCaoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected vn.dnict.qlquangcao.service.BangQuangCaoLocalService
		bangQuangCaoLocalService;

	protected BangQuangCaoService bangQuangCaoService;

	@Reference
	protected BangQuangCaoPersistence bangQuangCaoPersistence;

	@Reference
	protected NhomKHPersistence nhomKHPersistence;

	@Reference
	protected ViTriDanhMucPersistence viTriDanhMucPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		BangQuangCaoServiceBaseImpl.class);

}