/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model.impl;

import com.contact.model.CanBo;
import com.contact.model.CanBoModel;
import com.contact.model.CanBoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CanBo service. Represents a row in the &quot;cms_lienhe_canbo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CanBoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CanBoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CanBoImpl
 * @generated
 */
@JSON(strict = true)
public class CanBoModelImpl extends BaseModelImpl<CanBo> implements CanBoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a can bo model instance should use the <code>CanBo</code> interface instead.
	 */
	public static final String TABLE_NAME = "cms_lienhe_canbo";

	public static final Object[][] TABLE_COLUMNS = {
		{"canboId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"ten", Types.VARCHAR},
		{"chucVu", Types.VARCHAR}, {"phongban_id", Types.BIGINT},
		{"sdt", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"tinhTrang", Types.BIGINT}, {"sapXep", Types.INTEGER},
		{"daXoa", Types.BIGINT}, {"ngayTao", Types.TIMESTAMP},
		{"ngaySua", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("canboId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("chucVu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phongban_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sdt", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tinhTrang", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sapXep", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("daXoa", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayTao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngaySua", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cms_lienhe_canbo (canboId LONG not null primary key,companyId LONG,groupId LONG,ten VARCHAR(75) null,chucVu VARCHAR(75) null,phongban_id LONG,sdt VARCHAR(75) null,email VARCHAR(75) null,tinhTrang LONG,sapXep INTEGER,daXoa LONG,ngayTao DATE null,ngaySua DATE null)";

	public static final String TABLE_SQL_DROP = "drop table cms_lienhe_canbo";

	public static final String ORDER_BY_JPQL = " ORDER BY canBo.canboId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cms_lienhe_canbo.canboId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEN_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CANBOID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CanBo toModel(CanBoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CanBo model = new CanBoImpl();

		model.setCanboId(soapModel.getCanboId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setTen(soapModel.getTen());
		model.setChucVu(soapModel.getChucVu());
		model.setPhongban_id(soapModel.getPhongban_id());
		model.setSdt(soapModel.getSdt());
		model.setEmail(soapModel.getEmail());
		model.setTinhTrang(soapModel.getTinhTrang());
		model.setSapXep(soapModel.getSapXep());
		model.setDaXoa(soapModel.getDaXoa());
		model.setNgayTao(soapModel.getNgayTao());
		model.setNgaySua(soapModel.getNgaySua());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CanBo> toModels(CanBoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CanBo> models = new ArrayList<CanBo>(soapModels.length);

		for (CanBoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CanBoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _canboId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCanboId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _canboId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CanBo.class;
	}

	@Override
	public String getModelClassName() {
		return CanBo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CanBo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CanBo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CanBo, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CanBo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CanBo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CanBo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((CanBo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CanBo, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CanBo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CanBo, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<CanBo, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CanBo, Object>>();

		attributeGetterFunctions.put("canboId", CanBo::getCanboId);
		attributeGetterFunctions.put("companyId", CanBo::getCompanyId);
		attributeGetterFunctions.put("groupId", CanBo::getGroupId);
		attributeGetterFunctions.put("ten", CanBo::getTen);
		attributeGetterFunctions.put("chucVu", CanBo::getChucVu);
		attributeGetterFunctions.put("phongban_id", CanBo::getPhongban_id);
		attributeGetterFunctions.put("sdt", CanBo::getSdt);
		attributeGetterFunctions.put("email", CanBo::getEmail);
		attributeGetterFunctions.put("tinhTrang", CanBo::getTinhTrang);
		attributeGetterFunctions.put("sapXep", CanBo::getSapXep);
		attributeGetterFunctions.put("daXoa", CanBo::getDaXoa);
		attributeGetterFunctions.put("ngayTao", CanBo::getNgayTao);
		attributeGetterFunctions.put("ngaySua", CanBo::getNgaySua);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<CanBo, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<CanBo, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CanBo, ?>>();

		attributeSetterBiConsumers.put(
			"canboId", (BiConsumer<CanBo, Long>)CanBo::setCanboId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<CanBo, Long>)CanBo::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<CanBo, Long>)CanBo::setGroupId);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<CanBo, String>)CanBo::setTen);
		attributeSetterBiConsumers.put(
			"chucVu", (BiConsumer<CanBo, String>)CanBo::setChucVu);
		attributeSetterBiConsumers.put(
			"phongban_id", (BiConsumer<CanBo, Long>)CanBo::setPhongban_id);
		attributeSetterBiConsumers.put(
			"sdt", (BiConsumer<CanBo, String>)CanBo::setSdt);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<CanBo, String>)CanBo::setEmail);
		attributeSetterBiConsumers.put(
			"tinhTrang", (BiConsumer<CanBo, Long>)CanBo::setTinhTrang);
		attributeSetterBiConsumers.put(
			"sapXep", (BiConsumer<CanBo, Integer>)CanBo::setSapXep);
		attributeSetterBiConsumers.put(
			"daXoa", (BiConsumer<CanBo, Long>)CanBo::setDaXoa);
		attributeSetterBiConsumers.put(
			"ngayTao", (BiConsumer<CanBo, Date>)CanBo::setNgayTao);
		attributeSetterBiConsumers.put(
			"ngaySua", (BiConsumer<CanBo, Date>)CanBo::setNgaySua);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getCanboId() {
		return _canboId;
	}

	@Override
	public void setCanboId(long canboId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_canboId = canboId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTen() {
		return getColumnOriginalValue("ten");
	}

	@JSON
	@Override
	public String getChucVu() {
		if (_chucVu == null) {
			return "";
		}
		else {
			return _chucVu;
		}
	}

	@Override
	public void setChucVu(String chucVu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chucVu = chucVu;
	}

	@JSON
	@Override
	public long getPhongban_id() {
		return _phongban_id;
	}

	@Override
	public void setPhongban_id(long phongban_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phongban_id = phongban_id;
	}

	@JSON
	@Override
	public String getSdt() {
		if (_sdt == null) {
			return "";
		}
		else {
			return _sdt;
		}
	}

	@Override
	public void setSdt(String sdt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sdt = sdt;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public long getTinhTrang() {
		return _tinhTrang;
	}

	@Override
	public void setTinhTrang(long tinhTrang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tinhTrang = tinhTrang;
	}

	@JSON
	@Override
	public int getSapXep() {
		return _sapXep;
	}

	@Override
	public void setSapXep(int sapXep) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sapXep = sapXep;
	}

	@JSON
	@Override
	public long getDaXoa() {
		return _daXoa;
	}

	@Override
	public void setDaXoa(long daXoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_daXoa = daXoa;
	}

	@JSON
	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayTao = ngayTao;
	}

	@JSON
	@Override
	public Date getNgaySua() {
		return _ngaySua;
	}

	@Override
	public void setNgaySua(Date ngaySua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaySua = ngaySua;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CanBo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CanBo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CanBo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CanBoImpl canBoImpl = new CanBoImpl();

		canBoImpl.setCanboId(getCanboId());
		canBoImpl.setCompanyId(getCompanyId());
		canBoImpl.setGroupId(getGroupId());
		canBoImpl.setTen(getTen());
		canBoImpl.setChucVu(getChucVu());
		canBoImpl.setPhongban_id(getPhongban_id());
		canBoImpl.setSdt(getSdt());
		canBoImpl.setEmail(getEmail());
		canBoImpl.setTinhTrang(getTinhTrang());
		canBoImpl.setSapXep(getSapXep());
		canBoImpl.setDaXoa(getDaXoa());
		canBoImpl.setNgayTao(getNgayTao());
		canBoImpl.setNgaySua(getNgaySua());

		canBoImpl.resetOriginalValues();

		return canBoImpl;
	}

	@Override
	public int compareTo(CanBo canBo) {
		int value = 0;

		if (getCanboId() < canBo.getCanboId()) {
			value = -1;
		}
		else if (getCanboId() > canBo.getCanboId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CanBo)) {
			return false;
		}

		CanBo canBo = (CanBo)object;

		long primaryKey = canBo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CanBo> toCacheModel() {
		CanBoCacheModel canBoCacheModel = new CanBoCacheModel();

		canBoCacheModel.canboId = getCanboId();

		canBoCacheModel.companyId = getCompanyId();

		canBoCacheModel.groupId = getGroupId();

		canBoCacheModel.ten = getTen();

		String ten = canBoCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			canBoCacheModel.ten = null;
		}

		canBoCacheModel.chucVu = getChucVu();

		String chucVu = canBoCacheModel.chucVu;

		if ((chucVu != null) && (chucVu.length() == 0)) {
			canBoCacheModel.chucVu = null;
		}

		canBoCacheModel.phongban_id = getPhongban_id();

		canBoCacheModel.sdt = getSdt();

		String sdt = canBoCacheModel.sdt;

		if ((sdt != null) && (sdt.length() == 0)) {
			canBoCacheModel.sdt = null;
		}

		canBoCacheModel.email = getEmail();

		String email = canBoCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			canBoCacheModel.email = null;
		}

		canBoCacheModel.tinhTrang = getTinhTrang();

		canBoCacheModel.sapXep = getSapXep();

		canBoCacheModel.daXoa = getDaXoa();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			canBoCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			canBoCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			canBoCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			canBoCacheModel.ngaySua = Long.MIN_VALUE;
		}

		return canBoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CanBo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CanBo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CanBo, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CanBo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CanBo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CanBo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CanBo, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CanBo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CanBo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CanBo.class, ModelWrapper.class);

	}

	private long _canboId;
	private long _companyId;
	private long _groupId;
	private String _ten;
	private String _chucVu;
	private long _phongban_id;
	private String _sdt;
	private String _email;
	private long _tinhTrang;
	private int _sapXep;
	private long _daXoa;
	private Date _ngayTao;
	private Date _ngaySua;

	public <T> T getColumnValue(String columnName) {
		Function<CanBo, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CanBo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("canboId", _canboId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("chucVu", _chucVu);
		_columnOriginalValues.put("phongban_id", _phongban_id);
		_columnOriginalValues.put("sdt", _sdt);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("tinhTrang", _tinhTrang);
		_columnOriginalValues.put("sapXep", _sapXep);
		_columnOriginalValues.put("daXoa", _daXoa);
		_columnOriginalValues.put("ngayTao", _ngayTao);
		_columnOriginalValues.put("ngaySua", _ngaySua);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("canboId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("ten", 8L);

		columnBitmasks.put("chucVu", 16L);

		columnBitmasks.put("phongban_id", 32L);

		columnBitmasks.put("sdt", 64L);

		columnBitmasks.put("email", 128L);

		columnBitmasks.put("tinhTrang", 256L);

		columnBitmasks.put("sapXep", 512L);

		columnBitmasks.put("daXoa", 1024L);

		columnBitmasks.put("ngayTao", 2048L);

		columnBitmasks.put("ngaySua", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CanBo _escapedModel;

}