/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.contact.model.impl;

import com.contact.model.ToChuc;
import com.contact.model.ToChucModel;
import com.contact.model.ToChucSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ToChuc service. Represents a row in the &quot;cms_lienhe_tochuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ToChucModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ToChucImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ToChucImpl
 * @generated
 */
@JSON(strict = true)
public class ToChucModelImpl
	extends BaseModelImpl<ToChuc> implements ToChucModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a to chuc model instance should use the <code>ToChuc</code> interface instead.
	 */
	public static final String TABLE_NAME = "cms_lienhe_tochuc";

	public static final Object[][] TABLE_COLUMNS = {
		{"tochucId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"ten", Types.VARCHAR},
		{"moTa", Types.VARCHAR}, {"tinhTrang", Types.BIGINT},
		{"sapXep", Types.INTEGER}, {"daXoa", Types.BIGINT},
		{"ngayTao", Types.TIMESTAMP}, {"ngaySua", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("tochucId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("moTa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tinhTrang", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sapXep", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("daXoa", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayTao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngaySua", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cms_lienhe_tochuc (tochucId LONG not null primary key,companyId LONG,groupId LONG,ten VARCHAR(75) null,moTa VARCHAR(75) null,tinhTrang LONG,sapXep INTEGER,daXoa LONG,ngayTao DATE null,ngaySua DATE null)";

	public static final String TABLE_SQL_DROP = "drop table cms_lienhe_tochuc";

	public static final String ORDER_BY_JPQL = " ORDER BY toChuc.tochucId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cms_lienhe_tochuc.tochucId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEN_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOCHUCID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ToChuc toModel(ToChucSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ToChuc model = new ToChucImpl();

		model.setTochucId(soapModel.getTochucId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setTen(soapModel.getTen());
		model.setMoTa(soapModel.getMoTa());
		model.setTinhTrang(soapModel.getTinhTrang());
		model.setSapXep(soapModel.getSapXep());
		model.setDaXoa(soapModel.getDaXoa());
		model.setNgayTao(soapModel.getNgayTao());
		model.setNgaySua(soapModel.getNgaySua());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ToChuc> toModels(ToChucSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ToChuc> models = new ArrayList<ToChuc>(soapModels.length);

		for (ToChucSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ToChucModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tochucId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTochucId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tochucId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ToChuc.class;
	}

	@Override
	public String getModelClassName() {
		return ToChuc.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ToChuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ToChuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ToChuc, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ToChuc)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ToChuc, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ToChuc, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ToChuc)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ToChuc, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ToChuc, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ToChuc, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ToChuc, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ToChuc, Object>>();

		attributeGetterFunctions.put("tochucId", ToChuc::getTochucId);
		attributeGetterFunctions.put("companyId", ToChuc::getCompanyId);
		attributeGetterFunctions.put("groupId", ToChuc::getGroupId);
		attributeGetterFunctions.put("ten", ToChuc::getTen);
		attributeGetterFunctions.put("moTa", ToChuc::getMoTa);
		attributeGetterFunctions.put("tinhTrang", ToChuc::getTinhTrang);
		attributeGetterFunctions.put("sapXep", ToChuc::getSapXep);
		attributeGetterFunctions.put("daXoa", ToChuc::getDaXoa);
		attributeGetterFunctions.put("ngayTao", ToChuc::getNgayTao);
		attributeGetterFunctions.put("ngaySua", ToChuc::getNgaySua);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ToChuc, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ToChuc, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ToChuc, ?>>();

		attributeSetterBiConsumers.put(
			"tochucId", (BiConsumer<ToChuc, Long>)ToChuc::setTochucId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<ToChuc, Long>)ToChuc::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<ToChuc, Long>)ToChuc::setGroupId);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<ToChuc, String>)ToChuc::setTen);
		attributeSetterBiConsumers.put(
			"moTa", (BiConsumer<ToChuc, String>)ToChuc::setMoTa);
		attributeSetterBiConsumers.put(
			"tinhTrang", (BiConsumer<ToChuc, Long>)ToChuc::setTinhTrang);
		attributeSetterBiConsumers.put(
			"sapXep", (BiConsumer<ToChuc, Integer>)ToChuc::setSapXep);
		attributeSetterBiConsumers.put(
			"daXoa", (BiConsumer<ToChuc, Long>)ToChuc::setDaXoa);
		attributeSetterBiConsumers.put(
			"ngayTao", (BiConsumer<ToChuc, Date>)ToChuc::setNgayTao);
		attributeSetterBiConsumers.put(
			"ngaySua", (BiConsumer<ToChuc, Date>)ToChuc::setNgaySua);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTochucId() {
		return _tochucId;
	}

	@Override
	public void setTochucId(long tochucId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tochucId = tochucId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTen() {
		return getColumnOriginalValue("ten");
	}

	@JSON
	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return "";
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_moTa = moTa;
	}

	@JSON
	@Override
	public long getTinhTrang() {
		return _tinhTrang;
	}

	@Override
	public void setTinhTrang(long tinhTrang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tinhTrang = tinhTrang;
	}

	@JSON
	@Override
	public int getSapXep() {
		return _sapXep;
	}

	@Override
	public void setSapXep(int sapXep) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sapXep = sapXep;
	}

	@JSON
	@Override
	public long getDaXoa() {
		return _daXoa;
	}

	@Override
	public void setDaXoa(long daXoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_daXoa = daXoa;
	}

	@JSON
	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayTao = ngayTao;
	}

	@JSON
	@Override
	public Date getNgaySua() {
		return _ngaySua;
	}

	@Override
	public void setNgaySua(Date ngaySua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaySua = ngaySua;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ToChuc.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ToChuc toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ToChuc>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ToChucImpl toChucImpl = new ToChucImpl();

		toChucImpl.setTochucId(getTochucId());
		toChucImpl.setCompanyId(getCompanyId());
		toChucImpl.setGroupId(getGroupId());
		toChucImpl.setTen(getTen());
		toChucImpl.setMoTa(getMoTa());
		toChucImpl.setTinhTrang(getTinhTrang());
		toChucImpl.setSapXep(getSapXep());
		toChucImpl.setDaXoa(getDaXoa());
		toChucImpl.setNgayTao(getNgayTao());
		toChucImpl.setNgaySua(getNgaySua());

		toChucImpl.resetOriginalValues();

		return toChucImpl;
	}

	@Override
	public int compareTo(ToChuc toChuc) {
		int value = 0;

		if (getTochucId() < toChuc.getTochucId()) {
			value = -1;
		}
		else if (getTochucId() > toChuc.getTochucId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ToChuc)) {
			return false;
		}

		ToChuc toChuc = (ToChuc)object;

		long primaryKey = toChuc.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ToChuc> toCacheModel() {
		ToChucCacheModel toChucCacheModel = new ToChucCacheModel();

		toChucCacheModel.tochucId = getTochucId();

		toChucCacheModel.companyId = getCompanyId();

		toChucCacheModel.groupId = getGroupId();

		toChucCacheModel.ten = getTen();

		String ten = toChucCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			toChucCacheModel.ten = null;
		}

		toChucCacheModel.moTa = getMoTa();

		String moTa = toChucCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			toChucCacheModel.moTa = null;
		}

		toChucCacheModel.tinhTrang = getTinhTrang();

		toChucCacheModel.sapXep = getSapXep();

		toChucCacheModel.daXoa = getDaXoa();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			toChucCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			toChucCacheModel.ngayTao = Long.MIN_VALUE;
		}

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			toChucCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			toChucCacheModel.ngaySua = Long.MIN_VALUE;
		}

		return toChucCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ToChuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ToChuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ToChuc, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ToChuc)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ToChuc, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ToChuc, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ToChuc, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ToChuc)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ToChuc>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ToChuc.class, ModelWrapper.class);

	}

	private long _tochucId;
	private long _companyId;
	private long _groupId;
	private String _ten;
	private String _moTa;
	private long _tinhTrang;
	private int _sapXep;
	private long _daXoa;
	private Date _ngayTao;
	private Date _ngaySua;

	public <T> T getColumnValue(String columnName) {
		Function<ToChuc, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ToChuc)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("tochucId", _tochucId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("moTa", _moTa);
		_columnOriginalValues.put("tinhTrang", _tinhTrang);
		_columnOriginalValues.put("sapXep", _sapXep);
		_columnOriginalValues.put("daXoa", _daXoa);
		_columnOriginalValues.put("ngayTao", _ngayTao);
		_columnOriginalValues.put("ngaySua", _ngaySua);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("tochucId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("ten", 8L);

		columnBitmasks.put("moTa", 16L);

		columnBitmasks.put("tinhTrang", 32L);

		columnBitmasks.put("sapXep", 64L);

		columnBitmasks.put("daXoa", 128L);

		columnBitmasks.put("ngayTao", 256L);

		columnBitmasks.put("ngaySua", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ToChuc _escapedModel;

}