/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.tintuc.model.News_Categories;
import vn.dnict.tintuc.model.News_CategoriesModel;

/**
 * The base model implementation for the News_Categories service. Represents a row in the &quot;cw_News_Categories&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>News_CategoriesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link News_CategoriesImpl}.
 * </p>
 *
 * @author dnict
 * @see News_CategoriesImpl
 * @generated
 */
public class News_CategoriesModelImpl
	extends BaseModelImpl<News_Categories> implements News_CategoriesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news_ categories model instance should use the <code>News_Categories</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_News_Categories";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"name", Types.VARCHAR},
		{"language", Types.VARCHAR}, {"status", Types.INTEGER},
		{"orders", Types.INTEGER}, {"idlibcat", Types.BIGINT},
		{"delete_status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("orders", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("idlibcat", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_News_Categories (id_ LONG not null primary key,companyId LONG,groupId LONG,name STRING null,language VARCHAR(75) null,status INTEGER,orders INTEGER,idlibcat LONG,delete_status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table cw_News_Categories";

	public static final String ORDER_BY_JPQL =
		" ORDER BY news_Categories.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_News_Categories.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public News_CategoriesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return News_Categories.class;
	}

	@Override
	public String getModelClassName() {
		return News_Categories.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<News_Categories, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<News_Categories, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Categories, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((News_Categories)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<News_Categories, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<News_Categories, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(News_Categories)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<News_Categories, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<News_Categories, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, News_Categories>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			News_Categories.class.getClassLoader(), News_Categories.class,
			ModelWrapper.class);

		try {
			Constructor<News_Categories> constructor =
				(Constructor<News_Categories>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<News_Categories, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<News_Categories, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<News_Categories, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<News_Categories, Object>>();
		Map<String, BiConsumer<News_Categories, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<News_Categories, ?>>();

		attributeGetterFunctions.put("id", News_Categories::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<News_Categories, Long>)News_Categories::setId);
		attributeGetterFunctions.put(
			"companyId", News_Categories::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<News_Categories, Long>)News_Categories::setCompanyId);
		attributeGetterFunctions.put("groupId", News_Categories::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<News_Categories, Long>)News_Categories::setGroupId);
		attributeGetterFunctions.put("name", News_Categories::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<News_Categories, String>)News_Categories::setName);
		attributeGetterFunctions.put("language", News_Categories::getLanguage);
		attributeSetterBiConsumers.put(
			"language",
			(BiConsumer<News_Categories, String>)News_Categories::setLanguage);
		attributeGetterFunctions.put("status", News_Categories::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<News_Categories, Integer>)News_Categories::setStatus);
		attributeGetterFunctions.put("orders", News_Categories::getOrders);
		attributeSetterBiConsumers.put(
			"orders",
			(BiConsumer<News_Categories, Integer>)News_Categories::setOrders);
		attributeGetterFunctions.put("idlibcat", News_Categories::getIdlibcat);
		attributeSetterBiConsumers.put(
			"idlibcat",
			(BiConsumer<News_Categories, Long>)News_Categories::setIdlibcat);
		attributeGetterFunctions.put(
			"delete_status", News_Categories::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<News_Categories, Integer>)
				News_Categories::setDelete_status);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return "";
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_language = language;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public int getOrders() {
		return _orders;
	}

	@Override
	public void setOrders(int orders) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orders = orders;
	}

	@Override
	public long getIdlibcat() {
		return _idlibcat;
	}

	@Override
	public void setIdlibcat(long idlibcat) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idlibcat = idlibcat;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), News_Categories.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public News_Categories toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, News_Categories>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		News_CategoriesImpl news_CategoriesImpl = new News_CategoriesImpl();

		news_CategoriesImpl.setId(getId());
		news_CategoriesImpl.setCompanyId(getCompanyId());
		news_CategoriesImpl.setGroupId(getGroupId());
		news_CategoriesImpl.setName(getName());
		news_CategoriesImpl.setLanguage(getLanguage());
		news_CategoriesImpl.setStatus(getStatus());
		news_CategoriesImpl.setOrders(getOrders());
		news_CategoriesImpl.setIdlibcat(getIdlibcat());
		news_CategoriesImpl.setDelete_status(getDelete_status());

		news_CategoriesImpl.resetOriginalValues();

		return news_CategoriesImpl;
	}

	@Override
	public int compareTo(News_Categories news_Categories) {
		int value = 0;

		if (getId() < news_Categories.getId()) {
			value = -1;
		}
		else if (getId() > news_Categories.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof News_Categories)) {
			return false;
		}

		News_Categories news_Categories = (News_Categories)object;

		long primaryKey = news_Categories.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<News_Categories> toCacheModel() {
		News_CategoriesCacheModel news_CategoriesCacheModel =
			new News_CategoriesCacheModel();

		news_CategoriesCacheModel.id = getId();

		news_CategoriesCacheModel.companyId = getCompanyId();

		news_CategoriesCacheModel.groupId = getGroupId();

		news_CategoriesCacheModel.name = getName();

		String name = news_CategoriesCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			news_CategoriesCacheModel.name = null;
		}

		news_CategoriesCacheModel.language = getLanguage();

		String language = news_CategoriesCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			news_CategoriesCacheModel.language = null;
		}

		news_CategoriesCacheModel.status = getStatus();

		news_CategoriesCacheModel.orders = getOrders();

		news_CategoriesCacheModel.idlibcat = getIdlibcat();

		news_CategoriesCacheModel.delete_status = getDelete_status();

		return news_CategoriesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<News_Categories, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<News_Categories, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Categories, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((News_Categories)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<News_Categories, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<News_Categories, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Categories, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((News_Categories)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, News_Categories>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private String _name;
	private String _language;
	private int _status;
	private int _orders;
	private long _idlibcat;
	private int _delete_status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<News_Categories, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((News_Categories)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("language", _language);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("orders", _orders);
		_columnOriginalValues.put("idlibcat", _idlibcat);
		_columnOriginalValues.put("delete_status", _delete_status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("name", 8L);

		columnBitmasks.put("language", 16L);

		columnBitmasks.put("status", 32L);

		columnBitmasks.put("orders", 64L);

		columnBitmasks.put("idlibcat", 128L);

		columnBitmasks.put("delete_status", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private News_Categories _escapedModel;

}