/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlnhuanbut.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlnhuanbut.model.HeSoLoaiAP;
import vn.dnict.qlnhuanbut.model.HeSoLoaiAPModel;
import vn.dnict.qlnhuanbut.model.HeSoLoaiAPSoap;

/**
 * The base model implementation for the HeSoLoaiAP service. Represents a row in the &quot;cw_nhuanbut_hesoloaiAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HeSoLoaiAPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HeSoLoaiAPImpl}.
 * </p>
 *
 * @author dnict
 * @see HeSoLoaiAPImpl
 * @generated
 */
@JSON(strict = true)
public class HeSoLoaiAPModelImpl
	extends BaseModelImpl<HeSoLoaiAP> implements HeSoLoaiAPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a he so loai ap model instance should use the <code>HeSoLoaiAP</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_nhuanbut_hesoloaiAP";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"loaiId", Types.BIGINT},
		{"minheso", Types.VARCHAR}, {"maxheso", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("loaiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("minheso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("maxheso", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_nhuanbut_hesoloaiAP (id_ LONG not null primary key,loaiId LONG,minheso VARCHAR(75) null,maxheso VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_nhuanbut_hesoloaiAP";

	public static final String ORDER_BY_JPQL = " ORDER BY heSoLoaiAP.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_nhuanbut_hesoloaiAP.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static HeSoLoaiAP toModel(HeSoLoaiAPSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		HeSoLoaiAP model = new HeSoLoaiAPImpl();

		model.setId(soapModel.getId());
		model.setLoaiId(soapModel.getLoaiId());
		model.setMinheso(soapModel.getMinheso());
		model.setMaxheso(soapModel.getMaxheso());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<HeSoLoaiAP> toModels(HeSoLoaiAPSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<HeSoLoaiAP> models = new ArrayList<HeSoLoaiAP>(soapModels.length);

		for (HeSoLoaiAPSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public HeSoLoaiAPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HeSoLoaiAP.class;
	}

	@Override
	public String getModelClassName() {
		return HeSoLoaiAP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HeSoLoaiAP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HeSoLoaiAP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HeSoLoaiAP, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((HeSoLoaiAP)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HeSoLoaiAP, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HeSoLoaiAP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(HeSoLoaiAP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HeSoLoaiAP, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HeSoLoaiAP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<HeSoLoaiAP, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<HeSoLoaiAP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<HeSoLoaiAP, Object>>();

		attributeGetterFunctions.put("id", HeSoLoaiAP::getId);
		attributeGetterFunctions.put("loaiId", HeSoLoaiAP::getLoaiId);
		attributeGetterFunctions.put("minheso", HeSoLoaiAP::getMinheso);
		attributeGetterFunctions.put("maxheso", HeSoLoaiAP::getMaxheso);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<HeSoLoaiAP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<HeSoLoaiAP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<HeSoLoaiAP, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<HeSoLoaiAP, Long>)HeSoLoaiAP::setId);
		attributeSetterBiConsumers.put(
			"loaiId", (BiConsumer<HeSoLoaiAP, Long>)HeSoLoaiAP::setLoaiId);
		attributeSetterBiConsumers.put(
			"minheso", (BiConsumer<HeSoLoaiAP, String>)HeSoLoaiAP::setMinheso);
		attributeSetterBiConsumers.put(
			"maxheso", (BiConsumer<HeSoLoaiAP, String>)HeSoLoaiAP::setMaxheso);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getLoaiId() {
		return _loaiId;
	}

	@Override
	public void setLoaiId(long loaiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loaiId = loaiId;
	}

	@JSON
	@Override
	public String getMinheso() {
		if (_minheso == null) {
			return "";
		}
		else {
			return _minheso;
		}
	}

	@Override
	public void setMinheso(String minheso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_minheso = minheso;
	}

	@JSON
	@Override
	public String getMaxheso() {
		if (_maxheso == null) {
			return "";
		}
		else {
			return _maxheso;
		}
	}

	@Override
	public void setMaxheso(String maxheso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_maxheso = maxheso;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, HeSoLoaiAP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HeSoLoaiAP toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HeSoLoaiAP>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HeSoLoaiAPImpl heSoLoaiAPImpl = new HeSoLoaiAPImpl();

		heSoLoaiAPImpl.setId(getId());
		heSoLoaiAPImpl.setLoaiId(getLoaiId());
		heSoLoaiAPImpl.setMinheso(getMinheso());
		heSoLoaiAPImpl.setMaxheso(getMaxheso());

		heSoLoaiAPImpl.resetOriginalValues();

		return heSoLoaiAPImpl;
	}

	@Override
	public int compareTo(HeSoLoaiAP heSoLoaiAP) {
		long primaryKey = heSoLoaiAP.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof HeSoLoaiAP)) {
			return false;
		}

		HeSoLoaiAP heSoLoaiAP = (HeSoLoaiAP)object;

		long primaryKey = heSoLoaiAP.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<HeSoLoaiAP> toCacheModel() {
		HeSoLoaiAPCacheModel heSoLoaiAPCacheModel = new HeSoLoaiAPCacheModel();

		heSoLoaiAPCacheModel.id = getId();

		heSoLoaiAPCacheModel.loaiId = getLoaiId();

		heSoLoaiAPCacheModel.minheso = getMinheso();

		String minheso = heSoLoaiAPCacheModel.minheso;

		if ((minheso != null) && (minheso.length() == 0)) {
			heSoLoaiAPCacheModel.minheso = null;
		}

		heSoLoaiAPCacheModel.maxheso = getMaxheso();

		String maxheso = heSoLoaiAPCacheModel.maxheso;

		if ((maxheso != null) && (maxheso.length() == 0)) {
			heSoLoaiAPCacheModel.maxheso = null;
		}

		return heSoLoaiAPCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HeSoLoaiAP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HeSoLoaiAP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HeSoLoaiAP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((HeSoLoaiAP)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<HeSoLoaiAP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<HeSoLoaiAP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HeSoLoaiAP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((HeSoLoaiAP)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, HeSoLoaiAP>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					HeSoLoaiAP.class, ModelWrapper.class);

	}

	private long _id;
	private long _loaiId;
	private String _minheso;
	private String _maxheso;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<HeSoLoaiAP, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((HeSoLoaiAP)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("loaiId", _loaiId);
		_columnOriginalValues.put("minheso", _minheso);
		_columnOriginalValues.put("maxheso", _maxheso);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("loaiId", 2L);

		columnBitmasks.put("minheso", 4L);

		columnBitmasks.put("maxheso", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private HeSoLoaiAP _escapedModel;

}