/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlnhuanbut.model.impl;

import vn.dnict.qlnhuanbut.model.HeSoLoaiAP;
import vn.dnict.qlnhuanbut.service.HeSoLoaiAPLocalServiceUtil;

/**
 * The extended model base implementation for the HeSoLoaiAP service. Represents a row in the &quot;cw_nhuanbut_hesoloaiAP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HeSoLoaiAPImpl}.
 * </p>
 *
 * @author dnict
 * @see HeSoLoaiAPImpl
 * @see HeSoLoaiAP
 * @generated
 */
public abstract class HeSoLoaiAPBaseImpl
	extends HeSoLoaiAPModelImpl implements HeSoLoaiAP {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a he so loai ap model instance should use the <code>HeSoLoaiAP</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			HeSoLoaiAPLocalServiceUtil.addHeSoLoaiAP(this);
		}
		else {
			HeSoLoaiAPLocalServiceUtil.updateHeSoLoaiAP(this);
		}
	}

}