/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlnhuanbut.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlnhuanbut.model.ThongKeNB;
import vn.dnict.qlnhuanbut.model.ThongKeNBModel;
import vn.dnict.qlnhuanbut.model.ThongKeNBSoap;

/**
 * The base model implementation for the ThongKeNB service. Represents a row in the &quot;cw_nhuanbut_thongke&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ThongKeNBModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ThongKeNBImpl}.
 * </p>
 *
 * @author dnict
 * @see ThongKeNBImpl
 * @generated
 */
@JSON(strict = true)
public class ThongKeNBModelImpl
	extends BaseModelImpl<ThongKeNB> implements ThongKeNBModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a thong ke nb model instance should use the <code>ThongKeNB</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_nhuanbut_thongke";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"nguoixuly", Types.BIGINT},
		{"newarticleId", Types.BIGINT}, {"anphamId", Types.BIGINT},
		{"heso", Types.VARCHAR}, {"tongtien", Types.DOUBLE},
		{"status", Types.INTEGER}, {"ngaytao", Types.TIMESTAMP},
		{"ngaysua", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoixuly", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("newarticleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("anphamId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("heso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tongtien", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ngaytao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngaysua", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_nhuanbut_thongke (id_ LONG not null primary key,nguoixuly LONG,newarticleId LONG,anphamId LONG,heso VARCHAR(75) null,tongtien DOUBLE,status INTEGER,ngaytao DATE null,ngaysua DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_nhuanbut_thongke";

	public static final String ORDER_BY_JPQL = " ORDER BY thongKeNB.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_nhuanbut_thongke.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ThongKeNB toModel(ThongKeNBSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ThongKeNB model = new ThongKeNBImpl();

		model.setId(soapModel.getId());
		model.setNguoixuly(soapModel.getNguoixuly());
		model.setNewarticleId(soapModel.getNewarticleId());
		model.setAnphamId(soapModel.getAnphamId());
		model.setHeso(soapModel.getHeso());
		model.setTongtien(soapModel.getTongtien());
		model.setStatus(soapModel.getStatus());
		model.setNgaytao(soapModel.getNgaytao());
		model.setNgaysua(soapModel.getNgaysua());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ThongKeNB> toModels(ThongKeNBSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ThongKeNB> models = new ArrayList<ThongKeNB>(soapModels.length);

		for (ThongKeNBSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ThongKeNBModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ThongKeNB.class;
	}

	@Override
	public String getModelClassName() {
		return ThongKeNB.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ThongKeNB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ThongKeNB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKeNB, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ThongKeNB)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ThongKeNB, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ThongKeNB, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ThongKeNB)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ThongKeNB, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ThongKeNB, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ThongKeNB, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ThongKeNB, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ThongKeNB, Object>>();

		attributeGetterFunctions.put("id", ThongKeNB::getId);
		attributeGetterFunctions.put("nguoixuly", ThongKeNB::getNguoixuly);
		attributeGetterFunctions.put(
			"newarticleId", ThongKeNB::getNewarticleId);
		attributeGetterFunctions.put("anphamId", ThongKeNB::getAnphamId);
		attributeGetterFunctions.put("heso", ThongKeNB::getHeso);
		attributeGetterFunctions.put("tongtien", ThongKeNB::getTongtien);
		attributeGetterFunctions.put("status", ThongKeNB::getStatus);
		attributeGetterFunctions.put("ngaytao", ThongKeNB::getNgaytao);
		attributeGetterFunctions.put("ngaysua", ThongKeNB::getNgaysua);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ThongKeNB, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ThongKeNB, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ThongKeNB, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<ThongKeNB, Long>)ThongKeNB::setId);
		attributeSetterBiConsumers.put(
			"nguoixuly", (BiConsumer<ThongKeNB, Long>)ThongKeNB::setNguoixuly);
		attributeSetterBiConsumers.put(
			"newarticleId",
			(BiConsumer<ThongKeNB, Long>)ThongKeNB::setNewarticleId);
		attributeSetterBiConsumers.put(
			"anphamId", (BiConsumer<ThongKeNB, Long>)ThongKeNB::setAnphamId);
		attributeSetterBiConsumers.put(
			"heso", (BiConsumer<ThongKeNB, String>)ThongKeNB::setHeso);
		attributeSetterBiConsumers.put(
			"tongtien", (BiConsumer<ThongKeNB, Double>)ThongKeNB::setTongtien);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<ThongKeNB, Integer>)ThongKeNB::setStatus);
		attributeSetterBiConsumers.put(
			"ngaytao", (BiConsumer<ThongKeNB, Date>)ThongKeNB::setNgaytao);
		attributeSetterBiConsumers.put(
			"ngaysua", (BiConsumer<ThongKeNB, Date>)ThongKeNB::setNgaysua);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getNguoixuly() {
		return _nguoixuly;
	}

	@Override
	public void setNguoixuly(long nguoixuly) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoixuly = nguoixuly;
	}

	@JSON
	@Override
	public long getNewarticleId() {
		return _newarticleId;
	}

	@Override
	public void setNewarticleId(long newarticleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_newarticleId = newarticleId;
	}

	@JSON
	@Override
	public long getAnphamId() {
		return _anphamId;
	}

	@Override
	public void setAnphamId(long anphamId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anphamId = anphamId;
	}

	@JSON
	@Override
	public String getHeso() {
		if (_heso == null) {
			return "";
		}
		else {
			return _heso;
		}
	}

	@Override
	public void setHeso(String heso) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_heso = heso;
	}

	@JSON
	@Override
	public double getTongtien() {
		return _tongtien;
	}

	@Override
	public void setTongtien(double tongtien) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tongtien = tongtien;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Date getNgaytao() {
		return _ngaytao;
	}

	@Override
	public void setNgaytao(Date ngaytao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaytao = ngaytao;
	}

	@JSON
	@Override
	public Date getNgaysua() {
		return _ngaysua;
	}

	@Override
	public void setNgaysua(Date ngaysua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaysua = ngaysua;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ThongKeNB.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ThongKeNB toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ThongKeNB>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ThongKeNBImpl thongKeNBImpl = new ThongKeNBImpl();

		thongKeNBImpl.setId(getId());
		thongKeNBImpl.setNguoixuly(getNguoixuly());
		thongKeNBImpl.setNewarticleId(getNewarticleId());
		thongKeNBImpl.setAnphamId(getAnphamId());
		thongKeNBImpl.setHeso(getHeso());
		thongKeNBImpl.setTongtien(getTongtien());
		thongKeNBImpl.setStatus(getStatus());
		thongKeNBImpl.setNgaytao(getNgaytao());
		thongKeNBImpl.setNgaysua(getNgaysua());

		thongKeNBImpl.resetOriginalValues();

		return thongKeNBImpl;
	}

	@Override
	public int compareTo(ThongKeNB thongKeNB) {
		long primaryKey = thongKeNB.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ThongKeNB)) {
			return false;
		}

		ThongKeNB thongKeNB = (ThongKeNB)object;

		long primaryKey = thongKeNB.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ThongKeNB> toCacheModel() {
		ThongKeNBCacheModel thongKeNBCacheModel = new ThongKeNBCacheModel();

		thongKeNBCacheModel.id = getId();

		thongKeNBCacheModel.nguoixuly = getNguoixuly();

		thongKeNBCacheModel.newarticleId = getNewarticleId();

		thongKeNBCacheModel.anphamId = getAnphamId();

		thongKeNBCacheModel.heso = getHeso();

		String heso = thongKeNBCacheModel.heso;

		if ((heso != null) && (heso.length() == 0)) {
			thongKeNBCacheModel.heso = null;
		}

		thongKeNBCacheModel.tongtien = getTongtien();

		thongKeNBCacheModel.status = getStatus();

		Date ngaytao = getNgaytao();

		if (ngaytao != null) {
			thongKeNBCacheModel.ngaytao = ngaytao.getTime();
		}
		else {
			thongKeNBCacheModel.ngaytao = Long.MIN_VALUE;
		}

		Date ngaysua = getNgaysua();

		if (ngaysua != null) {
			thongKeNBCacheModel.ngaysua = ngaysua.getTime();
		}
		else {
			thongKeNBCacheModel.ngaysua = Long.MIN_VALUE;
		}

		return thongKeNBCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ThongKeNB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ThongKeNB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKeNB, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ThongKeNB)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ThongKeNB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ThongKeNB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ThongKeNB, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ThongKeNB)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ThongKeNB>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ThongKeNB.class, ModelWrapper.class);

	}

	private long _id;
	private long _nguoixuly;
	private long _newarticleId;
	private long _anphamId;
	private String _heso;
	private double _tongtien;
	private int _status;
	private Date _ngaytao;
	private Date _ngaysua;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ThongKeNB, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ThongKeNB)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("nguoixuly", _nguoixuly);
		_columnOriginalValues.put("newarticleId", _newarticleId);
		_columnOriginalValues.put("anphamId", _anphamId);
		_columnOriginalValues.put("heso", _heso);
		_columnOriginalValues.put("tongtien", _tongtien);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("ngaytao", _ngaytao);
		_columnOriginalValues.put("ngaysua", _ngaysua);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("nguoixuly", 2L);

		columnBitmasks.put("newarticleId", 4L);

		columnBitmasks.put("anphamId", 8L);

		columnBitmasks.put("heso", 16L);

		columnBitmasks.put("tongtien", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("ngaytao", 128L);

		columnBitmasks.put("ngaysua", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ThongKeNB _escapedModel;

}