/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import qlanphamdb.model.AnPham_Logs;

import qlanphamdb.service.AnPham_LogsLocalService;
import qlanphamdb.service.AnPham_LogsLocalServiceUtil;
import qlanphamdb.service.persistence.AnPham_ActivityPersistence;
import qlanphamdb.service.persistence.AnPham_BinhLuanPersistence;
import qlanphamdb.service.persistence.AnPham_CongTacVienPersistence;
import qlanphamdb.service.persistence.AnPham_DeCuongPersistence;
import qlanphamdb.service.persistence.AnPham_DinhKemFilePersistence;
import qlanphamdb.service.persistence.AnPham_LoaiPersistence;
import qlanphamdb.service.persistence.AnPham_LogsPersistence;
import qlanphamdb.service.persistence.AnPham_PhanCongPersistence;
import qlanphamdb.service.persistence.AnPham_TapChiPersistence;
import qlanphamdb.service.persistence.eMagazinePersistence;
import qlanphamdb.service.persistence.eMagazine_BinhLuanPersistence;
import qlanphamdb.service.persistence.eMagazine_LogsPersistence;
import qlanphamdb.service.persistence.eMagazine_templatePersistence;

/**
 * Provides the base implementation for the an pham_ logs local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link qlanphamdb.service.impl.AnPham_LogsLocalServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see qlanphamdb.service.impl.AnPham_LogsLocalServiceImpl
 * @generated
 */
public abstract class AnPham_LogsLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AnPham_LogsLocalService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AnPham_LogsLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AnPham_LogsLocalServiceUtil</code>.
	 */

	/**
	 * Adds the an pham_ logs to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnPham_LogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param anPham_Logs the an pham_ logs
	 * @return the an pham_ logs that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnPham_Logs addAnPham_Logs(AnPham_Logs anPham_Logs) {
		anPham_Logs.setNew(true);

		return anPham_LogsPersistence.update(anPham_Logs);
	}

	/**
	 * Creates a new an pham_ logs with the primary key. Does not add the an pham_ logs to the database.
	 *
	 * @param id the primary key for the new an pham_ logs
	 * @return the new an pham_ logs
	 */
	@Override
	@Transactional(enabled = false)
	public AnPham_Logs createAnPham_Logs(long id) {
		return anPham_LogsPersistence.create(id);
	}

	/**
	 * Deletes the an pham_ logs with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnPham_LogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the an pham_ logs
	 * @return the an pham_ logs that was removed
	 * @throws PortalException if a an pham_ logs with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnPham_Logs deleteAnPham_Logs(long id) throws PortalException {
		return anPham_LogsPersistence.remove(id);
	}

	/**
	 * Deletes the an pham_ logs from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnPham_LogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param anPham_Logs the an pham_ logs
	 * @return the an pham_ logs that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnPham_Logs deleteAnPham_Logs(AnPham_Logs anPham_Logs) {
		return anPham_LogsPersistence.remove(anPham_Logs);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AnPham_Logs.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return anPham_LogsPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.AnPham_LogsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return anPham_LogsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.AnPham_LogsModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return anPham_LogsPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return anPham_LogsPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return anPham_LogsPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AnPham_Logs fetchAnPham_Logs(long id) {
		return anPham_LogsPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the an pham_ logs with the primary key.
	 *
	 * @param id the primary key of the an pham_ logs
	 * @return the an pham_ logs
	 * @throws PortalException if a an pham_ logs with the primary key could not be found
	 */
	@Override
	public AnPham_Logs getAnPham_Logs(long id) throws PortalException {
		return anPham_LogsPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(anPham_LogsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnPham_Logs.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			anPham_LogsLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AnPham_Logs.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(anPham_LogsLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnPham_Logs.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return anPham_LogsPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return anPham_LogsLocalService.deleteAnPham_Logs(
			(AnPham_Logs)persistedModel);
	}

	public BasePersistence<AnPham_Logs> getBasePersistence() {
		return anPham_LogsPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return anPham_LogsPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the an pham_ logses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.AnPham_LogsModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of an pham_ logses
	 * @param end the upper bound of the range of an pham_ logses (not inclusive)
	 * @return the range of an pham_ logses
	 */
	@Override
	public List<AnPham_Logs> getAnPham_Logses(int start, int end) {
		return anPham_LogsPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of an pham_ logses.
	 *
	 * @return the number of an pham_ logses
	 */
	@Override
	public int getAnPham_LogsesCount() {
		return anPham_LogsPersistence.countAll();
	}

	/**
	 * Updates the an pham_ logs in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnPham_LogsLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param anPham_Logs the an pham_ logs
	 * @return the an pham_ logs that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnPham_Logs updateAnPham_Logs(AnPham_Logs anPham_Logs) {
		return anPham_LogsPersistence.update(anPham_Logs);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AnPham_LogsLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		anPham_LogsLocalService = (AnPham_LogsLocalService)aopProxy;

		_setLocalServiceUtilService(anPham_LogsLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AnPham_LogsLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AnPham_Logs.class;
	}

	protected String getModelClassName() {
		return AnPham_Logs.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = anPham_LogsPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AnPham_LogsLocalService anPham_LogsLocalService) {

		try {
			Field field = AnPham_LogsLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, anPham_LogsLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AnPham_ActivityPersistence anPham_ActivityPersistence;

	@Reference
	protected AnPham_BinhLuanPersistence anPham_BinhLuanPersistence;

	@Reference
	protected AnPham_CongTacVienPersistence anPham_CongTacVienPersistence;

	@Reference
	protected AnPham_DeCuongPersistence anPham_DeCuongPersistence;

	@Reference
	protected AnPham_DinhKemFilePersistence anPham_DinhKemFilePersistence;

	@Reference
	protected AnPham_LoaiPersistence anPham_LoaiPersistence;

	protected AnPham_LogsLocalService anPham_LogsLocalService;

	@Reference
	protected AnPham_LogsPersistence anPham_LogsPersistence;

	@Reference
	protected AnPham_PhanCongPersistence anPham_PhanCongPersistence;

	@Reference
	protected AnPham_TapChiPersistence anPham_TapChiPersistence;

	@Reference
	protected eMagazinePersistence eMagazinePersistence;

	@Reference
	protected eMagazine_BinhLuanPersistence eMagazine_BinhLuanPersistence;

	@Reference
	protected eMagazine_LogsPersistence eMagazine_LogsPersistence;

	@Reference
	protected eMagazine_templatePersistence eMagazine_templatePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}