/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import qlanphamdb.model.eMagazine;

import qlanphamdb.service.eMagazineLocalService;
import qlanphamdb.service.eMagazineLocalServiceUtil;
import qlanphamdb.service.persistence.AnPham_ActivityPersistence;
import qlanphamdb.service.persistence.AnPham_CongTacVienPersistence;
import qlanphamdb.service.persistence.AnPham_DeCuongPersistence;
import qlanphamdb.service.persistence.AnPham_DinhKemFilePersistence;
import qlanphamdb.service.persistence.AnPham_LoaiPersistence;
import qlanphamdb.service.persistence.AnPham_LogsPersistence;
import qlanphamdb.service.persistence.AnPham_PhanCongPersistence;
import qlanphamdb.service.persistence.AnPham_TapChiPersistence;
import qlanphamdb.service.persistence.eMagazinePersistence;
import qlanphamdb.service.persistence.eMagazine_LogsPersistence;
import qlanphamdb.service.persistence.eMagazine_templatePersistence;

/**
 * Provides the base implementation for the e magazine local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link qlanphamdb.service.impl.eMagazineLocalServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see qlanphamdb.service.impl.eMagazineLocalServiceImpl
 * @generated
 */
public abstract class eMagazineLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, eMagazineLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>eMagazineLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>eMagazineLocalServiceUtil</code>.
	 */

	/**
	 * Adds the e magazine to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect eMagazineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eMagazine the e magazine
	 * @return the e magazine that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public eMagazine addeMagazine(eMagazine eMagazine) {
		eMagazine.setNew(true);

		return eMagazinePersistence.update(eMagazine);
	}

	/**
	 * Creates a new e magazine with the primary key. Does not add the e magazine to the database.
	 *
	 * @param id the primary key for the new e magazine
	 * @return the new e magazine
	 */
	@Override
	@Transactional(enabled = false)
	public eMagazine createeMagazine(long id) {
		return eMagazinePersistence.create(id);
	}

	/**
	 * Deletes the e magazine with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect eMagazineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the e magazine
	 * @return the e magazine that was removed
	 * @throws PortalException if a e magazine with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public eMagazine deleteeMagazine(long id) throws PortalException {
		return eMagazinePersistence.remove(id);
	}

	/**
	 * Deletes the e magazine from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect eMagazineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eMagazine the e magazine
	 * @return the e magazine that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public eMagazine deleteeMagazine(eMagazine eMagazine) {
		return eMagazinePersistence.remove(eMagazine);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			eMagazine.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return eMagazinePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.eMagazineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return eMagazinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.eMagazineModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return eMagazinePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return eMagazinePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return eMagazinePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public eMagazine fetcheMagazine(long id) {
		return eMagazinePersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the e magazine with the primary key.
	 *
	 * @param id the primary key of the e magazine
	 * @return the e magazine
	 * @throws PortalException if a e magazine with the primary key could not be found
	 */
	@Override
	public eMagazine geteMagazine(long id) throws PortalException {
		return eMagazinePersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(eMagazineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(eMagazine.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			eMagazineLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(eMagazine.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(eMagazineLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(eMagazine.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eMagazinePersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return eMagazineLocalService.deleteeMagazine((eMagazine)persistedModel);
	}

	public BasePersistence<eMagazine> getBasePersistence() {
		return eMagazinePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eMagazinePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the e magazines.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>qlanphamdb.model.impl.eMagazineModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of e magazines
	 * @param end the upper bound of the range of e magazines (not inclusive)
	 * @return the range of e magazines
	 */
	@Override
	public List<eMagazine> geteMagazines(int start, int end) {
		return eMagazinePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of e magazines.
	 *
	 * @return the number of e magazines
	 */
	@Override
	public int geteMagazinesCount() {
		return eMagazinePersistence.countAll();
	}

	/**
	 * Updates the e magazine in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect eMagazineLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eMagazine the e magazine
	 * @return the e magazine that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public eMagazine updateeMagazine(eMagazine eMagazine) {
		return eMagazinePersistence.update(eMagazine);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			eMagazineLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		eMagazineLocalService = (eMagazineLocalService)aopProxy;

		_setLocalServiceUtilService(eMagazineLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return eMagazineLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return eMagazine.class;
	}

	protected String getModelClassName() {
		return eMagazine.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = eMagazinePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		eMagazineLocalService eMagazineLocalService) {

		try {
			Field field = eMagazineLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, eMagazineLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AnPham_ActivityPersistence anPham_ActivityPersistence;

	@Reference
	protected AnPham_CongTacVienPersistence anPham_CongTacVienPersistence;

	@Reference
	protected AnPham_DeCuongPersistence anPham_DeCuongPersistence;

	@Reference
	protected AnPham_DinhKemFilePersistence anPham_DinhKemFilePersistence;

	@Reference
	protected AnPham_LoaiPersistence anPham_LoaiPersistence;

	@Reference
	protected AnPham_LogsPersistence anPham_LogsPersistence;

	@Reference
	protected AnPham_PhanCongPersistence anPham_PhanCongPersistence;

	@Reference
	protected AnPham_TapChiPersistence anPham_TapChiPersistence;

	protected eMagazineLocalService eMagazineLocalService;

	@Reference
	protected eMagazinePersistence eMagazinePersistence;

	@Reference
	protected eMagazine_LogsPersistence eMagazine_LogsPersistence;

	@Reference
	protected eMagazine_templatePersistence eMagazine_templatePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}