/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package cms.quanlyvideo.model.impl;

import cms.quanlyvideo.model.ChuDeVideo;
import cms.quanlyvideo.model.ChuDeVideoModel;
import cms.quanlyvideo.model.ChuDeVideoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ChuDeVideo service. Represents a row in the &quot;cms_quanlyvideo_chudevideo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ChuDeVideoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChuDeVideoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChuDeVideoImpl
 * @generated
 */
@JSON(strict = true)
public class ChuDeVideoModelImpl
	extends BaseModelImpl<ChuDeVideo> implements ChuDeVideoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chu de video model instance should use the <code>ChuDeVideo</code> interface instead.
	 */
	public static final String TABLE_NAME = "cms_quanlyvideo_chudevideo";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"chude_id", Types.BIGINT},
		{"video_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("chude_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("video_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cms_quanlyvideo_chudevideo (id_ LONG not null primary key,chude_id LONG,video_id LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table cms_quanlyvideo_chudevideo";

	public static final String ORDER_BY_JPQL = " ORDER BY chuDeVideo.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cms_quanlyvideo_chudevideo.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHUDE_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VIDEO_ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static ChuDeVideo toModel(ChuDeVideoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ChuDeVideo model = new ChuDeVideoImpl();

		model.setId(soapModel.getId());
		model.setChude_id(soapModel.getChude_id());
		model.setVideo_id(soapModel.getVideo_id());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<ChuDeVideo> toModels(ChuDeVideoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ChuDeVideo> models = new ArrayList<ChuDeVideo>(soapModels.length);

		for (ChuDeVideoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ChuDeVideoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChuDeVideo.class;
	}

	@Override
	public String getModelClassName() {
		return ChuDeVideo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChuDeVideo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChuDeVideo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChuDeVideo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ChuDeVideo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChuDeVideo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChuDeVideo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChuDeVideo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChuDeVideo, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChuDeVideo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ChuDeVideo, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<ChuDeVideo, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ChuDeVideo, Object>>();

		attributeGetterFunctions.put("id", ChuDeVideo::getId);
		attributeGetterFunctions.put("chude_id", ChuDeVideo::getChude_id);
		attributeGetterFunctions.put("video_id", ChuDeVideo::getVideo_id);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<ChuDeVideo, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<ChuDeVideo, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChuDeVideo, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<ChuDeVideo, Long>)ChuDeVideo::setId);
		attributeSetterBiConsumers.put(
			"chude_id", (BiConsumer<ChuDeVideo, Long>)ChuDeVideo::setChude_id);
		attributeSetterBiConsumers.put(
			"video_id", (BiConsumer<ChuDeVideo, Long>)ChuDeVideo::setVideo_id);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getChude_id() {
		return _chude_id;
	}

	@Override
	public void setChude_id(long chude_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chude_id = chude_id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalChude_id() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("chude_id"));
	}

	@JSON
	@Override
	public long getVideo_id() {
		return _video_id;
	}

	@Override
	public void setVideo_id(long video_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_video_id = video_id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalVideo_id() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("video_id"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ChuDeVideo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChuDeVideo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChuDeVideo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChuDeVideoImpl chuDeVideoImpl = new ChuDeVideoImpl();

		chuDeVideoImpl.setId(getId());
		chuDeVideoImpl.setChude_id(getChude_id());
		chuDeVideoImpl.setVideo_id(getVideo_id());

		chuDeVideoImpl.resetOriginalValues();

		return chuDeVideoImpl;
	}

	@Override
	public int compareTo(ChuDeVideo chuDeVideo) {
		int value = 0;

		if (getId() < chuDeVideo.getId()) {
			value = -1;
		}
		else if (getId() > chuDeVideo.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ChuDeVideo)) {
			return false;
		}

		ChuDeVideo chuDeVideo = (ChuDeVideo)object;

		long primaryKey = chuDeVideo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ChuDeVideo> toCacheModel() {
		ChuDeVideoCacheModel chuDeVideoCacheModel = new ChuDeVideoCacheModel();

		chuDeVideoCacheModel.id = getId();

		chuDeVideoCacheModel.chude_id = getChude_id();

		chuDeVideoCacheModel.video_id = getVideo_id();

		return chuDeVideoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChuDeVideo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChuDeVideo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChuDeVideo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((ChuDeVideo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ChuDeVideo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ChuDeVideo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChuDeVideo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ChuDeVideo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChuDeVideo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ChuDeVideo.class, ModelWrapper.class);

	}

	private long _id;
	private long _chude_id;
	private long _video_id;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ChuDeVideo, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ChuDeVideo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("chude_id", _chude_id);
		_columnOriginalValues.put("video_id", _video_id);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("chude_id", 2L);

		columnBitmasks.put("video_id", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ChuDeVideo _escapedModel;

}