/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package cms.quanlyvideo.model.impl;

import cms.quanlyvideo.model.ChuDeVideo;
import cms.quanlyvideo.service.ChuDeVideoLocalServiceUtil;

/**
 * The extended model base implementation for the ChuDeVideo service. Represents a row in the &quot;cms_quanlyvideo_chudevideo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChuDeVideoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChuDeVideoImpl
 * @see ChuDeVideo
 * @generated
 */
public abstract class ChuDeVideoBaseImpl
	extends ChuDeVideoModelImpl implements ChuDeVideo {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chu de video model instance should use the <code>ChuDeVideo</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ChuDeVideoLocalServiceUtil.addChuDeVideo(this);
		}
		else {
			ChuDeVideoLocalServiceUtil.updateChuDeVideo(this);
		}
	}

}