/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package cms.quanlyvideo.model.impl;

import cms.quanlyvideo.model.Video;
import cms.quanlyvideo.service.VideoLocalServiceUtil;

/**
 * The extended model base implementation for the Video service. Represents a row in the &quot;cms_quanlyvideo_video&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VideoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VideoImpl
 * @see Video
 * @generated
 */
public abstract class VideoBaseImpl extends VideoModelImpl implements Video {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a video model instance should use the <code>Video</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			VideoLocalServiceUtil.addVideo(this);
		}
		else {
			VideoLocalServiceUtil.updateVideo(this);
		}
	}

}