/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the News_Type service. Represents a row in the &quot;cw_News_Type&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.dnict.tintuc.model.impl.News_TypeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.dnict.tintuc.model.impl.News_TypeImpl</code>.
 * </p>
 *
 * @author dnict
 * @see News_Type
 * @generated
 */
@ProviderType
public interface News_TypeModel extends BaseModel<News_Type>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news_ type model instance should use the {@link News_Type} interface instead.
	 */

	/**
	 * Returns the primary key of this news_ type.
	 *
	 * @return the primary key of this news_ type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news_ type.
	 *
	 * @param primaryKey the primary key of this news_ type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this news_ type.
	 *
	 * @return the ID of this news_ type
	 */
	public long getId();

	/**
	 * Sets the ID of this news_ type.
	 *
	 * @param id the ID of this news_ type
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this news_ type.
	 *
	 * @return the company ID of this news_ type
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this news_ type.
	 *
	 * @param companyId the company ID of this news_ type
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this news_ type.
	 *
	 * @return the group ID of this news_ type
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this news_ type.
	 *
	 * @param groupId the group ID of this news_ type
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the name of this news_ type.
	 *
	 * @return the name of this news_ type
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this news_ type.
	 *
	 * @param name the name of this news_ type
	 */
	public void setName(String name);

	/**
	 * Returns the language of this news_ type.
	 *
	 * @return the language of this news_ type
	 */
	@AutoEscape
	public String getLanguage();

	/**
	 * Sets the language of this news_ type.
	 *
	 * @param language the language of this news_ type
	 */
	public void setLanguage(String language);

	/**
	 * Returns the status of this news_ type.
	 *
	 * @return the status of this news_ type
	 */
	public int getStatus();

	/**
	 * Sets the status of this news_ type.
	 *
	 * @param status the status of this news_ type
	 */
	public void setStatus(int status);

	/**
	 * Returns the orders of this news_ type.
	 *
	 * @return the orders of this news_ type
	 */
	public int getOrders();

	/**
	 * Sets the orders of this news_ type.
	 *
	 * @param orders the orders of this news_ type
	 */
	public void setOrders(int orders);

	/**
	 * Returns the delete_status of this news_ type.
	 *
	 * @return the delete_status of this news_ type
	 */
	public int getDelete_status();

	/**
	 * Sets the delete_status of this news_ type.
	 *
	 * @param delete_status the delete_status of this news_ type
	 */
	public void setDelete_status(int delete_status);

}