/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.tintuc.model.News_Activity;
import vn.dnict.tintuc.model.News_ActivityModel;

/**
 * The base model implementation for the News_Activity service. Represents a row in the &quot;cw_News_Activity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>News_ActivityModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link News_ActivityImpl}.
 * </p>
 *
 * @author dnict
 * @see News_ActivityImpl
 * @generated
 */
public class News_ActivityModelImpl
	extends BaseModelImpl<News_Activity> implements News_ActivityModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news_ activity model instance should use the <code>News_Activity</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_News_Activity";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"id_", Types.BIGINT}, {"articleid", Types.BIGINT},
		{"startuserid", Types.BIGINT}, {"enduserid", Types.BIGINT},
		{"contentrequest", Types.CLOB}, {"statusofarticle", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("articleid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startuserid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("enduserid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contentrequest", Types.CLOB);
		TABLE_COLUMNS_MAP.put("statusofarticle", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_News_Activity (companyId LONG,groupId LONG,id_ LONG not null primary key,articleid LONG,startuserid LONG,enduserid LONG,contentrequest TEXT null,statusofarticle INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table cw_News_Activity";

	public static final String ORDER_BY_JPQL = " ORDER BY news_Activity.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_News_Activity.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public News_ActivityModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return News_Activity.class;
	}

	@Override
	public String getModelClassName() {
		return News_Activity.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<News_Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<News_Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Activity, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((News_Activity)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<News_Activity, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<News_Activity, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(News_Activity)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<News_Activity, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<News_Activity, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, News_Activity>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			News_Activity.class.getClassLoader(), News_Activity.class,
			ModelWrapper.class);

		try {
			Constructor<News_Activity> constructor =
				(Constructor<News_Activity>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<News_Activity, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<News_Activity, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<News_Activity, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<News_Activity, Object>>();
		Map<String, BiConsumer<News_Activity, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<News_Activity, ?>>();

		attributeGetterFunctions.put("companyId", News_Activity::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<News_Activity, Long>)News_Activity::setCompanyId);
		attributeGetterFunctions.put("groupId", News_Activity::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<News_Activity, Long>)News_Activity::setGroupId);
		attributeGetterFunctions.put("id", News_Activity::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<News_Activity, Long>)News_Activity::setId);
		attributeGetterFunctions.put("articleid", News_Activity::getArticleid);
		attributeSetterBiConsumers.put(
			"articleid",
			(BiConsumer<News_Activity, Long>)News_Activity::setArticleid);
		attributeGetterFunctions.put(
			"startuserid", News_Activity::getStartuserid);
		attributeSetterBiConsumers.put(
			"startuserid",
			(BiConsumer<News_Activity, Long>)News_Activity::setStartuserid);
		attributeGetterFunctions.put("enduserid", News_Activity::getEnduserid);
		attributeSetterBiConsumers.put(
			"enduserid",
			(BiConsumer<News_Activity, Long>)News_Activity::setEnduserid);
		attributeGetterFunctions.put(
			"contentrequest", News_Activity::getContentrequest);
		attributeSetterBiConsumers.put(
			"contentrequest",
			(BiConsumer<News_Activity, String>)
				News_Activity::setContentrequest);
		attributeGetterFunctions.put(
			"statusofarticle", News_Activity::getStatusofarticle);
		attributeSetterBiConsumers.put(
			"statusofarticle",
			(BiConsumer<News_Activity, Integer>)
				News_Activity::setStatusofarticle);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getArticleid() {
		return _articleid;
	}

	@Override
	public void setArticleid(long articleid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_articleid = articleid;
	}

	@Override
	public long getStartuserid() {
		return _startuserid;
	}

	@Override
	public void setStartuserid(long startuserid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startuserid = startuserid;
	}

	@Override
	public long getEnduserid() {
		return _enduserid;
	}

	@Override
	public void setEnduserid(long enduserid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enduserid = enduserid;
	}

	@Override
	public String getContentrequest() {
		if (_contentrequest == null) {
			return "";
		}
		else {
			return _contentrequest;
		}
	}

	@Override
	public void setContentrequest(String contentrequest) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contentrequest = contentrequest;
	}

	@Override
	public int getStatusofarticle() {
		return _statusofarticle;
	}

	@Override
	public void setStatusofarticle(int statusofarticle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusofarticle = statusofarticle;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), News_Activity.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public News_Activity toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, News_Activity>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		News_ActivityImpl news_ActivityImpl = new News_ActivityImpl();

		news_ActivityImpl.setCompanyId(getCompanyId());
		news_ActivityImpl.setGroupId(getGroupId());
		news_ActivityImpl.setId(getId());
		news_ActivityImpl.setArticleid(getArticleid());
		news_ActivityImpl.setStartuserid(getStartuserid());
		news_ActivityImpl.setEnduserid(getEnduserid());
		news_ActivityImpl.setContentrequest(getContentrequest());
		news_ActivityImpl.setStatusofarticle(getStatusofarticle());

		news_ActivityImpl.resetOriginalValues();

		return news_ActivityImpl;
	}

	@Override
	public int compareTo(News_Activity news_Activity) {
		long primaryKey = news_Activity.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof News_Activity)) {
			return false;
		}

		News_Activity news_Activity = (News_Activity)object;

		long primaryKey = news_Activity.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<News_Activity> toCacheModel() {
		News_ActivityCacheModel news_ActivityCacheModel =
			new News_ActivityCacheModel();

		news_ActivityCacheModel.companyId = getCompanyId();

		news_ActivityCacheModel.groupId = getGroupId();

		news_ActivityCacheModel.id = getId();

		news_ActivityCacheModel.articleid = getArticleid();

		news_ActivityCacheModel.startuserid = getStartuserid();

		news_ActivityCacheModel.enduserid = getEnduserid();

		news_ActivityCacheModel.contentrequest = getContentrequest();

		String contentrequest = news_ActivityCacheModel.contentrequest;

		if ((contentrequest != null) && (contentrequest.length() == 0)) {
			news_ActivityCacheModel.contentrequest = null;
		}

		news_ActivityCacheModel.statusofarticle = getStatusofarticle();

		return news_ActivityCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<News_Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<News_Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Activity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((News_Activity)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<News_Activity, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<News_Activity, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_Activity, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((News_Activity)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, News_Activity>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _companyId;
	private long _groupId;
	private long _id;
	private long _articleid;
	private long _startuserid;
	private long _enduserid;
	private String _contentrequest;
	private int _statusofarticle;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<News_Activity, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((News_Activity)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("articleid", _articleid);
		_columnOriginalValues.put("startuserid", _startuserid);
		_columnOriginalValues.put("enduserid", _enduserid);
		_columnOriginalValues.put("contentrequest", _contentrequest);
		_columnOriginalValues.put("statusofarticle", _statusofarticle);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("companyId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("id_", 4L);

		columnBitmasks.put("articleid", 8L);

		columnBitmasks.put("startuserid", 16L);

		columnBitmasks.put("enduserid", 32L);

		columnBitmasks.put("contentrequest", 64L);

		columnBitmasks.put("statusofarticle", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private News_Activity _escapedModel;

}