/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlgopy.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GopY_DinhKem service. Represents a row in the &quot;cw_gopy_dinhkemfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.dnict.qlgopy.model.impl.GopY_DinhKemModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.dnict.qlgopy.model.impl.GopY_DinhKemImpl</code>.
 * </p>
 *
 * @author dnict
 * @see GopY_DinhKem
 * @generated
 */
@ProviderType
public interface GopY_DinhKemModel
	extends BaseModel<GopY_DinhKem>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gop y_ dinh kem model instance should use the {@link GopY_DinhKem} interface instead.
	 */

	/**
	 * Returns the primary key of this gop y_ dinh kem.
	 *
	 * @return the primary key of this gop y_ dinh kem
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gop y_ dinh kem.
	 *
	 * @param primaryKey the primary key of this gop y_ dinh kem
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this gop y_ dinh kem.
	 *
	 * @return the ID of this gop y_ dinh kem
	 */
	public long getId();

	/**
	 * Sets the ID of this gop y_ dinh kem.
	 *
	 * @param id the ID of this gop y_ dinh kem
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this gop y_ dinh kem.
	 *
	 * @return the company ID of this gop y_ dinh kem
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this gop y_ dinh kem.
	 *
	 * @param companyId the company ID of this gop y_ dinh kem
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this gop y_ dinh kem.
	 *
	 * @return the group ID of this gop y_ dinh kem
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this gop y_ dinh kem.
	 *
	 * @param groupId the group ID of this gop y_ dinh kem
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this gop y_ dinh kem.
	 *
	 * @return the user ID of this gop y_ dinh kem
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this gop y_ dinh kem.
	 *
	 * @param userId the user ID of this gop y_ dinh kem
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this gop y_ dinh kem.
	 *
	 * @return the user uuid of this gop y_ dinh kem
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this gop y_ dinh kem.
	 *
	 * @param userUuid the user uuid of this gop y_ dinh kem
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ten of this gop y_ dinh kem.
	 *
	 * @return the ten of this gop y_ dinh kem
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this gop y_ dinh kem.
	 *
	 * @param ten the ten of this gop y_ dinh kem
	 */
	public void setTen(String ten);

	/**
	 * Returns the url of this gop y_ dinh kem.
	 *
	 * @return the url of this gop y_ dinh kem
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this gop y_ dinh kem.
	 *
	 * @param url the url of this gop y_ dinh kem
	 */
	public void setUrl(String url);

	/**
	 * Returns the object of this gop y_ dinh kem.
	 *
	 * @return the object of this gop y_ dinh kem
	 */
	public long getObject();

	/**
	 * Sets the object of this gop y_ dinh kem.
	 *
	 * @param Object the object of this gop y_ dinh kem
	 */
	public void setObject(long Object);

	/**
	 * Returns the object ID of this gop y_ dinh kem.
	 *
	 * @return the object ID of this gop y_ dinh kem
	 */
	public long getObjectId();

	/**
	 * Sets the object ID of this gop y_ dinh kem.
	 *
	 * @param ObjectId the object ID of this gop y_ dinh kem
	 */
	public void setObjectId(long ObjectId);

	/**
	 * Returns the ghichu of this gop y_ dinh kem.
	 *
	 * @return the ghichu of this gop y_ dinh kem
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this gop y_ dinh kem.
	 *
	 * @param ghichu the ghichu of this gop y_ dinh kem
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the daxoa of this gop y_ dinh kem.
	 *
	 * @return the daxoa of this gop y_ dinh kem
	 */
	public int getDaxoa();

	/**
	 * Sets the daxoa of this gop y_ dinh kem.
	 *
	 * @param daxoa the daxoa of this gop y_ dinh kem
	 */
	public void setDaxoa(int daxoa);

	/**
	 * Returns the status of this gop y_ dinh kem.
	 *
	 * @return the status of this gop y_ dinh kem
	 */
	public int getStatus();

	/**
	 * Sets the status of this gop y_ dinh kem.
	 *
	 * @param status the status of this gop y_ dinh kem
	 */
	public void setStatus(int status);

}