/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlnhuanbut.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import vn.dnict.qlnhuanbut.model.HeSoLoaiAP;
import vn.dnict.qlnhuanbut.service.HeSoLoaiAPService;
import vn.dnict.qlnhuanbut.service.HeSoLoaiAPServiceUtil;
import vn.dnict.qlnhuanbut.service.persistence.DinhMucPersistence;
import vn.dnict.qlnhuanbut.service.persistence.HeSoLoaiAPPersistence;
import vn.dnict.qlnhuanbut.service.persistence.HeSoTheLoaiPersistence;
import vn.dnict.qlnhuanbut.service.persistence.ThongKeNBPersistence;

/**
 * Provides the base implementation for the he so loai ap remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.dnict.qlnhuanbut.service.impl.HeSoLoaiAPServiceImpl}.
 * </p>
 *
 * @author dnict
 * @see vn.dnict.qlnhuanbut.service.impl.HeSoLoaiAPServiceImpl
 * @generated
 */
public abstract class HeSoLoaiAPServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, HeSoLoaiAPService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>HeSoLoaiAPService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>HeSoLoaiAPServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		HeSoLoaiAPServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			HeSoLoaiAPService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		heSoLoaiAPService = (HeSoLoaiAPService)aopProxy;

		HeSoLoaiAPServiceUtil.setService(heSoLoaiAPService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HeSoLoaiAPService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HeSoLoaiAP.class;
	}

	protected String getModelClassName() {
		return HeSoLoaiAP.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = heSoLoaiAPPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected DinhMucPersistence dinhMucPersistence;

	@Reference
	protected vn.dnict.qlnhuanbut.service.HeSoLoaiAPLocalService
		heSoLoaiAPLocalService;

	protected HeSoLoaiAPService heSoLoaiAPService;

	@Reference
	protected HeSoLoaiAPPersistence heSoLoaiAPPersistence;

	@Reference
	protected HeSoTheLoaiPersistence heSoTheLoaiPersistence;

	@Reference
	protected ThongKeNBPersistence thongKeNBPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		HeSoLoaiAPServiceBaseImpl.class);

}