/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AnPham_DinhKemFile service. Represents a row in the &quot;cw_AnPham_DinhKemFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>qlanphamdb.model.impl.AnPham_DinhKemFileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>qlanphamdb.model.impl.AnPham_DinhKemFileImpl</code>.
 * </p>
 *
 * @author dnict
 * @see AnPham_DinhKemFile
 * @generated
 */
@ProviderType
public interface AnPham_DinhKemFileModel
	extends BaseModel<AnPham_DinhKemFile>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a an pham_ dinh kem file model instance should use the {@link AnPham_DinhKemFile} interface instead.
	 */

	/**
	 * Returns the primary key of this an pham_ dinh kem file.
	 *
	 * @return the primary key of this an pham_ dinh kem file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this an pham_ dinh kem file.
	 *
	 * @param primaryKey the primary key of this an pham_ dinh kem file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this an pham_ dinh kem file.
	 *
	 * @return the ID of this an pham_ dinh kem file
	 */
	public long getId();

	/**
	 * Sets the ID of this an pham_ dinh kem file.
	 *
	 * @param id the ID of this an pham_ dinh kem file
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this an pham_ dinh kem file.
	 *
	 * @return the company ID of this an pham_ dinh kem file
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this an pham_ dinh kem file.
	 *
	 * @param companyId the company ID of this an pham_ dinh kem file
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this an pham_ dinh kem file.
	 *
	 * @return the group ID of this an pham_ dinh kem file
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this an pham_ dinh kem file.
	 *
	 * @param groupId the group ID of this an pham_ dinh kem file
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this an pham_ dinh kem file.
	 *
	 * @return the user ID of this an pham_ dinh kem file
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this an pham_ dinh kem file.
	 *
	 * @param userId the user ID of this an pham_ dinh kem file
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this an pham_ dinh kem file.
	 *
	 * @return the user uuid of this an pham_ dinh kem file
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this an pham_ dinh kem file.
	 *
	 * @param userUuid the user uuid of this an pham_ dinh kem file
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the ten of this an pham_ dinh kem file.
	 *
	 * @return the ten of this an pham_ dinh kem file
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this an pham_ dinh kem file.
	 *
	 * @param ten the ten of this an pham_ dinh kem file
	 */
	public void setTen(String ten);

	/**
	 * Returns the url of this an pham_ dinh kem file.
	 *
	 * @return the url of this an pham_ dinh kem file
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this an pham_ dinh kem file.
	 *
	 * @param url the url of this an pham_ dinh kem file
	 */
	public void setUrl(String url);

	/**
	 * Returns the object of this an pham_ dinh kem file.
	 *
	 * @return the object of this an pham_ dinh kem file
	 */
	public long getObject();

	/**
	 * Sets the object of this an pham_ dinh kem file.
	 *
	 * @param Object the object of this an pham_ dinh kem file
	 */
	public void setObject(long Object);

	/**
	 * Returns the object ID of this an pham_ dinh kem file.
	 *
	 * @return the object ID of this an pham_ dinh kem file
	 */
	public long getObjectId();

	/**
	 * Sets the object ID of this an pham_ dinh kem file.
	 *
	 * @param ObjectId the object ID of this an pham_ dinh kem file
	 */
	public void setObjectId(long ObjectId);

	/**
	 * Returns the luot tai of this an pham_ dinh kem file.
	 *
	 * @return the luot tai of this an pham_ dinh kem file
	 */
	public long getLuotTai();

	/**
	 * Sets the luot tai of this an pham_ dinh kem file.
	 *
	 * @param luotTai the luot tai of this an pham_ dinh kem file
	 */
	public void setLuotTai(long luotTai);

	/**
	 * Returns the ghi chu of this an pham_ dinh kem file.
	 *
	 * @return the ghi chu of this an pham_ dinh kem file
	 */
	@AutoEscape
	public String getGhiChu();

	/**
	 * Sets the ghi chu of this an pham_ dinh kem file.
	 *
	 * @param ghiChu the ghi chu of this an pham_ dinh kem file
	 */
	public void setGhiChu(String ghiChu);

	/**
	 * Returns the delete_status of this an pham_ dinh kem file.
	 *
	 * @return the delete_status of this an pham_ dinh kem file
	 */
	public int getDelete_status();

	/**
	 * Sets the delete_status of this an pham_ dinh kem file.
	 *
	 * @param delete_status the delete_status of this an pham_ dinh kem file
	 */
	public void setDelete_status(int delete_status);

	/**
	 * Returns the status of this an pham_ dinh kem file.
	 *
	 * @return the status of this an pham_ dinh kem file
	 */
	public int getStatus();

	/**
	 * Sets the status of this an pham_ dinh kem file.
	 *
	 * @param status the status of this an pham_ dinh kem file
	 */
	public void setStatus(int status);

}