/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.tintuc.model.News_role;
import vn.dnict.tintuc.model.News_roleModel;

/**
 * The base model implementation for the News_role service. Represents a row in the &quot;cw_News_role&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>News_roleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link News_roleImpl}.
 * </p>
 *
 * @author dnict
 * @see News_roleImpl
 * @generated
 */
public class News_roleModelImpl
	extends BaseModelImpl<News_role> implements News_roleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news_role model instance should use the <code>News_role</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_News_role";

	public static final Object[][] TABLE_COLUMNS = {
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"id_", Types.BIGINT}, {"userid", Types.BIGINT},
		{"role_add", Types.INTEGER}, {"role_edit", Types.INTEGER},
		{"role_public", Types.INTEGER}, {"category_active_role", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("role_add", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("role_edit", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("role_public", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("category_active_role", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_News_role (companyId LONG,groupId LONG,id_ LONG not null primary key,userid LONG,role_add INTEGER,role_edit INTEGER,role_public INTEGER,category_active_role TEXT null)";

	public static final String TABLE_SQL_DROP = "drop table cw_News_role";

	public static final String ORDER_BY_JPQL = " ORDER BY news_role.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY cw_News_role.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public News_roleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return News_role.class;
	}

	@Override
	public String getModelClassName() {
		return News_role.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<News_role, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<News_role, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_role, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((News_role)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<News_role, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<News_role, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(News_role)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<News_role, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<News_role, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, News_role>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			News_role.class.getClassLoader(), News_role.class,
			ModelWrapper.class);

		try {
			Constructor<News_role> constructor =
				(Constructor<News_role>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<News_role, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<News_role, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<News_role, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<News_role, Object>>();
		Map<String, BiConsumer<News_role, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<News_role, ?>>();

		attributeGetterFunctions.put("companyId", News_role::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<News_role, Long>)News_role::setCompanyId);
		attributeGetterFunctions.put("groupId", News_role::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<News_role, Long>)News_role::setGroupId);
		attributeGetterFunctions.put("id", News_role::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<News_role, Long>)News_role::setId);
		attributeGetterFunctions.put("userid", News_role::getUserid);
		attributeSetterBiConsumers.put(
			"userid", (BiConsumer<News_role, Long>)News_role::setUserid);
		attributeGetterFunctions.put("role_add", News_role::getRole_add);
		attributeSetterBiConsumers.put(
			"role_add", (BiConsumer<News_role, Integer>)News_role::setRole_add);
		attributeGetterFunctions.put("role_edit", News_role::getRole_edit);
		attributeSetterBiConsumers.put(
			"role_edit",
			(BiConsumer<News_role, Integer>)News_role::setRole_edit);
		attributeGetterFunctions.put("role_public", News_role::getRole_public);
		attributeSetterBiConsumers.put(
			"role_public",
			(BiConsumer<News_role, Integer>)News_role::setRole_public);
		attributeGetterFunctions.put(
			"category_active_role", News_role::getCategory_active_role);
		attributeSetterBiConsumers.put(
			"category_active_role",
			(BiConsumer<News_role, String>)News_role::setCategory_active_role);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getUserid() {
		return _userid;
	}

	@Override
	public void setUserid(long userid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userid = userid;
	}

	@Override
	public int getRole_add() {
		return _role_add;
	}

	@Override
	public void setRole_add(int role_add) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_role_add = role_add;
	}

	@Override
	public int getRole_edit() {
		return _role_edit;
	}

	@Override
	public void setRole_edit(int role_edit) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_role_edit = role_edit;
	}

	@Override
	public int getRole_public() {
		return _role_public;
	}

	@Override
	public void setRole_public(int role_public) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_role_public = role_public;
	}

	@Override
	public String getCategory_active_role() {
		if (_category_active_role == null) {
			return "";
		}
		else {
			return _category_active_role;
		}
	}

	@Override
	public void setCategory_active_role(String category_active_role) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_category_active_role = category_active_role;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), News_role.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public News_role toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, News_role>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		News_roleImpl news_roleImpl = new News_roleImpl();

		news_roleImpl.setCompanyId(getCompanyId());
		news_roleImpl.setGroupId(getGroupId());
		news_roleImpl.setId(getId());
		news_roleImpl.setUserid(getUserid());
		news_roleImpl.setRole_add(getRole_add());
		news_roleImpl.setRole_edit(getRole_edit());
		news_roleImpl.setRole_public(getRole_public());
		news_roleImpl.setCategory_active_role(getCategory_active_role());

		news_roleImpl.resetOriginalValues();

		return news_roleImpl;
	}

	@Override
	public int compareTo(News_role news_role) {
		long primaryKey = news_role.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof News_role)) {
			return false;
		}

		News_role news_role = (News_role)object;

		long primaryKey = news_role.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<News_role> toCacheModel() {
		News_roleCacheModel news_roleCacheModel = new News_roleCacheModel();

		news_roleCacheModel.companyId = getCompanyId();

		news_roleCacheModel.groupId = getGroupId();

		news_roleCacheModel.id = getId();

		news_roleCacheModel.userid = getUserid();

		news_roleCacheModel.role_add = getRole_add();

		news_roleCacheModel.role_edit = getRole_edit();

		news_roleCacheModel.role_public = getRole_public();

		news_roleCacheModel.category_active_role = getCategory_active_role();

		String category_active_role = news_roleCacheModel.category_active_role;

		if ((category_active_role != null) &&
			(category_active_role.length() == 0)) {

			news_roleCacheModel.category_active_role = null;
		}

		return news_roleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<News_role, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<News_role, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_role, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((News_role)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<News_role, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<News_role, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<News_role, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((News_role)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, News_role>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _companyId;
	private long _groupId;
	private long _id;
	private long _userid;
	private int _role_add;
	private int _role_edit;
	private int _role_public;
	private String _category_active_role;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<News_role, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((News_role)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("userid", _userid);
		_columnOriginalValues.put("role_add", _role_add);
		_columnOriginalValues.put("role_edit", _role_edit);
		_columnOriginalValues.put("role_public", _role_public);
		_columnOriginalValues.put(
			"category_active_role", _category_active_role);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("companyId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("id_", 4L);

		columnBitmasks.put("userid", 8L);

		columnBitmasks.put("role_add", 16L);

		columnBitmasks.put("role_edit", 32L);

		columnBitmasks.put("role_public", 64L);

		columnBitmasks.put("category_active_role", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private News_role _escapedModel;

}