/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.tintuc.model.impl;

import vn.dnict.tintuc.model.News_Article;
import vn.dnict.tintuc.service.News_ArticleLocalServiceUtil;

/**
 * The extended model base implementation for the News_Article service. Represents a row in the &quot;cw_News_Article&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link News_ArticleImpl}.
 * </p>
 *
 * @author dnict
 * @see News_ArticleImpl
 * @see News_Article
 * @generated
 */
public abstract class News_ArticleBaseImpl
	extends News_ArticleModelImpl implements News_Article {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news_ article model instance should use the <code>News_Article</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			News_ArticleLocalServiceUtil.addNews_Article(this);
		}
		else {
			News_ArticleLocalServiceUtil.updateNews_Article(this);
		}
	}

}