/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import qlanphamdb.model.AnPham_CongTacVien;
import qlanphamdb.model.AnPham_CongTacVienModel;

/**
 * The base model implementation for the AnPham_CongTacVien service. Represents a row in the &quot;cw_AnPham_CongTacVien&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnPham_CongTacVienModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnPham_CongTacVienImpl}.
 * </p>
 *
 * @author dnict
 * @see AnPham_CongTacVienImpl
 * @generated
 */
public class AnPham_CongTacVienModelImpl
	extends BaseModelImpl<AnPham_CongTacVien>
	implements AnPham_CongTacVienModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a an pham_ cong tac vien model instance should use the <code>AnPham_CongTacVien</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_AnPham_CongTacVien";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"hoTen", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"thongTin", Types.VARCHAR},
		{"status", Types.INTEGER}, {"orders", Types.BIGINT},
		{"delete_status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hoTen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("thongTin", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("orders", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_AnPham_CongTacVien (id_ LONG not null primary key,groupId LONG,companyId LONG,hoTen VARCHAR(75) null,email VARCHAR(75) null,thongTin VARCHAR(75) null,status INTEGER,orders LONG,delete_status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_AnPham_CongTacVien";

	public static final String ORDER_BY_JPQL =
		" ORDER BY anPham_CongTacVien.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_AnPham_CongTacVien.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnPham_CongTacVienModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnPham_CongTacVien.class;
	}

	@Override
	public String getModelClassName() {
		return AnPham_CongTacVien.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnPham_CongTacVien, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnPham_CongTacVien, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_CongTacVien, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnPham_CongTacVien)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnPham_CongTacVien, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnPham_CongTacVien, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnPham_CongTacVien)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnPham_CongTacVien, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnPham_CongTacVien, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AnPham_CongTacVien>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AnPham_CongTacVien.class.getClassLoader(), AnPham_CongTacVien.class,
			ModelWrapper.class);

		try {
			Constructor<AnPham_CongTacVien> constructor =
				(Constructor<AnPham_CongTacVien>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AnPham_CongTacVien, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AnPham_CongTacVien, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AnPham_CongTacVien, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AnPham_CongTacVien, Object>>();
		Map<String, BiConsumer<AnPham_CongTacVien, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AnPham_CongTacVien, ?>>();

		attributeGetterFunctions.put("id", AnPham_CongTacVien::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<AnPham_CongTacVien, Long>)AnPham_CongTacVien::setId);
		attributeGetterFunctions.put("groupId", AnPham_CongTacVien::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AnPham_CongTacVien, Long>)
				AnPham_CongTacVien::setGroupId);
		attributeGetterFunctions.put(
			"companyId", AnPham_CongTacVien::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AnPham_CongTacVien, Long>)
				AnPham_CongTacVien::setCompanyId);
		attributeGetterFunctions.put("hoTen", AnPham_CongTacVien::getHoTen);
		attributeSetterBiConsumers.put(
			"hoTen",
			(BiConsumer<AnPham_CongTacVien, String>)
				AnPham_CongTacVien::setHoTen);
		attributeGetterFunctions.put("email", AnPham_CongTacVien::getEmail);
		attributeSetterBiConsumers.put(
			"email",
			(BiConsumer<AnPham_CongTacVien, String>)
				AnPham_CongTacVien::setEmail);
		attributeGetterFunctions.put(
			"thongTin", AnPham_CongTacVien::getThongTin);
		attributeSetterBiConsumers.put(
			"thongTin",
			(BiConsumer<AnPham_CongTacVien, String>)
				AnPham_CongTacVien::setThongTin);
		attributeGetterFunctions.put("status", AnPham_CongTacVien::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<AnPham_CongTacVien, Integer>)
				AnPham_CongTacVien::setStatus);
		attributeGetterFunctions.put("orders", AnPham_CongTacVien::getOrders);
		attributeSetterBiConsumers.put(
			"orders",
			(BiConsumer<AnPham_CongTacVien, Long>)
				AnPham_CongTacVien::setOrders);
		attributeGetterFunctions.put(
			"delete_status", AnPham_CongTacVien::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<AnPham_CongTacVien, Integer>)
				AnPham_CongTacVien::setDelete_status);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getHoTen() {
		if (_hoTen == null) {
			return "";
		}
		else {
			return _hoTen;
		}
	}

	@Override
	public void setHoTen(String hoTen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hoTen = hoTen;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public String getThongTin() {
		if (_thongTin == null) {
			return "";
		}
		else {
			return _thongTin;
		}
	}

	@Override
	public void setThongTin(String thongTin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_thongTin = thongTin;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getOrders() {
		return _orders;
	}

	@Override
	public void setOrders(long orders) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orders = orders;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AnPham_CongTacVien.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnPham_CongTacVien toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnPham_CongTacVien>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnPham_CongTacVienImpl anPham_CongTacVienImpl =
			new AnPham_CongTacVienImpl();

		anPham_CongTacVienImpl.setId(getId());
		anPham_CongTacVienImpl.setGroupId(getGroupId());
		anPham_CongTacVienImpl.setCompanyId(getCompanyId());
		anPham_CongTacVienImpl.setHoTen(getHoTen());
		anPham_CongTacVienImpl.setEmail(getEmail());
		anPham_CongTacVienImpl.setThongTin(getThongTin());
		anPham_CongTacVienImpl.setStatus(getStatus());
		anPham_CongTacVienImpl.setOrders(getOrders());
		anPham_CongTacVienImpl.setDelete_status(getDelete_status());

		anPham_CongTacVienImpl.resetOriginalValues();

		return anPham_CongTacVienImpl;
	}

	@Override
	public int compareTo(AnPham_CongTacVien anPham_CongTacVien) {
		int value = 0;

		if (getId() < anPham_CongTacVien.getId()) {
			value = -1;
		}
		else if (getId() > anPham_CongTacVien.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnPham_CongTacVien)) {
			return false;
		}

		AnPham_CongTacVien anPham_CongTacVien = (AnPham_CongTacVien)object;

		long primaryKey = anPham_CongTacVien.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnPham_CongTacVien> toCacheModel() {
		AnPham_CongTacVienCacheModel anPham_CongTacVienCacheModel =
			new AnPham_CongTacVienCacheModel();

		anPham_CongTacVienCacheModel.id = getId();

		anPham_CongTacVienCacheModel.groupId = getGroupId();

		anPham_CongTacVienCacheModel.companyId = getCompanyId();

		anPham_CongTacVienCacheModel.hoTen = getHoTen();

		String hoTen = anPham_CongTacVienCacheModel.hoTen;

		if ((hoTen != null) && (hoTen.length() == 0)) {
			anPham_CongTacVienCacheModel.hoTen = null;
		}

		anPham_CongTacVienCacheModel.email = getEmail();

		String email = anPham_CongTacVienCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			anPham_CongTacVienCacheModel.email = null;
		}

		anPham_CongTacVienCacheModel.thongTin = getThongTin();

		String thongTin = anPham_CongTacVienCacheModel.thongTin;

		if ((thongTin != null) && (thongTin.length() == 0)) {
			anPham_CongTacVienCacheModel.thongTin = null;
		}

		anPham_CongTacVienCacheModel.status = getStatus();

		anPham_CongTacVienCacheModel.orders = getOrders();

		anPham_CongTacVienCacheModel.delete_status = getDelete_status();

		return anPham_CongTacVienCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnPham_CongTacVien, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnPham_CongTacVien, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_CongTacVien, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AnPham_CongTacVien)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AnPham_CongTacVien, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AnPham_CongTacVien, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_CongTacVien, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AnPham_CongTacVien)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnPham_CongTacVien>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _groupId;
	private long _companyId;
	private String _hoTen;
	private String _email;
	private String _thongTin;
	private int _status;
	private long _orders;
	private int _delete_status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnPham_CongTacVien, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnPham_CongTacVien)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("hoTen", _hoTen);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("thongTin", _thongTin);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("orders", _orders);
		_columnOriginalValues.put("delete_status", _delete_status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("hoTen", 8L);

		columnBitmasks.put("email", 16L);

		columnBitmasks.put("thongTin", 32L);

		columnBitmasks.put("status", 64L);

		columnBitmasks.put("orders", 128L);

		columnBitmasks.put("delete_status", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnPham_CongTacVien _escapedModel;

}