/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import qlanphamdb.model.AnPham_DinhKemFile;
import qlanphamdb.model.AnPham_DinhKemFileModel;

/**
 * The base model implementation for the AnPham_DinhKemFile service. Represents a row in the &quot;cw_AnPham_DinhKemFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnPham_DinhKemFileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnPham_DinhKemFileImpl}.
 * </p>
 *
 * @author dnict
 * @see AnPham_DinhKemFileImpl
 * @generated
 */
public class AnPham_DinhKemFileModelImpl
	extends BaseModelImpl<AnPham_DinhKemFile>
	implements AnPham_DinhKemFileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a an pham_ dinh kem file model instance should use the <code>AnPham_DinhKemFile</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_AnPham_DinhKemFile";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"ten", Types.VARCHAR}, {"url", Types.VARCHAR},
		{"Object", Types.BIGINT}, {"ObjectId", Types.BIGINT},
		{"luotTai", Types.BIGINT}, {"ghiChu", Types.VARCHAR},
		{"delete_status", Types.INTEGER}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Object", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ObjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("luotTai", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ghiChu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_AnPham_DinhKemFile (id_ LONG not null primary key,companyId LONG,groupId LONG,userId LONG,ten VARCHAR(75) null,url VARCHAR(75) null,Object LONG,ObjectId LONG,luotTai LONG,ghiChu VARCHAR(75) null,delete_status INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_AnPham_DinhKemFile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY anPham_DinhKemFile.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_AnPham_DinhKemFile.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnPham_DinhKemFileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnPham_DinhKemFile.class;
	}

	@Override
	public String getModelClassName() {
		return AnPham_DinhKemFile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnPham_DinhKemFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnPham_DinhKemFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_DinhKemFile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnPham_DinhKemFile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnPham_DinhKemFile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnPham_DinhKemFile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnPham_DinhKemFile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnPham_DinhKemFile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnPham_DinhKemFile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AnPham_DinhKemFile>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AnPham_DinhKemFile.class.getClassLoader(), AnPham_DinhKemFile.class,
			ModelWrapper.class);

		try {
			Constructor<AnPham_DinhKemFile> constructor =
				(Constructor<AnPham_DinhKemFile>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AnPham_DinhKemFile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AnPham_DinhKemFile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AnPham_DinhKemFile, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AnPham_DinhKemFile, Object>>();
		Map<String, BiConsumer<AnPham_DinhKemFile, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AnPham_DinhKemFile, ?>>();

		attributeGetterFunctions.put("id", AnPham_DinhKemFile::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<AnPham_DinhKemFile, Long>)AnPham_DinhKemFile::setId);
		attributeGetterFunctions.put(
			"companyId", AnPham_DinhKemFile::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setCompanyId);
		attributeGetterFunctions.put("groupId", AnPham_DinhKemFile::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setGroupId);
		attributeGetterFunctions.put("userId", AnPham_DinhKemFile::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setUserId);
		attributeGetterFunctions.put("ten", AnPham_DinhKemFile::getTen);
		attributeSetterBiConsumers.put(
			"ten",
			(BiConsumer<AnPham_DinhKemFile, String>)AnPham_DinhKemFile::setTen);
		attributeGetterFunctions.put("url", AnPham_DinhKemFile::getUrl);
		attributeSetterBiConsumers.put(
			"url",
			(BiConsumer<AnPham_DinhKemFile, String>)AnPham_DinhKemFile::setUrl);
		attributeGetterFunctions.put("Object", AnPham_DinhKemFile::getObject);
		attributeSetterBiConsumers.put(
			"Object",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setObject);
		attributeGetterFunctions.put(
			"ObjectId", AnPham_DinhKemFile::getObjectId);
		attributeSetterBiConsumers.put(
			"ObjectId",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setObjectId);
		attributeGetterFunctions.put("luotTai", AnPham_DinhKemFile::getLuotTai);
		attributeSetterBiConsumers.put(
			"luotTai",
			(BiConsumer<AnPham_DinhKemFile, Long>)
				AnPham_DinhKemFile::setLuotTai);
		attributeGetterFunctions.put("ghiChu", AnPham_DinhKemFile::getGhiChu);
		attributeSetterBiConsumers.put(
			"ghiChu",
			(BiConsumer<AnPham_DinhKemFile, String>)
				AnPham_DinhKemFile::setGhiChu);
		attributeGetterFunctions.put(
			"delete_status", AnPham_DinhKemFile::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<AnPham_DinhKemFile, Integer>)
				AnPham_DinhKemFile::setDelete_status);
		attributeGetterFunctions.put("status", AnPham_DinhKemFile::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<AnPham_DinhKemFile, Integer>)
				AnPham_DinhKemFile::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@Override
	public long getObject() {
		return _Object;
	}

	@Override
	public void setObject(long Object) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Object = Object;
	}

	@Override
	public long getObjectId() {
		return _ObjectId;
	}

	@Override
	public void setObjectId(long ObjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ObjectId = ObjectId;
	}

	@Override
	public long getLuotTai() {
		return _luotTai;
	}

	@Override
	public void setLuotTai(long luotTai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_luotTai = luotTai;
	}

	@Override
	public String getGhiChu() {
		if (_ghiChu == null) {
			return "";
		}
		else {
			return _ghiChu;
		}
	}

	@Override
	public void setGhiChu(String ghiChu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ghiChu = ghiChu;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AnPham_DinhKemFile.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnPham_DinhKemFile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnPham_DinhKemFile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnPham_DinhKemFileImpl anPham_DinhKemFileImpl =
			new AnPham_DinhKemFileImpl();

		anPham_DinhKemFileImpl.setId(getId());
		anPham_DinhKemFileImpl.setCompanyId(getCompanyId());
		anPham_DinhKemFileImpl.setGroupId(getGroupId());
		anPham_DinhKemFileImpl.setUserId(getUserId());
		anPham_DinhKemFileImpl.setTen(getTen());
		anPham_DinhKemFileImpl.setUrl(getUrl());
		anPham_DinhKemFileImpl.setObject(getObject());
		anPham_DinhKemFileImpl.setObjectId(getObjectId());
		anPham_DinhKemFileImpl.setLuotTai(getLuotTai());
		anPham_DinhKemFileImpl.setGhiChu(getGhiChu());
		anPham_DinhKemFileImpl.setDelete_status(getDelete_status());
		anPham_DinhKemFileImpl.setStatus(getStatus());

		anPham_DinhKemFileImpl.resetOriginalValues();

		return anPham_DinhKemFileImpl;
	}

	@Override
	public int compareTo(AnPham_DinhKemFile anPham_DinhKemFile) {
		long primaryKey = anPham_DinhKemFile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnPham_DinhKemFile)) {
			return false;
		}

		AnPham_DinhKemFile anPham_DinhKemFile = (AnPham_DinhKemFile)object;

		long primaryKey = anPham_DinhKemFile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnPham_DinhKemFile> toCacheModel() {
		AnPham_DinhKemFileCacheModel anPham_DinhKemFileCacheModel =
			new AnPham_DinhKemFileCacheModel();

		anPham_DinhKemFileCacheModel.id = getId();

		anPham_DinhKemFileCacheModel.companyId = getCompanyId();

		anPham_DinhKemFileCacheModel.groupId = getGroupId();

		anPham_DinhKemFileCacheModel.userId = getUserId();

		anPham_DinhKemFileCacheModel.ten = getTen();

		String ten = anPham_DinhKemFileCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			anPham_DinhKemFileCacheModel.ten = null;
		}

		anPham_DinhKemFileCacheModel.url = getUrl();

		String url = anPham_DinhKemFileCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			anPham_DinhKemFileCacheModel.url = null;
		}

		anPham_DinhKemFileCacheModel.Object = getObject();

		anPham_DinhKemFileCacheModel.ObjectId = getObjectId();

		anPham_DinhKemFileCacheModel.luotTai = getLuotTai();

		anPham_DinhKemFileCacheModel.ghiChu = getGhiChu();

		String ghiChu = anPham_DinhKemFileCacheModel.ghiChu;

		if ((ghiChu != null) && (ghiChu.length() == 0)) {
			anPham_DinhKemFileCacheModel.ghiChu = null;
		}

		anPham_DinhKemFileCacheModel.delete_status = getDelete_status();

		anPham_DinhKemFileCacheModel.status = getStatus();

		return anPham_DinhKemFileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnPham_DinhKemFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnPham_DinhKemFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_DinhKemFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AnPham_DinhKemFile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AnPham_DinhKemFile, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AnPham_DinhKemFile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_DinhKemFile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AnPham_DinhKemFile)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnPham_DinhKemFile>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _ten;
	private String _url;
	private long _Object;
	private long _ObjectId;
	private long _luotTai;
	private String _ghiChu;
	private int _delete_status;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnPham_DinhKemFile, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnPham_DinhKemFile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("Object", _Object);
		_columnOriginalValues.put("ObjectId", _ObjectId);
		_columnOriginalValues.put("luotTai", _luotTai);
		_columnOriginalValues.put("ghiChu", _ghiChu);
		_columnOriginalValues.put("delete_status", _delete_status);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("ten", 16L);

		columnBitmasks.put("url", 32L);

		columnBitmasks.put("Object", 64L);

		columnBitmasks.put("ObjectId", 128L);

		columnBitmasks.put("luotTai", 256L);

		columnBitmasks.put("ghiChu", 512L);

		columnBitmasks.put("delete_status", 1024L);

		columnBitmasks.put("status", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnPham_DinhKemFile _escapedModel;

}