/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import qlanphamdb.model.AnPham_Logs;
import qlanphamdb.model.AnPham_LogsModel;

/**
 * The base model implementation for the AnPham_Logs service. Represents a row in the &quot;cw_AnPham_Logs&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnPham_LogsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnPham_LogsImpl}.
 * </p>
 *
 * @author dnict
 * @see AnPham_LogsImpl
 * @generated
 */
public class AnPham_LogsModelImpl
	extends BaseModelImpl<AnPham_Logs> implements AnPham_LogsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a an pham_ logs model instance should use the <code>AnPham_Logs</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_AnPham_Logs";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"activityId", Types.BIGINT},
		{"ten", Types.VARCHAR}, {"slug", Types.VARCHAR},
		{"moTa", Types.VARCHAR}, {"anhDaiDien", Types.VARCHAR},
		{"loaiId", Types.BIGINT}, {"deCuongId", Types.BIGINT},
		{"noiDung", Types.VARCHAR}, {"tuKhoa", Types.VARCHAR},
		{"phienBan", Types.BIGINT}, {"luotXem", Types.BIGINT},
		{"anPhamId", Types.BIGINT}, {"noiDungLog", Types.VARCHAR},
		{"nguoiTao", Types.BIGINT}, {"ngayTao", Types.TIMESTAMP},
		{"nguoiSua", Types.BIGINT}, {"ngaySua", Types.TIMESTAMP},
		{"nguoiNhan", Types.BIGINT}, {"nguoiXuLy", Types.BIGINT},
		{"ngayXuLy", Types.TIMESTAMP}, {"language", Types.VARCHAR},
		{"loaiTin", Types.INTEGER}, {"isFormHienBinhLuan", Types.INTEGER},
		{"isFormViewBinhLuan", Types.INTEGER}, {"status", Types.INTEGER},
		{"orders", Types.BIGINT}, {"delete_status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("activityId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("slug", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("moTa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anhDaiDien", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loaiId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("deCuongId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("noiDung", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tuKhoa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phienBan", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("luotXem", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("anPhamId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("noiDungLog", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nguoiTao", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayTao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nguoiSua", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngaySua", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nguoiNhan", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoiXuLy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayXuLy", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loaiTin", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isFormHienBinhLuan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isFormViewBinhLuan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("orders", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_AnPham_Logs (id_ LONG not null primary key,groupId LONG,companyId LONG,activityId LONG,ten VARCHAR(75) null,slug VARCHAR(75) null,moTa VARCHAR(75) null,anhDaiDien VARCHAR(75) null,loaiId LONG,deCuongId LONG,noiDung VARCHAR(75) null,tuKhoa VARCHAR(75) null,phienBan LONG,luotXem LONG,anPhamId LONG,noiDungLog VARCHAR(75) null,nguoiTao LONG,ngayTao DATE null,nguoiSua LONG,ngaySua DATE null,nguoiNhan LONG,nguoiXuLy LONG,ngayXuLy DATE null,language VARCHAR(75) null,loaiTin INTEGER,isFormHienBinhLuan INTEGER,isFormViewBinhLuan INTEGER,status INTEGER,orders LONG,delete_status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table cw_AnPham_Logs";

	public static final String ORDER_BY_JPQL = " ORDER BY anPham_Logs.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_AnPham_Logs.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnPham_LogsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnPham_Logs.class;
	}

	@Override
	public String getModelClassName() {
		return AnPham_Logs.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnPham_Logs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnPham_Logs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_Logs, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnPham_Logs)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnPham_Logs, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnPham_Logs, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnPham_Logs)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnPham_Logs, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnPham_Logs, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AnPham_Logs>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AnPham_Logs.class.getClassLoader(), AnPham_Logs.class,
			ModelWrapper.class);

		try {
			Constructor<AnPham_Logs> constructor =
				(Constructor<AnPham_Logs>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AnPham_Logs, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AnPham_Logs, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AnPham_Logs, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AnPham_Logs, Object>>();
		Map<String, BiConsumer<AnPham_Logs, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AnPham_Logs, ?>>();

		attributeGetterFunctions.put("id", AnPham_Logs::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setId);
		attributeGetterFunctions.put("groupId", AnPham_Logs::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setGroupId);
		attributeGetterFunctions.put("companyId", AnPham_Logs::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setCompanyId);
		attributeGetterFunctions.put("activityId", AnPham_Logs::getActivityId);
		attributeSetterBiConsumers.put(
			"activityId",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setActivityId);
		attributeGetterFunctions.put("ten", AnPham_Logs::getTen);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<AnPham_Logs, String>)AnPham_Logs::setTen);
		attributeGetterFunctions.put("slug", AnPham_Logs::getSlug);
		attributeSetterBiConsumers.put(
			"slug", (BiConsumer<AnPham_Logs, String>)AnPham_Logs::setSlug);
		attributeGetterFunctions.put("moTa", AnPham_Logs::getMoTa);
		attributeSetterBiConsumers.put(
			"moTa", (BiConsumer<AnPham_Logs, String>)AnPham_Logs::setMoTa);
		attributeGetterFunctions.put("anhDaiDien", AnPham_Logs::getAnhDaiDien);
		attributeSetterBiConsumers.put(
			"anhDaiDien",
			(BiConsumer<AnPham_Logs, String>)AnPham_Logs::setAnhDaiDien);
		attributeGetterFunctions.put("loaiId", AnPham_Logs::getLoaiId);
		attributeSetterBiConsumers.put(
			"loaiId", (BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setLoaiId);
		attributeGetterFunctions.put("deCuongId", AnPham_Logs::getDeCuongId);
		attributeSetterBiConsumers.put(
			"deCuongId",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setDeCuongId);
		attributeGetterFunctions.put("noiDung", AnPham_Logs::getNoiDung);
		attributeSetterBiConsumers.put(
			"noiDung",
			(BiConsumer<AnPham_Logs, String>)AnPham_Logs::setNoiDung);
		attributeGetterFunctions.put("tuKhoa", AnPham_Logs::getTuKhoa);
		attributeSetterBiConsumers.put(
			"tuKhoa", (BiConsumer<AnPham_Logs, String>)AnPham_Logs::setTuKhoa);
		attributeGetterFunctions.put("phienBan", AnPham_Logs::getPhienBan);
		attributeSetterBiConsumers.put(
			"phienBan",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setPhienBan);
		attributeGetterFunctions.put("luotXem", AnPham_Logs::getLuotXem);
		attributeSetterBiConsumers.put(
			"luotXem", (BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setLuotXem);
		attributeGetterFunctions.put("anPhamId", AnPham_Logs::getAnPhamId);
		attributeSetterBiConsumers.put(
			"anPhamId",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setAnPhamId);
		attributeGetterFunctions.put("noiDungLog", AnPham_Logs::getNoiDungLog);
		attributeSetterBiConsumers.put(
			"noiDungLog",
			(BiConsumer<AnPham_Logs, String>)AnPham_Logs::setNoiDungLog);
		attributeGetterFunctions.put("nguoiTao", AnPham_Logs::getNguoiTao);
		attributeSetterBiConsumers.put(
			"nguoiTao",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setNguoiTao);
		attributeGetterFunctions.put("ngayTao", AnPham_Logs::getNgayTao);
		attributeSetterBiConsumers.put(
			"ngayTao", (BiConsumer<AnPham_Logs, Date>)AnPham_Logs::setNgayTao);
		attributeGetterFunctions.put("nguoiSua", AnPham_Logs::getNguoiSua);
		attributeSetterBiConsumers.put(
			"nguoiSua",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setNguoiSua);
		attributeGetterFunctions.put("ngaySua", AnPham_Logs::getNgaySua);
		attributeSetterBiConsumers.put(
			"ngaySua", (BiConsumer<AnPham_Logs, Date>)AnPham_Logs::setNgaySua);
		attributeGetterFunctions.put("nguoiNhan", AnPham_Logs::getNguoiNhan);
		attributeSetterBiConsumers.put(
			"nguoiNhan",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setNguoiNhan);
		attributeGetterFunctions.put("nguoiXuLy", AnPham_Logs::getNguoiXuLy);
		attributeSetterBiConsumers.put(
			"nguoiXuLy",
			(BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setNguoiXuLy);
		attributeGetterFunctions.put("ngayXuLy", AnPham_Logs::getNgayXuLy);
		attributeSetterBiConsumers.put(
			"ngayXuLy",
			(BiConsumer<AnPham_Logs, Date>)AnPham_Logs::setNgayXuLy);
		attributeGetterFunctions.put("language", AnPham_Logs::getLanguage);
		attributeSetterBiConsumers.put(
			"language",
			(BiConsumer<AnPham_Logs, String>)AnPham_Logs::setLanguage);
		attributeGetterFunctions.put("loaiTin", AnPham_Logs::getLoaiTin);
		attributeSetterBiConsumers.put(
			"loaiTin",
			(BiConsumer<AnPham_Logs, Integer>)AnPham_Logs::setLoaiTin);
		attributeGetterFunctions.put(
			"isFormHienBinhLuan", AnPham_Logs::getIsFormHienBinhLuan);
		attributeSetterBiConsumers.put(
			"isFormHienBinhLuan",
			(BiConsumer<AnPham_Logs, Integer>)
				AnPham_Logs::setIsFormHienBinhLuan);
		attributeGetterFunctions.put(
			"isFormViewBinhLuan", AnPham_Logs::getIsFormViewBinhLuan);
		attributeSetterBiConsumers.put(
			"isFormViewBinhLuan",
			(BiConsumer<AnPham_Logs, Integer>)
				AnPham_Logs::setIsFormViewBinhLuan);
		attributeGetterFunctions.put("status", AnPham_Logs::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<AnPham_Logs, Integer>)AnPham_Logs::setStatus);
		attributeGetterFunctions.put("orders", AnPham_Logs::getOrders);
		attributeSetterBiConsumers.put(
			"orders", (BiConsumer<AnPham_Logs, Long>)AnPham_Logs::setOrders);
		attributeGetterFunctions.put(
			"delete_status", AnPham_Logs::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<AnPham_Logs, Integer>)AnPham_Logs::setDelete_status);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getActivityId() {
		return _activityId;
	}

	@Override
	public void setActivityId(long activityId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_activityId = activityId;
	}

	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@Override
	public String getSlug() {
		if (_slug == null) {
			return "";
		}
		else {
			return _slug;
		}
	}

	@Override
	public void setSlug(String slug) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_slug = slug;
	}

	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return "";
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_moTa = moTa;
	}

	@Override
	public String getAnhDaiDien() {
		if (_anhDaiDien == null) {
			return "";
		}
		else {
			return _anhDaiDien;
		}
	}

	@Override
	public void setAnhDaiDien(String anhDaiDien) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anhDaiDien = anhDaiDien;
	}

	@Override
	public long getLoaiId() {
		return _loaiId;
	}

	@Override
	public void setLoaiId(long loaiId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loaiId = loaiId;
	}

	@Override
	public long getDeCuongId() {
		return _deCuongId;
	}

	@Override
	public void setDeCuongId(long deCuongId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deCuongId = deCuongId;
	}

	@Override
	public String getNoiDung() {
		if (_noiDung == null) {
			return "";
		}
		else {
			return _noiDung;
		}
	}

	@Override
	public void setNoiDung(String noiDung) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noiDung = noiDung;
	}

	@Override
	public String getTuKhoa() {
		if (_tuKhoa == null) {
			return "";
		}
		else {
			return _tuKhoa;
		}
	}

	@Override
	public void setTuKhoa(String tuKhoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tuKhoa = tuKhoa;
	}

	@Override
	public long getPhienBan() {
		return _phienBan;
	}

	@Override
	public void setPhienBan(long phienBan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phienBan = phienBan;
	}

	@Override
	public long getLuotXem() {
		return _luotXem;
	}

	@Override
	public void setLuotXem(long luotXem) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_luotXem = luotXem;
	}

	@Override
	public long getAnPhamId() {
		return _anPhamId;
	}

	@Override
	public void setAnPhamId(long anPhamId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anPhamId = anPhamId;
	}

	@Override
	public String getNoiDungLog() {
		if (_noiDungLog == null) {
			return "";
		}
		else {
			return _noiDungLog;
		}
	}

	@Override
	public void setNoiDungLog(String noiDungLog) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noiDungLog = noiDungLog;
	}

	@Override
	public long getNguoiTao() {
		return _nguoiTao;
	}

	@Override
	public void setNguoiTao(long nguoiTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiTao = nguoiTao;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayTao = ngayTao;
	}

	@Override
	public long getNguoiSua() {
		return _nguoiSua;
	}

	@Override
	public void setNguoiSua(long nguoiSua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiSua = nguoiSua;
	}

	@Override
	public Date getNgaySua() {
		return _ngaySua;
	}

	@Override
	public void setNgaySua(Date ngaySua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaySua = ngaySua;
	}

	@Override
	public long getNguoiNhan() {
		return _nguoiNhan;
	}

	@Override
	public void setNguoiNhan(long nguoiNhan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiNhan = nguoiNhan;
	}

	@Override
	public long getNguoiXuLy() {
		return _nguoiXuLy;
	}

	@Override
	public void setNguoiXuLy(long nguoiXuLy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiXuLy = nguoiXuLy;
	}

	@Override
	public Date getNgayXuLy() {
		return _ngayXuLy;
	}

	@Override
	public void setNgayXuLy(Date ngayXuLy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayXuLy = ngayXuLy;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return "";
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_language = language;
	}

	@Override
	public int getLoaiTin() {
		return _loaiTin;
	}

	@Override
	public void setLoaiTin(int loaiTin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loaiTin = loaiTin;
	}

	@Override
	public int getIsFormHienBinhLuan() {
		return _isFormHienBinhLuan;
	}

	@Override
	public void setIsFormHienBinhLuan(int isFormHienBinhLuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFormHienBinhLuan = isFormHienBinhLuan;
	}

	@Override
	public int getIsFormViewBinhLuan() {
		return _isFormViewBinhLuan;
	}

	@Override
	public void setIsFormViewBinhLuan(int isFormViewBinhLuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFormViewBinhLuan = isFormViewBinhLuan;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getOrders() {
		return _orders;
	}

	@Override
	public void setOrders(long orders) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orders = orders;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AnPham_Logs.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnPham_Logs toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnPham_Logs>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnPham_LogsImpl anPham_LogsImpl = new AnPham_LogsImpl();

		anPham_LogsImpl.setId(getId());
		anPham_LogsImpl.setGroupId(getGroupId());
		anPham_LogsImpl.setCompanyId(getCompanyId());
		anPham_LogsImpl.setActivityId(getActivityId());
		anPham_LogsImpl.setTen(getTen());
		anPham_LogsImpl.setSlug(getSlug());
		anPham_LogsImpl.setMoTa(getMoTa());
		anPham_LogsImpl.setAnhDaiDien(getAnhDaiDien());
		anPham_LogsImpl.setLoaiId(getLoaiId());
		anPham_LogsImpl.setDeCuongId(getDeCuongId());
		anPham_LogsImpl.setNoiDung(getNoiDung());
		anPham_LogsImpl.setTuKhoa(getTuKhoa());
		anPham_LogsImpl.setPhienBan(getPhienBan());
		anPham_LogsImpl.setLuotXem(getLuotXem());
		anPham_LogsImpl.setAnPhamId(getAnPhamId());
		anPham_LogsImpl.setNoiDungLog(getNoiDungLog());
		anPham_LogsImpl.setNguoiTao(getNguoiTao());
		anPham_LogsImpl.setNgayTao(getNgayTao());
		anPham_LogsImpl.setNguoiSua(getNguoiSua());
		anPham_LogsImpl.setNgaySua(getNgaySua());
		anPham_LogsImpl.setNguoiNhan(getNguoiNhan());
		anPham_LogsImpl.setNguoiXuLy(getNguoiXuLy());
		anPham_LogsImpl.setNgayXuLy(getNgayXuLy());
		anPham_LogsImpl.setLanguage(getLanguage());
		anPham_LogsImpl.setLoaiTin(getLoaiTin());
		anPham_LogsImpl.setIsFormHienBinhLuan(getIsFormHienBinhLuan());
		anPham_LogsImpl.setIsFormViewBinhLuan(getIsFormViewBinhLuan());
		anPham_LogsImpl.setStatus(getStatus());
		anPham_LogsImpl.setOrders(getOrders());
		anPham_LogsImpl.setDelete_status(getDelete_status());

		anPham_LogsImpl.resetOriginalValues();

		return anPham_LogsImpl;
	}

	@Override
	public int compareTo(AnPham_Logs anPham_Logs) {
		int value = 0;

		if (getId() < anPham_Logs.getId()) {
			value = -1;
		}
		else if (getId() > anPham_Logs.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnPham_Logs)) {
			return false;
		}

		AnPham_Logs anPham_Logs = (AnPham_Logs)object;

		long primaryKey = anPham_Logs.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnPham_Logs> toCacheModel() {
		AnPham_LogsCacheModel anPham_LogsCacheModel =
			new AnPham_LogsCacheModel();

		anPham_LogsCacheModel.id = getId();

		anPham_LogsCacheModel.groupId = getGroupId();

		anPham_LogsCacheModel.companyId = getCompanyId();

		anPham_LogsCacheModel.activityId = getActivityId();

		anPham_LogsCacheModel.ten = getTen();

		String ten = anPham_LogsCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			anPham_LogsCacheModel.ten = null;
		}

		anPham_LogsCacheModel.slug = getSlug();

		String slug = anPham_LogsCacheModel.slug;

		if ((slug != null) && (slug.length() == 0)) {
			anPham_LogsCacheModel.slug = null;
		}

		anPham_LogsCacheModel.moTa = getMoTa();

		String moTa = anPham_LogsCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			anPham_LogsCacheModel.moTa = null;
		}

		anPham_LogsCacheModel.anhDaiDien = getAnhDaiDien();

		String anhDaiDien = anPham_LogsCacheModel.anhDaiDien;

		if ((anhDaiDien != null) && (anhDaiDien.length() == 0)) {
			anPham_LogsCacheModel.anhDaiDien = null;
		}

		anPham_LogsCacheModel.loaiId = getLoaiId();

		anPham_LogsCacheModel.deCuongId = getDeCuongId();

		anPham_LogsCacheModel.noiDung = getNoiDung();

		String noiDung = anPham_LogsCacheModel.noiDung;

		if ((noiDung != null) && (noiDung.length() == 0)) {
			anPham_LogsCacheModel.noiDung = null;
		}

		anPham_LogsCacheModel.tuKhoa = getTuKhoa();

		String tuKhoa = anPham_LogsCacheModel.tuKhoa;

		if ((tuKhoa != null) && (tuKhoa.length() == 0)) {
			anPham_LogsCacheModel.tuKhoa = null;
		}

		anPham_LogsCacheModel.phienBan = getPhienBan();

		anPham_LogsCacheModel.luotXem = getLuotXem();

		anPham_LogsCacheModel.anPhamId = getAnPhamId();

		anPham_LogsCacheModel.noiDungLog = getNoiDungLog();

		String noiDungLog = anPham_LogsCacheModel.noiDungLog;

		if ((noiDungLog != null) && (noiDungLog.length() == 0)) {
			anPham_LogsCacheModel.noiDungLog = null;
		}

		anPham_LogsCacheModel.nguoiTao = getNguoiTao();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			anPham_LogsCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			anPham_LogsCacheModel.ngayTao = Long.MIN_VALUE;
		}

		anPham_LogsCacheModel.nguoiSua = getNguoiSua();

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			anPham_LogsCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			anPham_LogsCacheModel.ngaySua = Long.MIN_VALUE;
		}

		anPham_LogsCacheModel.nguoiNhan = getNguoiNhan();

		anPham_LogsCacheModel.nguoiXuLy = getNguoiXuLy();

		Date ngayXuLy = getNgayXuLy();

		if (ngayXuLy != null) {
			anPham_LogsCacheModel.ngayXuLy = ngayXuLy.getTime();
		}
		else {
			anPham_LogsCacheModel.ngayXuLy = Long.MIN_VALUE;
		}

		anPham_LogsCacheModel.language = getLanguage();

		String language = anPham_LogsCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			anPham_LogsCacheModel.language = null;
		}

		anPham_LogsCacheModel.loaiTin = getLoaiTin();

		anPham_LogsCacheModel.isFormHienBinhLuan = getIsFormHienBinhLuan();

		anPham_LogsCacheModel.isFormViewBinhLuan = getIsFormViewBinhLuan();

		anPham_LogsCacheModel.status = getStatus();

		anPham_LogsCacheModel.orders = getOrders();

		anPham_LogsCacheModel.delete_status = getDelete_status();

		return anPham_LogsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnPham_Logs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnPham_Logs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_Logs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AnPham_Logs)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AnPham_Logs, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AnPham_Logs, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnPham_Logs, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AnPham_Logs)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnPham_Logs>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _groupId;
	private long _companyId;
	private long _activityId;
	private String _ten;
	private String _slug;
	private String _moTa;
	private String _anhDaiDien;
	private long _loaiId;
	private long _deCuongId;
	private String _noiDung;
	private String _tuKhoa;
	private long _phienBan;
	private long _luotXem;
	private long _anPhamId;
	private String _noiDungLog;
	private long _nguoiTao;
	private Date _ngayTao;
	private long _nguoiSua;
	private Date _ngaySua;
	private long _nguoiNhan;
	private long _nguoiXuLy;
	private Date _ngayXuLy;
	private String _language;
	private int _loaiTin;
	private int _isFormHienBinhLuan;
	private int _isFormViewBinhLuan;
	private int _status;
	private long _orders;
	private int _delete_status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnPham_Logs, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnPham_Logs)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("activityId", _activityId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("slug", _slug);
		_columnOriginalValues.put("moTa", _moTa);
		_columnOriginalValues.put("anhDaiDien", _anhDaiDien);
		_columnOriginalValues.put("loaiId", _loaiId);
		_columnOriginalValues.put("deCuongId", _deCuongId);
		_columnOriginalValues.put("noiDung", _noiDung);
		_columnOriginalValues.put("tuKhoa", _tuKhoa);
		_columnOriginalValues.put("phienBan", _phienBan);
		_columnOriginalValues.put("luotXem", _luotXem);
		_columnOriginalValues.put("anPhamId", _anPhamId);
		_columnOriginalValues.put("noiDungLog", _noiDungLog);
		_columnOriginalValues.put("nguoiTao", _nguoiTao);
		_columnOriginalValues.put("ngayTao", _ngayTao);
		_columnOriginalValues.put("nguoiSua", _nguoiSua);
		_columnOriginalValues.put("ngaySua", _ngaySua);
		_columnOriginalValues.put("nguoiNhan", _nguoiNhan);
		_columnOriginalValues.put("nguoiXuLy", _nguoiXuLy);
		_columnOriginalValues.put("ngayXuLy", _ngayXuLy);
		_columnOriginalValues.put("language", _language);
		_columnOriginalValues.put("loaiTin", _loaiTin);
		_columnOriginalValues.put("isFormHienBinhLuan", _isFormHienBinhLuan);
		_columnOriginalValues.put("isFormViewBinhLuan", _isFormViewBinhLuan);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("orders", _orders);
		_columnOriginalValues.put("delete_status", _delete_status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("activityId", 8L);

		columnBitmasks.put("ten", 16L);

		columnBitmasks.put("slug", 32L);

		columnBitmasks.put("moTa", 64L);

		columnBitmasks.put("anhDaiDien", 128L);

		columnBitmasks.put("loaiId", 256L);

		columnBitmasks.put("deCuongId", 512L);

		columnBitmasks.put("noiDung", 1024L);

		columnBitmasks.put("tuKhoa", 2048L);

		columnBitmasks.put("phienBan", 4096L);

		columnBitmasks.put("luotXem", 8192L);

		columnBitmasks.put("anPhamId", 16384L);

		columnBitmasks.put("noiDungLog", 32768L);

		columnBitmasks.put("nguoiTao", 65536L);

		columnBitmasks.put("ngayTao", 131072L);

		columnBitmasks.put("nguoiSua", 262144L);

		columnBitmasks.put("ngaySua", 524288L);

		columnBitmasks.put("nguoiNhan", 1048576L);

		columnBitmasks.put("nguoiXuLy", 2097152L);

		columnBitmasks.put("ngayXuLy", 4194304L);

		columnBitmasks.put("language", 8388608L);

		columnBitmasks.put("loaiTin", 16777216L);

		columnBitmasks.put("isFormHienBinhLuan", 33554432L);

		columnBitmasks.put("isFormViewBinhLuan", 67108864L);

		columnBitmasks.put("status", 134217728L);

		columnBitmasks.put("orders", 268435456L);

		columnBitmasks.put("delete_status", 536870912L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnPham_Logs _escapedModel;

}