/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import qlanphamdb.model.eMagazine_BinhLuan;
import qlanphamdb.model.eMagazine_BinhLuanModel;

/**
 * The base model implementation for the eMagazine_BinhLuan service. Represents a row in the &quot;cw_eMagazine_BinhLuan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>eMagazine_BinhLuanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eMagazine_BinhLuanImpl}.
 * </p>
 *
 * @author dnict
 * @see eMagazine_BinhLuanImpl
 * @generated
 */
public class eMagazine_BinhLuanModelImpl
	extends BaseModelImpl<eMagazine_BinhLuan>
	implements eMagazine_BinhLuanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e magazine_ binh luan model instance should use the <code>eMagazine_BinhLuan</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_eMagazine_BinhLuan";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"magazineId", Types.BIGINT},
		{"hoTen", Types.VARCHAR}, {"noiDung", Types.VARCHAR},
		{"ngayBinhLuan", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"orders", Types.INTEGER}, {"delete_status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("magazineId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hoTen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noiDung", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ngayBinhLuan", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("orders", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_eMagazine_BinhLuan (id_ LONG not null primary key,companyId LONG,groupId LONG,magazineId LONG,hoTen VARCHAR(75) null,noiDung VARCHAR(75) null,ngayBinhLuan DATE null,status INTEGER,orders INTEGER,delete_status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_eMagazine_BinhLuan";

	public static final String ORDER_BY_JPQL =
		" ORDER BY eMagazine_BinhLuan.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_eMagazine_BinhLuan.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public eMagazine_BinhLuanModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return eMagazine_BinhLuan.class;
	}

	@Override
	public String getModelClassName() {
		return eMagazine_BinhLuan.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<eMagazine_BinhLuan, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<eMagazine_BinhLuan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine_BinhLuan, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((eMagazine_BinhLuan)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<eMagazine_BinhLuan, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<eMagazine_BinhLuan, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(eMagazine_BinhLuan)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<eMagazine_BinhLuan, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<eMagazine_BinhLuan, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, eMagazine_BinhLuan>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			eMagazine_BinhLuan.class.getClassLoader(), eMagazine_BinhLuan.class,
			ModelWrapper.class);

		try {
			Constructor<eMagazine_BinhLuan> constructor =
				(Constructor<eMagazine_BinhLuan>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<eMagazine_BinhLuan, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<eMagazine_BinhLuan, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<eMagazine_BinhLuan, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<eMagazine_BinhLuan, Object>>();
		Map<String, BiConsumer<eMagazine_BinhLuan, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<eMagazine_BinhLuan, ?>>();

		attributeGetterFunctions.put("id", eMagazine_BinhLuan::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<eMagazine_BinhLuan, Long>)eMagazine_BinhLuan::setId);
		attributeGetterFunctions.put(
			"companyId", eMagazine_BinhLuan::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<eMagazine_BinhLuan, Long>)
				eMagazine_BinhLuan::setCompanyId);
		attributeGetterFunctions.put("groupId", eMagazine_BinhLuan::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<eMagazine_BinhLuan, Long>)
				eMagazine_BinhLuan::setGroupId);
		attributeGetterFunctions.put(
			"magazineId", eMagazine_BinhLuan::getMagazineId);
		attributeSetterBiConsumers.put(
			"magazineId",
			(BiConsumer<eMagazine_BinhLuan, Long>)
				eMagazine_BinhLuan::setMagazineId);
		attributeGetterFunctions.put("hoTen", eMagazine_BinhLuan::getHoTen);
		attributeSetterBiConsumers.put(
			"hoTen",
			(BiConsumer<eMagazine_BinhLuan, String>)
				eMagazine_BinhLuan::setHoTen);
		attributeGetterFunctions.put("noiDung", eMagazine_BinhLuan::getNoiDung);
		attributeSetterBiConsumers.put(
			"noiDung",
			(BiConsumer<eMagazine_BinhLuan, String>)
				eMagazine_BinhLuan::setNoiDung);
		attributeGetterFunctions.put(
			"ngayBinhLuan", eMagazine_BinhLuan::getNgayBinhLuan);
		attributeSetterBiConsumers.put(
			"ngayBinhLuan",
			(BiConsumer<eMagazine_BinhLuan, Date>)
				eMagazine_BinhLuan::setNgayBinhLuan);
		attributeGetterFunctions.put("status", eMagazine_BinhLuan::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<eMagazine_BinhLuan, Integer>)
				eMagazine_BinhLuan::setStatus);
		attributeGetterFunctions.put("orders", eMagazine_BinhLuan::getOrders);
		attributeSetterBiConsumers.put(
			"orders",
			(BiConsumer<eMagazine_BinhLuan, Integer>)
				eMagazine_BinhLuan::setOrders);
		attributeGetterFunctions.put(
			"delete_status", eMagazine_BinhLuan::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<eMagazine_BinhLuan, Integer>)
				eMagazine_BinhLuan::setDelete_status);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getMagazineId() {
		return _magazineId;
	}

	@Override
	public void setMagazineId(long magazineId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_magazineId = magazineId;
	}

	@Override
	public String getHoTen() {
		if (_hoTen == null) {
			return "";
		}
		else {
			return _hoTen;
		}
	}

	@Override
	public void setHoTen(String hoTen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hoTen = hoTen;
	}

	@Override
	public String getNoiDung() {
		if (_noiDung == null) {
			return "";
		}
		else {
			return _noiDung;
		}
	}

	@Override
	public void setNoiDung(String noiDung) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noiDung = noiDung;
	}

	@Override
	public Date getNgayBinhLuan() {
		return _ngayBinhLuan;
	}

	@Override
	public void setNgayBinhLuan(Date ngayBinhLuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayBinhLuan = ngayBinhLuan;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public int getOrders() {
		return _orders;
	}

	@Override
	public void setOrders(int orders) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orders = orders;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), eMagazine_BinhLuan.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public eMagazine_BinhLuan toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, eMagazine_BinhLuan>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		eMagazine_BinhLuanImpl eMagazine_BinhLuanImpl =
			new eMagazine_BinhLuanImpl();

		eMagazine_BinhLuanImpl.setId(getId());
		eMagazine_BinhLuanImpl.setCompanyId(getCompanyId());
		eMagazine_BinhLuanImpl.setGroupId(getGroupId());
		eMagazine_BinhLuanImpl.setMagazineId(getMagazineId());
		eMagazine_BinhLuanImpl.setHoTen(getHoTen());
		eMagazine_BinhLuanImpl.setNoiDung(getNoiDung());
		eMagazine_BinhLuanImpl.setNgayBinhLuan(getNgayBinhLuan());
		eMagazine_BinhLuanImpl.setStatus(getStatus());
		eMagazine_BinhLuanImpl.setOrders(getOrders());
		eMagazine_BinhLuanImpl.setDelete_status(getDelete_status());

		eMagazine_BinhLuanImpl.resetOriginalValues();

		return eMagazine_BinhLuanImpl;
	}

	@Override
	public int compareTo(eMagazine_BinhLuan eMagazine_BinhLuan) {
		long primaryKey = eMagazine_BinhLuan.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof eMagazine_BinhLuan)) {
			return false;
		}

		eMagazine_BinhLuan eMagazine_BinhLuan = (eMagazine_BinhLuan)object;

		long primaryKey = eMagazine_BinhLuan.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<eMagazine_BinhLuan> toCacheModel() {
		eMagazine_BinhLuanCacheModel eMagazine_BinhLuanCacheModel =
			new eMagazine_BinhLuanCacheModel();

		eMagazine_BinhLuanCacheModel.id = getId();

		eMagazine_BinhLuanCacheModel.companyId = getCompanyId();

		eMagazine_BinhLuanCacheModel.groupId = getGroupId();

		eMagazine_BinhLuanCacheModel.magazineId = getMagazineId();

		eMagazine_BinhLuanCacheModel.hoTen = getHoTen();

		String hoTen = eMagazine_BinhLuanCacheModel.hoTen;

		if ((hoTen != null) && (hoTen.length() == 0)) {
			eMagazine_BinhLuanCacheModel.hoTen = null;
		}

		eMagazine_BinhLuanCacheModel.noiDung = getNoiDung();

		String noiDung = eMagazine_BinhLuanCacheModel.noiDung;

		if ((noiDung != null) && (noiDung.length() == 0)) {
			eMagazine_BinhLuanCacheModel.noiDung = null;
		}

		Date ngayBinhLuan = getNgayBinhLuan();

		if (ngayBinhLuan != null) {
			eMagazine_BinhLuanCacheModel.ngayBinhLuan = ngayBinhLuan.getTime();
		}
		else {
			eMagazine_BinhLuanCacheModel.ngayBinhLuan = Long.MIN_VALUE;
		}

		eMagazine_BinhLuanCacheModel.status = getStatus();

		eMagazine_BinhLuanCacheModel.orders = getOrders();

		eMagazine_BinhLuanCacheModel.delete_status = getDelete_status();

		return eMagazine_BinhLuanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<eMagazine_BinhLuan, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<eMagazine_BinhLuan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine_BinhLuan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(eMagazine_BinhLuan)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<eMagazine_BinhLuan, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<eMagazine_BinhLuan, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine_BinhLuan, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((eMagazine_BinhLuan)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, eMagazine_BinhLuan>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private long _magazineId;
	private String _hoTen;
	private String _noiDung;
	private Date _ngayBinhLuan;
	private int _status;
	private int _orders;
	private int _delete_status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<eMagazine_BinhLuan, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((eMagazine_BinhLuan)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("magazineId", _magazineId);
		_columnOriginalValues.put("hoTen", _hoTen);
		_columnOriginalValues.put("noiDung", _noiDung);
		_columnOriginalValues.put("ngayBinhLuan", _ngayBinhLuan);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("orders", _orders);
		_columnOriginalValues.put("delete_status", _delete_status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("magazineId", 8L);

		columnBitmasks.put("hoTen", 16L);

		columnBitmasks.put("noiDung", 32L);

		columnBitmasks.put("ngayBinhLuan", 64L);

		columnBitmasks.put("status", 128L);

		columnBitmasks.put("orders", 256L);

		columnBitmasks.put("delete_status", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private eMagazine_BinhLuan _escapedModel;

}