/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import qlanphamdb.model.eMagazine;
import qlanphamdb.model.eMagazineModel;

/**
 * The base model implementation for the eMagazine service. Represents a row in the &quot;cw_eMagazine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>eMagazineModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eMagazineImpl}.
 * </p>
 *
 * @author dnict
 * @see eMagazineImpl
 * @generated
 */
public class eMagazineModelImpl
	extends BaseModelImpl<eMagazine> implements eMagazineModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e magazine model instance should use the <code>eMagazine</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_eMagazine";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"ten", Types.VARCHAR},
		{"slug", Types.VARCHAR}, {"moTa", Types.VARCHAR},
		{"anhDaiDien", Types.VARCHAR}, {"mauChuDao", Types.VARCHAR},
		{"hinhNen", Types.VARCHAR}, {"templateId", Types.BIGINT},
		{"noiDung", Types.VARCHAR}, {"tuKhoa", Types.VARCHAR},
		{"phienBan", Types.BIGINT}, {"luotXem", Types.BIGINT},
		{"nguoiTao", Types.BIGINT}, {"ngayTao", Types.TIMESTAMP},
		{"nguoiSua", Types.BIGINT}, {"ngaySua", Types.TIMESTAMP},
		{"nguoiNhan", Types.BIGINT}, {"nguoiXuLy", Types.BIGINT},
		{"ngayXuLy", Types.TIMESTAMP}, {"language", Types.VARCHAR},
		{"isFormHienBinhLuan", Types.INTEGER},
		{"isFormViewBinhLuan", Types.INTEGER}, {"status", Types.INTEGER},
		{"orders", Types.BIGINT}, {"delete_status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("slug", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("moTa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anhDaiDien", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mauChuDao", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hinhNen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("templateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("noiDung", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tuKhoa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phienBan", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("luotXem", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoiTao", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayTao", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nguoiSua", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngaySua", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nguoiNhan", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoiXuLy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ngayXuLy", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isFormHienBinhLuan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isFormViewBinhLuan", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("orders", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("delete_status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_eMagazine (id_ LONG not null primary key,groupId LONG,companyId LONG,ten VARCHAR(75) null,slug VARCHAR(75) null,moTa VARCHAR(75) null,anhDaiDien VARCHAR(75) null,mauChuDao VARCHAR(75) null,hinhNen VARCHAR(75) null,templateId LONG,noiDung VARCHAR(75) null,tuKhoa VARCHAR(75) null,phienBan LONG,luotXem LONG,nguoiTao LONG,ngayTao DATE null,nguoiSua LONG,ngaySua DATE null,nguoiNhan LONG,nguoiXuLy LONG,ngayXuLy DATE null,language VARCHAR(75) null,isFormHienBinhLuan INTEGER,isFormViewBinhLuan INTEGER,status INTEGER,orders LONG,delete_status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table cw_eMagazine";

	public static final String ORDER_BY_JPQL = " ORDER BY eMagazine.id DESC";

	public static final String ORDER_BY_SQL = " ORDER BY cw_eMagazine.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public eMagazineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return eMagazine.class;
	}

	@Override
	public String getModelClassName() {
		return eMagazine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<eMagazine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<eMagazine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((eMagazine)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<eMagazine, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<eMagazine, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(eMagazine)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<eMagazine, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<eMagazine, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, eMagazine>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			eMagazine.class.getClassLoader(), eMagazine.class,
			ModelWrapper.class);

		try {
			Constructor<eMagazine> constructor =
				(Constructor<eMagazine>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<eMagazine, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<eMagazine, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<eMagazine, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<eMagazine, Object>>();
		Map<String, BiConsumer<eMagazine, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<eMagazine, ?>>();

		attributeGetterFunctions.put("id", eMagazine::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<eMagazine, Long>)eMagazine::setId);
		attributeGetterFunctions.put("groupId", eMagazine::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<eMagazine, Long>)eMagazine::setGroupId);
		attributeGetterFunctions.put("companyId", eMagazine::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<eMagazine, Long>)eMagazine::setCompanyId);
		attributeGetterFunctions.put("ten", eMagazine::getTen);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<eMagazine, String>)eMagazine::setTen);
		attributeGetterFunctions.put("slug", eMagazine::getSlug);
		attributeSetterBiConsumers.put(
			"slug", (BiConsumer<eMagazine, String>)eMagazine::setSlug);
		attributeGetterFunctions.put("moTa", eMagazine::getMoTa);
		attributeSetterBiConsumers.put(
			"moTa", (BiConsumer<eMagazine, String>)eMagazine::setMoTa);
		attributeGetterFunctions.put("anhDaiDien", eMagazine::getAnhDaiDien);
		attributeSetterBiConsumers.put(
			"anhDaiDien",
			(BiConsumer<eMagazine, String>)eMagazine::setAnhDaiDien);
		attributeGetterFunctions.put("mauChuDao", eMagazine::getMauChuDao);
		attributeSetterBiConsumers.put(
			"mauChuDao",
			(BiConsumer<eMagazine, String>)eMagazine::setMauChuDao);
		attributeGetterFunctions.put("hinhNen", eMagazine::getHinhNen);
		attributeSetterBiConsumers.put(
			"hinhNen", (BiConsumer<eMagazine, String>)eMagazine::setHinhNen);
		attributeGetterFunctions.put("templateId", eMagazine::getTemplateId);
		attributeSetterBiConsumers.put(
			"templateId",
			(BiConsumer<eMagazine, Long>)eMagazine::setTemplateId);
		attributeGetterFunctions.put("noiDung", eMagazine::getNoiDung);
		attributeSetterBiConsumers.put(
			"noiDung", (BiConsumer<eMagazine, String>)eMagazine::setNoiDung);
		attributeGetterFunctions.put("tuKhoa", eMagazine::getTuKhoa);
		attributeSetterBiConsumers.put(
			"tuKhoa", (BiConsumer<eMagazine, String>)eMagazine::setTuKhoa);
		attributeGetterFunctions.put("phienBan", eMagazine::getPhienBan);
		attributeSetterBiConsumers.put(
			"phienBan", (BiConsumer<eMagazine, Long>)eMagazine::setPhienBan);
		attributeGetterFunctions.put("luotXem", eMagazine::getLuotXem);
		attributeSetterBiConsumers.put(
			"luotXem", (BiConsumer<eMagazine, Long>)eMagazine::setLuotXem);
		attributeGetterFunctions.put("nguoiTao", eMagazine::getNguoiTao);
		attributeSetterBiConsumers.put(
			"nguoiTao", (BiConsumer<eMagazine, Long>)eMagazine::setNguoiTao);
		attributeGetterFunctions.put("ngayTao", eMagazine::getNgayTao);
		attributeSetterBiConsumers.put(
			"ngayTao", (BiConsumer<eMagazine, Date>)eMagazine::setNgayTao);
		attributeGetterFunctions.put("nguoiSua", eMagazine::getNguoiSua);
		attributeSetterBiConsumers.put(
			"nguoiSua", (BiConsumer<eMagazine, Long>)eMagazine::setNguoiSua);
		attributeGetterFunctions.put("ngaySua", eMagazine::getNgaySua);
		attributeSetterBiConsumers.put(
			"ngaySua", (BiConsumer<eMagazine, Date>)eMagazine::setNgaySua);
		attributeGetterFunctions.put("nguoiNhan", eMagazine::getNguoiNhan);
		attributeSetterBiConsumers.put(
			"nguoiNhan", (BiConsumer<eMagazine, Long>)eMagazine::setNguoiNhan);
		attributeGetterFunctions.put("nguoiXuLy", eMagazine::getNguoiXuLy);
		attributeSetterBiConsumers.put(
			"nguoiXuLy", (BiConsumer<eMagazine, Long>)eMagazine::setNguoiXuLy);
		attributeGetterFunctions.put("ngayXuLy", eMagazine::getNgayXuLy);
		attributeSetterBiConsumers.put(
			"ngayXuLy", (BiConsumer<eMagazine, Date>)eMagazine::setNgayXuLy);
		attributeGetterFunctions.put("language", eMagazine::getLanguage);
		attributeSetterBiConsumers.put(
			"language", (BiConsumer<eMagazine, String>)eMagazine::setLanguage);
		attributeGetterFunctions.put(
			"isFormHienBinhLuan", eMagazine::getIsFormHienBinhLuan);
		attributeSetterBiConsumers.put(
			"isFormHienBinhLuan",
			(BiConsumer<eMagazine, Integer>)eMagazine::setIsFormHienBinhLuan);
		attributeGetterFunctions.put(
			"isFormViewBinhLuan", eMagazine::getIsFormViewBinhLuan);
		attributeSetterBiConsumers.put(
			"isFormViewBinhLuan",
			(BiConsumer<eMagazine, Integer>)eMagazine::setIsFormViewBinhLuan);
		attributeGetterFunctions.put("status", eMagazine::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<eMagazine, Integer>)eMagazine::setStatus);
		attributeGetterFunctions.put("orders", eMagazine::getOrders);
		attributeSetterBiConsumers.put(
			"orders", (BiConsumer<eMagazine, Long>)eMagazine::setOrders);
		attributeGetterFunctions.put(
			"delete_status", eMagazine::getDelete_status);
		attributeSetterBiConsumers.put(
			"delete_status",
			(BiConsumer<eMagazine, Integer>)eMagazine::setDelete_status);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@Override
	public String getSlug() {
		if (_slug == null) {
			return "";
		}
		else {
			return _slug;
		}
	}

	@Override
	public void setSlug(String slug) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_slug = slug;
	}

	@Override
	public String getMoTa() {
		if (_moTa == null) {
			return "";
		}
		else {
			return _moTa;
		}
	}

	@Override
	public void setMoTa(String moTa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_moTa = moTa;
	}

	@Override
	public String getAnhDaiDien() {
		if (_anhDaiDien == null) {
			return "";
		}
		else {
			return _anhDaiDien;
		}
	}

	@Override
	public void setAnhDaiDien(String anhDaiDien) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anhDaiDien = anhDaiDien;
	}

	@Override
	public String getMauChuDao() {
		if (_mauChuDao == null) {
			return "";
		}
		else {
			return _mauChuDao;
		}
	}

	@Override
	public void setMauChuDao(String mauChuDao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mauChuDao = mauChuDao;
	}

	@Override
	public String getHinhNen() {
		if (_hinhNen == null) {
			return "";
		}
		else {
			return _hinhNen;
		}
	}

	@Override
	public void setHinhNen(String hinhNen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hinhNen = hinhNen;
	}

	@Override
	public long getTemplateId() {
		return _templateId;
	}

	@Override
	public void setTemplateId(long templateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_templateId = templateId;
	}

	@Override
	public String getNoiDung() {
		if (_noiDung == null) {
			return "";
		}
		else {
			return _noiDung;
		}
	}

	@Override
	public void setNoiDung(String noiDung) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noiDung = noiDung;
	}

	@Override
	public String getTuKhoa() {
		if (_tuKhoa == null) {
			return "";
		}
		else {
			return _tuKhoa;
		}
	}

	@Override
	public void setTuKhoa(String tuKhoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tuKhoa = tuKhoa;
	}

	@Override
	public long getPhienBan() {
		return _phienBan;
	}

	@Override
	public void setPhienBan(long phienBan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phienBan = phienBan;
	}

	@Override
	public long getLuotXem() {
		return _luotXem;
	}

	@Override
	public void setLuotXem(long luotXem) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_luotXem = luotXem;
	}

	@Override
	public long getNguoiTao() {
		return _nguoiTao;
	}

	@Override
	public void setNguoiTao(long nguoiTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiTao = nguoiTao;
	}

	@Override
	public Date getNgayTao() {
		return _ngayTao;
	}

	@Override
	public void setNgayTao(Date ngayTao) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayTao = ngayTao;
	}

	@Override
	public long getNguoiSua() {
		return _nguoiSua;
	}

	@Override
	public void setNguoiSua(long nguoiSua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiSua = nguoiSua;
	}

	@Override
	public Date getNgaySua() {
		return _ngaySua;
	}

	@Override
	public void setNgaySua(Date ngaySua) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngaySua = ngaySua;
	}

	@Override
	public long getNguoiNhan() {
		return _nguoiNhan;
	}

	@Override
	public void setNguoiNhan(long nguoiNhan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiNhan = nguoiNhan;
	}

	@Override
	public long getNguoiXuLy() {
		return _nguoiXuLy;
	}

	@Override
	public void setNguoiXuLy(long nguoiXuLy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiXuLy = nguoiXuLy;
	}

	@Override
	public Date getNgayXuLy() {
		return _ngayXuLy;
	}

	@Override
	public void setNgayXuLy(Date ngayXuLy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngayXuLy = ngayXuLy;
	}

	@Override
	public String getLanguage() {
		if (_language == null) {
			return "";
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_language = language;
	}

	@Override
	public int getIsFormHienBinhLuan() {
		return _isFormHienBinhLuan;
	}

	@Override
	public void setIsFormHienBinhLuan(int isFormHienBinhLuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFormHienBinhLuan = isFormHienBinhLuan;
	}

	@Override
	public int getIsFormViewBinhLuan() {
		return _isFormViewBinhLuan;
	}

	@Override
	public void setIsFormViewBinhLuan(int isFormViewBinhLuan) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isFormViewBinhLuan = isFormViewBinhLuan;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@Override
	public long getOrders() {
		return _orders;
	}

	@Override
	public void setOrders(long orders) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_orders = orders;
	}

	@Override
	public int getDelete_status() {
		return _delete_status;
	}

	@Override
	public void setDelete_status(int delete_status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_delete_status = delete_status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), eMagazine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public eMagazine toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, eMagazine>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		eMagazineImpl eMagazineImpl = new eMagazineImpl();

		eMagazineImpl.setId(getId());
		eMagazineImpl.setGroupId(getGroupId());
		eMagazineImpl.setCompanyId(getCompanyId());
		eMagazineImpl.setTen(getTen());
		eMagazineImpl.setSlug(getSlug());
		eMagazineImpl.setMoTa(getMoTa());
		eMagazineImpl.setAnhDaiDien(getAnhDaiDien());
		eMagazineImpl.setMauChuDao(getMauChuDao());
		eMagazineImpl.setHinhNen(getHinhNen());
		eMagazineImpl.setTemplateId(getTemplateId());
		eMagazineImpl.setNoiDung(getNoiDung());
		eMagazineImpl.setTuKhoa(getTuKhoa());
		eMagazineImpl.setPhienBan(getPhienBan());
		eMagazineImpl.setLuotXem(getLuotXem());
		eMagazineImpl.setNguoiTao(getNguoiTao());
		eMagazineImpl.setNgayTao(getNgayTao());
		eMagazineImpl.setNguoiSua(getNguoiSua());
		eMagazineImpl.setNgaySua(getNgaySua());
		eMagazineImpl.setNguoiNhan(getNguoiNhan());
		eMagazineImpl.setNguoiXuLy(getNguoiXuLy());
		eMagazineImpl.setNgayXuLy(getNgayXuLy());
		eMagazineImpl.setLanguage(getLanguage());
		eMagazineImpl.setIsFormHienBinhLuan(getIsFormHienBinhLuan());
		eMagazineImpl.setIsFormViewBinhLuan(getIsFormViewBinhLuan());
		eMagazineImpl.setStatus(getStatus());
		eMagazineImpl.setOrders(getOrders());
		eMagazineImpl.setDelete_status(getDelete_status());

		eMagazineImpl.resetOriginalValues();

		return eMagazineImpl;
	}

	@Override
	public int compareTo(eMagazine eMagazine) {
		int value = 0;

		if (getId() < eMagazine.getId()) {
			value = -1;
		}
		else if (getId() > eMagazine.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof eMagazine)) {
			return false;
		}

		eMagazine eMagazine = (eMagazine)object;

		long primaryKey = eMagazine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<eMagazine> toCacheModel() {
		eMagazineCacheModel eMagazineCacheModel = new eMagazineCacheModel();

		eMagazineCacheModel.id = getId();

		eMagazineCacheModel.groupId = getGroupId();

		eMagazineCacheModel.companyId = getCompanyId();

		eMagazineCacheModel.ten = getTen();

		String ten = eMagazineCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			eMagazineCacheModel.ten = null;
		}

		eMagazineCacheModel.slug = getSlug();

		String slug = eMagazineCacheModel.slug;

		if ((slug != null) && (slug.length() == 0)) {
			eMagazineCacheModel.slug = null;
		}

		eMagazineCacheModel.moTa = getMoTa();

		String moTa = eMagazineCacheModel.moTa;

		if ((moTa != null) && (moTa.length() == 0)) {
			eMagazineCacheModel.moTa = null;
		}

		eMagazineCacheModel.anhDaiDien = getAnhDaiDien();

		String anhDaiDien = eMagazineCacheModel.anhDaiDien;

		if ((anhDaiDien != null) && (anhDaiDien.length() == 0)) {
			eMagazineCacheModel.anhDaiDien = null;
		}

		eMagazineCacheModel.mauChuDao = getMauChuDao();

		String mauChuDao = eMagazineCacheModel.mauChuDao;

		if ((mauChuDao != null) && (mauChuDao.length() == 0)) {
			eMagazineCacheModel.mauChuDao = null;
		}

		eMagazineCacheModel.hinhNen = getHinhNen();

		String hinhNen = eMagazineCacheModel.hinhNen;

		if ((hinhNen != null) && (hinhNen.length() == 0)) {
			eMagazineCacheModel.hinhNen = null;
		}

		eMagazineCacheModel.templateId = getTemplateId();

		eMagazineCacheModel.noiDung = getNoiDung();

		String noiDung = eMagazineCacheModel.noiDung;

		if ((noiDung != null) && (noiDung.length() == 0)) {
			eMagazineCacheModel.noiDung = null;
		}

		eMagazineCacheModel.tuKhoa = getTuKhoa();

		String tuKhoa = eMagazineCacheModel.tuKhoa;

		if ((tuKhoa != null) && (tuKhoa.length() == 0)) {
			eMagazineCacheModel.tuKhoa = null;
		}

		eMagazineCacheModel.phienBan = getPhienBan();

		eMagazineCacheModel.luotXem = getLuotXem();

		eMagazineCacheModel.nguoiTao = getNguoiTao();

		Date ngayTao = getNgayTao();

		if (ngayTao != null) {
			eMagazineCacheModel.ngayTao = ngayTao.getTime();
		}
		else {
			eMagazineCacheModel.ngayTao = Long.MIN_VALUE;
		}

		eMagazineCacheModel.nguoiSua = getNguoiSua();

		Date ngaySua = getNgaySua();

		if (ngaySua != null) {
			eMagazineCacheModel.ngaySua = ngaySua.getTime();
		}
		else {
			eMagazineCacheModel.ngaySua = Long.MIN_VALUE;
		}

		eMagazineCacheModel.nguoiNhan = getNguoiNhan();

		eMagazineCacheModel.nguoiXuLy = getNguoiXuLy();

		Date ngayXuLy = getNgayXuLy();

		if (ngayXuLy != null) {
			eMagazineCacheModel.ngayXuLy = ngayXuLy.getTime();
		}
		else {
			eMagazineCacheModel.ngayXuLy = Long.MIN_VALUE;
		}

		eMagazineCacheModel.language = getLanguage();

		String language = eMagazineCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			eMagazineCacheModel.language = null;
		}

		eMagazineCacheModel.isFormHienBinhLuan = getIsFormHienBinhLuan();

		eMagazineCacheModel.isFormViewBinhLuan = getIsFormViewBinhLuan();

		eMagazineCacheModel.status = getStatus();

		eMagazineCacheModel.orders = getOrders();

		eMagazineCacheModel.delete_status = getDelete_status();

		return eMagazineCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<eMagazine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<eMagazine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((eMagazine)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<eMagazine, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<eMagazine, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<eMagazine, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((eMagazine)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, eMagazine>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _groupId;
	private long _companyId;
	private String _ten;
	private String _slug;
	private String _moTa;
	private String _anhDaiDien;
	private String _mauChuDao;
	private String _hinhNen;
	private long _templateId;
	private String _noiDung;
	private String _tuKhoa;
	private long _phienBan;
	private long _luotXem;
	private long _nguoiTao;
	private Date _ngayTao;
	private long _nguoiSua;
	private Date _ngaySua;
	private long _nguoiNhan;
	private long _nguoiXuLy;
	private Date _ngayXuLy;
	private String _language;
	private int _isFormHienBinhLuan;
	private int _isFormViewBinhLuan;
	private int _status;
	private long _orders;
	private int _delete_status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<eMagazine, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((eMagazine)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("slug", _slug);
		_columnOriginalValues.put("moTa", _moTa);
		_columnOriginalValues.put("anhDaiDien", _anhDaiDien);
		_columnOriginalValues.put("mauChuDao", _mauChuDao);
		_columnOriginalValues.put("hinhNen", _hinhNen);
		_columnOriginalValues.put("templateId", _templateId);
		_columnOriginalValues.put("noiDung", _noiDung);
		_columnOriginalValues.put("tuKhoa", _tuKhoa);
		_columnOriginalValues.put("phienBan", _phienBan);
		_columnOriginalValues.put("luotXem", _luotXem);
		_columnOriginalValues.put("nguoiTao", _nguoiTao);
		_columnOriginalValues.put("ngayTao", _ngayTao);
		_columnOriginalValues.put("nguoiSua", _nguoiSua);
		_columnOriginalValues.put("ngaySua", _ngaySua);
		_columnOriginalValues.put("nguoiNhan", _nguoiNhan);
		_columnOriginalValues.put("nguoiXuLy", _nguoiXuLy);
		_columnOriginalValues.put("ngayXuLy", _ngayXuLy);
		_columnOriginalValues.put("language", _language);
		_columnOriginalValues.put("isFormHienBinhLuan", _isFormHienBinhLuan);
		_columnOriginalValues.put("isFormViewBinhLuan", _isFormViewBinhLuan);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("orders", _orders);
		_columnOriginalValues.put("delete_status", _delete_status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("ten", 8L);

		columnBitmasks.put("slug", 16L);

		columnBitmasks.put("moTa", 32L);

		columnBitmasks.put("anhDaiDien", 64L);

		columnBitmasks.put("mauChuDao", 128L);

		columnBitmasks.put("hinhNen", 256L);

		columnBitmasks.put("templateId", 512L);

		columnBitmasks.put("noiDung", 1024L);

		columnBitmasks.put("tuKhoa", 2048L);

		columnBitmasks.put("phienBan", 4096L);

		columnBitmasks.put("luotXem", 8192L);

		columnBitmasks.put("nguoiTao", 16384L);

		columnBitmasks.put("ngayTao", 32768L);

		columnBitmasks.put("nguoiSua", 65536L);

		columnBitmasks.put("ngaySua", 131072L);

		columnBitmasks.put("nguoiNhan", 262144L);

		columnBitmasks.put("nguoiXuLy", 524288L);

		columnBitmasks.put("ngayXuLy", 1048576L);

		columnBitmasks.put("language", 2097152L);

		columnBitmasks.put("isFormHienBinhLuan", 4194304L);

		columnBitmasks.put("isFormViewBinhLuan", 8388608L);

		columnBitmasks.put("status", 16777216L);

		columnBitmasks.put("orders", 33554432L);

		columnBitmasks.put("delete_status", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private eMagazine _escapedModel;

}