/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package qlanphamdb.model.impl;

import qlanphamdb.model.eMagazine_template;

import qlanphamdb.service.eMagazine_templateLocalServiceUtil;

/**
 * The extended model base implementation for the eMagazine_template service. Represents a row in the &quot;cw_eMagazine_template&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eMagazine_templateImpl}.
 * </p>
 *
 * @author dnict
 * @see eMagazine_templateImpl
 * @see eMagazine_template
 * @generated
 */
public abstract class eMagazine_templateBaseImpl
	extends eMagazine_templateModelImpl implements eMagazine_template {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e magazine_template model instance should use the <code>eMagazine_template</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			eMagazine_templateLocalServiceUtil.addeMagazine_template(this);
		}
		else {
			eMagazine_templateLocalServiceUtil.updateeMagazine_template(this);
		}
	}

}