/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlquangcao.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ViTriDanhMuc service. Represents a row in the &quot;cw_quangcao_vitridanhmuc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>vn.dnict.qlquangcao.model.impl.ViTriDanhMucModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>vn.dnict.qlquangcao.model.impl.ViTriDanhMucImpl</code>.
 * </p>
 *
 * @author dnict
 * @see ViTriDanhMuc
 * @generated
 */
@ProviderType
public interface ViTriDanhMucModel
	extends BaseModel<ViTriDanhMuc>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vi tri danh muc model instance should use the {@link ViTriDanhMuc} interface instead.
	 */

	/**
	 * Returns the primary key of this vi tri danh muc.
	 *
	 * @return the primary key of this vi tri danh muc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vi tri danh muc.
	 *
	 * @param primaryKey the primary key of this vi tri danh muc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vi tri danh muc.
	 *
	 * @return the ID of this vi tri danh muc
	 */
	public long getId();

	/**
	 * Sets the ID of this vi tri danh muc.
	 *
	 * @param id the ID of this vi tri danh muc
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this vi tri danh muc.
	 *
	 * @return the company ID of this vi tri danh muc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vi tri danh muc.
	 *
	 * @param companyId the company ID of this vi tri danh muc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this vi tri danh muc.
	 *
	 * @return the group ID of this vi tri danh muc
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this vi tri danh muc.
	 *
	 * @param groupId the group ID of this vi tri danh muc
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the nguoitao of this vi tri danh muc.
	 *
	 * @return the nguoitao of this vi tri danh muc
	 */
	public long getNguoitao();

	/**
	 * Sets the nguoitao of this vi tri danh muc.
	 *
	 * @param nguoitao the nguoitao of this vi tri danh muc
	 */
	public void setNguoitao(long nguoitao);

	/**
	 * Returns the ten of this vi tri danh muc.
	 *
	 * @return the ten of this vi tri danh muc
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this vi tri danh muc.
	 *
	 * @param ten the ten of this vi tri danh muc
	 */
	public void setTen(String ten);

	/**
	 * Returns the css class of this vi tri danh muc.
	 *
	 * @return the css class of this vi tri danh muc
	 */
	@AutoEscape
	public String getCssClass();

	/**
	 * Sets the css class of this vi tri danh muc.
	 *
	 * @param cssClass the css class of this vi tri danh muc
	 */
	public void setCssClass(String cssClass);

	/**
	 * Returns the kichthuoc of this vi tri danh muc.
	 *
	 * @return the kichthuoc of this vi tri danh muc
	 */
	@AutoEscape
	public String getKichthuoc();

	/**
	 * Sets the kichthuoc of this vi tri danh muc.
	 *
	 * @param kichthuoc the kichthuoc of this vi tri danh muc
	 */
	public void setKichthuoc(String kichthuoc);

	/**
	 * Returns the ngaytao of this vi tri danh muc.
	 *
	 * @return the ngaytao of this vi tri danh muc
	 */
	public Date getNgaytao();

	/**
	 * Sets the ngaytao of this vi tri danh muc.
	 *
	 * @param ngaytao the ngaytao of this vi tri danh muc
	 */
	public void setNgaytao(Date ngaytao);

	/**
	 * Returns the daxoa of this vi tri danh muc.
	 *
	 * @return the daxoa of this vi tri danh muc
	 */
	public int getDaxoa();

	/**
	 * Sets the daxoa of this vi tri danh muc.
	 *
	 * @param daxoa the daxoa of this vi tri danh muc
	 */
	public void setDaxoa(int daxoa);

	/**
	 * Returns the trangthai of this vi tri danh muc.
	 *
	 * @return the trangthai of this vi tri danh muc
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this vi tri danh muc.
	 *
	 * @param trangthai the trangthai of this vi tri danh muc
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the ngaysua of this vi tri danh muc.
	 *
	 * @return the ngaysua of this vi tri danh muc
	 */
	public Date getNgaysua();

	/**
	 * Sets the ngaysua of this vi tri danh muc.
	 *
	 * @param ngaysua the ngaysua of this vi tri danh muc
	 */
	public void setNgaysua(Date ngaysua);

}