/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlgopy.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlgopy.model.emailTemplate;
import vn.dnict.qlgopy.model.emailTemplateModel;
import vn.dnict.qlgopy.model.emailTemplateSoap;

/**
 * The base model implementation for the emailTemplate service. Represents a row in the &quot;cw_gopy_emailTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>emailTemplateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link emailTemplateImpl}.
 * </p>
 *
 * @author dnict
 * @see emailTemplateImpl
 * @generated
 */
@JSON(strict = true)
public class emailTemplateModelImpl
	extends BaseModelImpl<emailTemplate> implements emailTemplateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email template model instance should use the <code>emailTemplate</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_gopy_emailTemplate";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"ten", Types.VARCHAR},
		{"noidung", Types.VARCHAR}, {"loai", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noidung", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loai", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_gopy_emailTemplate (id_ LONG not null primary key,companyId LONG,groupId LONG,ten VARCHAR(75) null,noidung VARCHAR(75) null,loai INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_gopy_emailTemplate";

	public static final String ORDER_BY_JPQL = " ORDER BY emailTemplate.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_gopy_emailTemplate.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOAI_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static emailTemplate toModel(emailTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		emailTemplate model = new emailTemplateImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setTen(soapModel.getTen());
		model.setNoidung(soapModel.getNoidung());
		model.setLoai(soapModel.getLoai());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<emailTemplate> toModels(emailTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<emailTemplate> models = new ArrayList<emailTemplate>(
			soapModels.length);

		for (emailTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public emailTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return emailTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return emailTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<emailTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<emailTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emailTemplate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((emailTemplate)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<emailTemplate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<emailTemplate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(emailTemplate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<emailTemplate, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<emailTemplate, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<emailTemplate, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<emailTemplate, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<emailTemplate, Object>>();

		attributeGetterFunctions.put("id", emailTemplate::getId);
		attributeGetterFunctions.put("companyId", emailTemplate::getCompanyId);
		attributeGetterFunctions.put("groupId", emailTemplate::getGroupId);
		attributeGetterFunctions.put("ten", emailTemplate::getTen);
		attributeGetterFunctions.put("noidung", emailTemplate::getNoidung);
		attributeGetterFunctions.put("loai", emailTemplate::getLoai);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<emailTemplate, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<emailTemplate, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<emailTemplate, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<emailTemplate, Long>)emailTemplate::setId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<emailTemplate, Long>)emailTemplate::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<emailTemplate, Long>)emailTemplate::setGroupId);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<emailTemplate, String>)emailTemplate::setTen);
		attributeSetterBiConsumers.put(
			"noidung",
			(BiConsumer<emailTemplate, String>)emailTemplate::setNoidung);
		attributeSetterBiConsumers.put(
			"loai", (BiConsumer<emailTemplate, Integer>)emailTemplate::setLoai);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@JSON
	@Override
	public String getNoidung() {
		if (_noidung == null) {
			return "";
		}
		else {
			return _noidung;
		}
	}

	@Override
	public void setNoidung(String noidung) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noidung = noidung;
	}

	@JSON
	@Override
	public int getLoai() {
		return _loai;
	}

	@Override
	public void setLoai(int loai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_loai = loai;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalLoai() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("loai"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), emailTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public emailTemplate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, emailTemplate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		emailTemplateImpl emailTemplateImpl = new emailTemplateImpl();

		emailTemplateImpl.setId(getId());
		emailTemplateImpl.setCompanyId(getCompanyId());
		emailTemplateImpl.setGroupId(getGroupId());
		emailTemplateImpl.setTen(getTen());
		emailTemplateImpl.setNoidung(getNoidung());
		emailTemplateImpl.setLoai(getLoai());

		emailTemplateImpl.resetOriginalValues();

		return emailTemplateImpl;
	}

	@Override
	public int compareTo(emailTemplate emailTemplate) {
		long primaryKey = emailTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof emailTemplate)) {
			return false;
		}

		emailTemplate emailTemplate = (emailTemplate)object;

		long primaryKey = emailTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<emailTemplate> toCacheModel() {
		emailTemplateCacheModel emailTemplateCacheModel =
			new emailTemplateCacheModel();

		emailTemplateCacheModel.id = getId();

		emailTemplateCacheModel.companyId = getCompanyId();

		emailTemplateCacheModel.groupId = getGroupId();

		emailTemplateCacheModel.ten = getTen();

		String ten = emailTemplateCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			emailTemplateCacheModel.ten = null;
		}

		emailTemplateCacheModel.noidung = getNoidung();

		String noidung = emailTemplateCacheModel.noidung;

		if ((noidung != null) && (noidung.length() == 0)) {
			emailTemplateCacheModel.noidung = null;
		}

		emailTemplateCacheModel.loai = getLoai();

		return emailTemplateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<emailTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<emailTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emailTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((emailTemplate)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<emailTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<emailTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<emailTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((emailTemplate)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, emailTemplate>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					emailTemplate.class, ModelWrapper.class);

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private String _ten;
	private String _noidung;
	private int _loai;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<emailTemplate, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((emailTemplate)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("noidung", _noidung);
		_columnOriginalValues.put("loai", _loai);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("ten", 8L);

		columnBitmasks.put("noidung", 16L);

		columnBitmasks.put("loai", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private emailTemplate _escapedModel;

}