/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package vn.dnict.qlgopy.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.qlgopy.model.GopY_DinhKem;
import vn.dnict.qlgopy.model.GopY_DinhKemModel;
import vn.dnict.qlgopy.model.GopY_DinhKemSoap;

/**
 * The base model implementation for the GopY_DinhKem service. Represents a row in the &quot;cw_gopy_dinhkemfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GopY_DinhKemModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GopY_DinhKemImpl}.
 * </p>
 *
 * @author dnict
 * @see GopY_DinhKemImpl
 * @generated
 */
@JSON(strict = true)
public class GopY_DinhKemModelImpl
	extends BaseModelImpl<GopY_DinhKem> implements GopY_DinhKemModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a gop y_ dinh kem model instance should use the <code>GopY_DinhKem</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_gopy_dinhkemfile";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"ten", Types.VARCHAR}, {"url", Types.VARCHAR},
		{"Object", Types.BIGINT}, {"ObjectId", Types.BIGINT},
		{"ghichu", Types.VARCHAR}, {"daxoa", Types.INTEGER},
		{"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Object", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ObjectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ghichu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("daxoa", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_gopy_dinhkemfile (id_ LONG not null primary key,companyId LONG,groupId LONG,userId LONG,ten VARCHAR(75) null,url VARCHAR(75) null,Object LONG,ObjectId LONG,ghichu VARCHAR(75) null,daxoa INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table cw_gopy_dinhkemfile";

	public static final String ORDER_BY_JPQL = " ORDER BY gopY_DinhKem.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_gopy_dinhkemfile.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static GopY_DinhKem toModel(GopY_DinhKemSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		GopY_DinhKem model = new GopY_DinhKemImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setTen(soapModel.getTen());
		model.setUrl(soapModel.getUrl());
		model.setObject(soapModel.getObject());
		model.setObjectId(soapModel.getObjectId());
		model.setGhichu(soapModel.getGhichu());
		model.setDaxoa(soapModel.getDaxoa());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<GopY_DinhKem> toModels(GopY_DinhKemSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<GopY_DinhKem> models = new ArrayList<GopY_DinhKem>(
			soapModels.length);

		for (GopY_DinhKemSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public GopY_DinhKemModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GopY_DinhKem.class;
	}

	@Override
	public String getModelClassName() {
		return GopY_DinhKem.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GopY_DinhKem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GopY_DinhKem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GopY_DinhKem, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GopY_DinhKem)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GopY_DinhKem, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GopY_DinhKem, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GopY_DinhKem)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GopY_DinhKem, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GopY_DinhKem, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<GopY_DinhKem, Object>>
		_attributeGetterFunctions;

	static {
		Map<String, Function<GopY_DinhKem, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GopY_DinhKem, Object>>();

		attributeGetterFunctions.put("id", GopY_DinhKem::getId);
		attributeGetterFunctions.put("companyId", GopY_DinhKem::getCompanyId);
		attributeGetterFunctions.put("groupId", GopY_DinhKem::getGroupId);
		attributeGetterFunctions.put("userId", GopY_DinhKem::getUserId);
		attributeGetterFunctions.put("ten", GopY_DinhKem::getTen);
		attributeGetterFunctions.put("url", GopY_DinhKem::getUrl);
		attributeGetterFunctions.put("Object", GopY_DinhKem::getObject);
		attributeGetterFunctions.put("ObjectId", GopY_DinhKem::getObjectId);
		attributeGetterFunctions.put("ghichu", GopY_DinhKem::getGhichu);
		attributeGetterFunctions.put("daxoa", GopY_DinhKem::getDaxoa);
		attributeGetterFunctions.put("status", GopY_DinhKem::getStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
	}

	private static final Map<String, BiConsumer<GopY_DinhKem, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, BiConsumer<GopY_DinhKem, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GopY_DinhKem, ?>>();

		attributeSetterBiConsumers.put(
			"id", (BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setCompanyId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setGroupId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setUserId);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<GopY_DinhKem, String>)GopY_DinhKem::setTen);
		attributeSetterBiConsumers.put(
			"url", (BiConsumer<GopY_DinhKem, String>)GopY_DinhKem::setUrl);
		attributeSetterBiConsumers.put(
			"Object", (BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setObject);
		attributeSetterBiConsumers.put(
			"ObjectId",
			(BiConsumer<GopY_DinhKem, Long>)GopY_DinhKem::setObjectId);
		attributeSetterBiConsumers.put(
			"ghichu",
			(BiConsumer<GopY_DinhKem, String>)GopY_DinhKem::setGhichu);
		attributeSetterBiConsumers.put(
			"daxoa", (BiConsumer<GopY_DinhKem, Integer>)GopY_DinhKem::setDaxoa);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<GopY_DinhKem, Integer>)GopY_DinhKem::setStatus);

		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@JSON
	@Override
	public String getUrl() {
		if (_url == null) {
			return "";
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_url = url;
	}

	@JSON
	@Override
	public long getObject() {
		return _Object;
	}

	@Override
	public void setObject(long Object) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Object = Object;
	}

	@JSON
	@Override
	public long getObjectId() {
		return _ObjectId;
	}

	@Override
	public void setObjectId(long ObjectId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ObjectId = ObjectId;
	}

	@JSON
	@Override
	public String getGhichu() {
		if (_ghichu == null) {
			return "";
		}
		else {
			return _ghichu;
		}
	}

	@Override
	public void setGhichu(String ghichu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ghichu = ghichu;
	}

	@JSON
	@Override
	public int getDaxoa() {
		return _daxoa;
	}

	@Override
	public void setDaxoa(int daxoa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_daxoa = daxoa;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GopY_DinhKem.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GopY_DinhKem toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GopY_DinhKem>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GopY_DinhKemImpl gopY_DinhKemImpl = new GopY_DinhKemImpl();

		gopY_DinhKemImpl.setId(getId());
		gopY_DinhKemImpl.setCompanyId(getCompanyId());
		gopY_DinhKemImpl.setGroupId(getGroupId());
		gopY_DinhKemImpl.setUserId(getUserId());
		gopY_DinhKemImpl.setTen(getTen());
		gopY_DinhKemImpl.setUrl(getUrl());
		gopY_DinhKemImpl.setObject(getObject());
		gopY_DinhKemImpl.setObjectId(getObjectId());
		gopY_DinhKemImpl.setGhichu(getGhichu());
		gopY_DinhKemImpl.setDaxoa(getDaxoa());
		gopY_DinhKemImpl.setStatus(getStatus());

		gopY_DinhKemImpl.resetOriginalValues();

		return gopY_DinhKemImpl;
	}

	@Override
	public int compareTo(GopY_DinhKem gopY_DinhKem) {
		long primaryKey = gopY_DinhKem.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GopY_DinhKem)) {
			return false;
		}

		GopY_DinhKem gopY_DinhKem = (GopY_DinhKem)object;

		long primaryKey = gopY_DinhKem.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GopY_DinhKem> toCacheModel() {
		GopY_DinhKemCacheModel gopY_DinhKemCacheModel =
			new GopY_DinhKemCacheModel();

		gopY_DinhKemCacheModel.id = getId();

		gopY_DinhKemCacheModel.companyId = getCompanyId();

		gopY_DinhKemCacheModel.groupId = getGroupId();

		gopY_DinhKemCacheModel.userId = getUserId();

		gopY_DinhKemCacheModel.ten = getTen();

		String ten = gopY_DinhKemCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			gopY_DinhKemCacheModel.ten = null;
		}

		gopY_DinhKemCacheModel.url = getUrl();

		String url = gopY_DinhKemCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			gopY_DinhKemCacheModel.url = null;
		}

		gopY_DinhKemCacheModel.Object = getObject();

		gopY_DinhKemCacheModel.ObjectId = getObjectId();

		gopY_DinhKemCacheModel.ghichu = getGhichu();

		String ghichu = gopY_DinhKemCacheModel.ghichu;

		if ((ghichu != null) && (ghichu.length() == 0)) {
			gopY_DinhKemCacheModel.ghichu = null;
		}

		gopY_DinhKemCacheModel.daxoa = getDaxoa();

		gopY_DinhKemCacheModel.status = getStatus();

		return gopY_DinhKemCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GopY_DinhKem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GopY_DinhKem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GopY_DinhKem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((GopY_DinhKem)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GopY_DinhKem, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GopY_DinhKem, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GopY_DinhKem, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GopY_DinhKem)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GopY_DinhKem>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					GopY_DinhKem.class, ModelWrapper.class);

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _ten;
	private String _url;
	private long _Object;
	private long _ObjectId;
	private String _ghichu;
	private int _daxoa;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GopY_DinhKem, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GopY_DinhKem)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("url", _url);
		_columnOriginalValues.put("Object", _Object);
		_columnOriginalValues.put("ObjectId", _ObjectId);
		_columnOriginalValues.put("ghichu", _ghichu);
		_columnOriginalValues.put("daxoa", _daxoa);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("ten", 16L);

		columnBitmasks.put("url", 32L);

		columnBitmasks.put("Object", 64L);

		columnBitmasks.put("ObjectId", 128L);

		columnBitmasks.put("ghichu", 256L);

		columnBitmasks.put("daxoa", 512L);

		columnBitmasks.put("status", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GopY_DinhKem _escapedModel;

}