/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.dnict.vanbanphapquy.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import vn.dnict.vanbanphapquy.model.Vanbanphapquy;
import vn.dnict.vanbanphapquy.model.VanbanphapquyModel;
import vn.dnict.vanbanphapquy.model.VanbanphapquySoap;

/**
 * The base model implementation for the Vanbanphapquy service. Represents a row in the &quot;cw_vanbanphapquy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>VanbanphapquyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VanbanphapquyImpl}.
 * </p>
 *
 * @author BinhNT
 * @see VanbanphapquyImpl
 * @generated
 */
@JSON(strict = true)
public class VanbanphapquyModelImpl
	extends BaseModelImpl<Vanbanphapquy> implements VanbanphapquyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vanbanphapquy model instance should use the <code>Vanbanphapquy</code> interface instead.
	 */
	public static final String TABLE_NAME = "cw_vanbanphapquy";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"sohieu", Types.VARCHAR},
		{"trichyeu", Types.VARCHAR}, {"noidung", Types.VARCHAR},
		{"ngay_banhanh", Types.TIMESTAMP}, {"ngay_hieuluc", Types.TIMESTAMP},
		{"ngay_hethieuluc", Types.TIMESTAMP}, {"ngay_xuatban", Types.TIMESTAMP},
		{"id_linhvuc", Types.BIGINT}, {"id_loaivanban", Types.BIGINT},
		{"id_capbanhanh", Types.BIGINT}, {"id_coquanbanhanh", Types.BIGINT},
		{"nguoiky", Types.VARCHAR}, {"status", Types.INTEGER},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sohieu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trichyeu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noidung", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ngay_banhanh", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngay_hieuluc", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngay_hethieuluc", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ngay_xuatban", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("id_linhvuc", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_loaivanban", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_capbanhanh", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_coquanbanhanh", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nguoiky", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table cw_vanbanphapquy (id_ LONG not null primary key,companyId LONG,groupId LONG,sohieu VARCHAR(75) null,trichyeu VARCHAR(75) null,noidung VARCHAR(75) null,ngay_banhanh DATE null,ngay_hieuluc DATE null,ngay_hethieuluc DATE null,ngay_xuatban DATE null,id_linhvuc LONG,id_loaivanban LONG,id_capbanhanh LONG,id_coquanbanhanh LONG,nguoiky VARCHAR(75) null,status INTEGER,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table cw_vanbanphapquy";

	public static final String ORDER_BY_JPQL =
		" ORDER BY vanbanphapquy.ngay_xuatban DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY cw_vanbanphapquy.ngay_xuatban DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NGAY_XUATBAN_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Vanbanphapquy toModel(VanbanphapquySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Vanbanphapquy model = new VanbanphapquyImpl();

		model.setId(soapModel.getId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setSohieu(soapModel.getSohieu());
		model.setTrichyeu(soapModel.getTrichyeu());
		model.setNoidung(soapModel.getNoidung());
		model.setNgay_banhanh(soapModel.getNgay_banhanh());
		model.setNgay_hieuluc(soapModel.getNgay_hieuluc());
		model.setNgay_hethieuluc(soapModel.getNgay_hethieuluc());
		model.setNgay_xuatban(soapModel.getNgay_xuatban());
		model.setId_linhvuc(soapModel.getId_linhvuc());
		model.setId_loaivanban(soapModel.getId_loaivanban());
		model.setId_capbanhanh(soapModel.getId_capbanhanh());
		model.setId_coquanbanhanh(soapModel.getId_coquanbanhanh());
		model.setNguoiky(soapModel.getNguoiky());
		model.setStatus(soapModel.getStatus());
		model.setType(soapModel.getType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Vanbanphapquy> toModels(VanbanphapquySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Vanbanphapquy> models = new ArrayList<Vanbanphapquy>(
			soapModels.length);

		for (VanbanphapquySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public VanbanphapquyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vanbanphapquy.class;
	}

	@Override
	public String getModelClassName() {
		return Vanbanphapquy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Vanbanphapquy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Vanbanphapquy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vanbanphapquy, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Vanbanphapquy)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Vanbanphapquy, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Vanbanphapquy, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Vanbanphapquy)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Vanbanphapquy, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Vanbanphapquy, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Vanbanphapquy>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Vanbanphapquy.class.getClassLoader(), Vanbanphapquy.class,
			ModelWrapper.class);

		try {
			Constructor<Vanbanphapquy> constructor =
				(Constructor<Vanbanphapquy>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Vanbanphapquy, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Vanbanphapquy, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Vanbanphapquy, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Vanbanphapquy, Object>>();
		Map<String, BiConsumer<Vanbanphapquy, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Vanbanphapquy, ?>>();

		attributeGetterFunctions.put("id", Vanbanphapquy::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setId);
		attributeGetterFunctions.put("companyId", Vanbanphapquy::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setCompanyId);
		attributeGetterFunctions.put("groupId", Vanbanphapquy::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setGroupId);
		attributeGetterFunctions.put("sohieu", Vanbanphapquy::getSohieu);
		attributeSetterBiConsumers.put(
			"sohieu",
			(BiConsumer<Vanbanphapquy, String>)Vanbanphapquy::setSohieu);
		attributeGetterFunctions.put("trichyeu", Vanbanphapquy::getTrichyeu);
		attributeSetterBiConsumers.put(
			"trichyeu",
			(BiConsumer<Vanbanphapquy, String>)Vanbanphapquy::setTrichyeu);
		attributeGetterFunctions.put("noidung", Vanbanphapquy::getNoidung);
		attributeSetterBiConsumers.put(
			"noidung",
			(BiConsumer<Vanbanphapquy, String>)Vanbanphapquy::setNoidung);
		attributeGetterFunctions.put(
			"ngay_banhanh", Vanbanphapquy::getNgay_banhanh);
		attributeSetterBiConsumers.put(
			"ngay_banhanh",
			(BiConsumer<Vanbanphapquy, Date>)Vanbanphapquy::setNgay_banhanh);
		attributeGetterFunctions.put(
			"ngay_hieuluc", Vanbanphapquy::getNgay_hieuluc);
		attributeSetterBiConsumers.put(
			"ngay_hieuluc",
			(BiConsumer<Vanbanphapquy, Date>)Vanbanphapquy::setNgay_hieuluc);
		attributeGetterFunctions.put(
			"ngay_hethieuluc", Vanbanphapquy::getNgay_hethieuluc);
		attributeSetterBiConsumers.put(
			"ngay_hethieuluc",
			(BiConsumer<Vanbanphapquy, Date>)Vanbanphapquy::setNgay_hethieuluc);
		attributeGetterFunctions.put(
			"ngay_xuatban", Vanbanphapquy::getNgay_xuatban);
		attributeSetterBiConsumers.put(
			"ngay_xuatban",
			(BiConsumer<Vanbanphapquy, Date>)Vanbanphapquy::setNgay_xuatban);
		attributeGetterFunctions.put(
			"id_linhvuc", Vanbanphapquy::getId_linhvuc);
		attributeSetterBiConsumers.put(
			"id_linhvuc",
			(BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setId_linhvuc);
		attributeGetterFunctions.put(
			"id_loaivanban", Vanbanphapquy::getId_loaivanban);
		attributeSetterBiConsumers.put(
			"id_loaivanban",
			(BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setId_loaivanban);
		attributeGetterFunctions.put(
			"id_capbanhanh", Vanbanphapquy::getId_capbanhanh);
		attributeSetterBiConsumers.put(
			"id_capbanhanh",
			(BiConsumer<Vanbanphapquy, Long>)Vanbanphapquy::setId_capbanhanh);
		attributeGetterFunctions.put(
			"id_coquanbanhanh", Vanbanphapquy::getId_coquanbanhanh);
		attributeSetterBiConsumers.put(
			"id_coquanbanhanh",
			(BiConsumer<Vanbanphapquy, Long>)
				Vanbanphapquy::setId_coquanbanhanh);
		attributeGetterFunctions.put("nguoiky", Vanbanphapquy::getNguoiky);
		attributeSetterBiConsumers.put(
			"nguoiky",
			(BiConsumer<Vanbanphapquy, String>)Vanbanphapquy::setNguoiky);
		attributeGetterFunctions.put("status", Vanbanphapquy::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<Vanbanphapquy, Integer>)Vanbanphapquy::setStatus);
		attributeGetterFunctions.put("type", Vanbanphapquy::getType);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<Vanbanphapquy, String>)Vanbanphapquy::setType);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public String getSohieu() {
		if (_sohieu == null) {
			return "";
		}
		else {
			return _sohieu;
		}
	}

	@Override
	public void setSohieu(String sohieu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sohieu = sohieu;
	}

	@JSON
	@Override
	public String getTrichyeu() {
		if (_trichyeu == null) {
			return "";
		}
		else {
			return _trichyeu;
		}
	}

	@Override
	public void setTrichyeu(String trichyeu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trichyeu = trichyeu;
	}

	@JSON
	@Override
	public String getNoidung() {
		if (_noidung == null) {
			return "";
		}
		else {
			return _noidung;
		}
	}

	@Override
	public void setNoidung(String noidung) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noidung = noidung;
	}

	@JSON
	@Override
	public Date getNgay_banhanh() {
		return _ngay_banhanh;
	}

	@Override
	public void setNgay_banhanh(Date ngay_banhanh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngay_banhanh = ngay_banhanh;
	}

	@JSON
	@Override
	public Date getNgay_hieuluc() {
		return _ngay_hieuluc;
	}

	@Override
	public void setNgay_hieuluc(Date ngay_hieuluc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngay_hieuluc = ngay_hieuluc;
	}

	@JSON
	@Override
	public Date getNgay_hethieuluc() {
		return _ngay_hethieuluc;
	}

	@Override
	public void setNgay_hethieuluc(Date ngay_hethieuluc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngay_hethieuluc = ngay_hethieuluc;
	}

	@JSON
	@Override
	public Date getNgay_xuatban() {
		return _ngay_xuatban;
	}

	@Override
	public void setNgay_xuatban(Date ngay_xuatban) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngay_xuatban = ngay_xuatban;
	}

	@JSON
	@Override
	public long getId_linhvuc() {
		return _id_linhvuc;
	}

	@Override
	public void setId_linhvuc(long id_linhvuc) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id_linhvuc = id_linhvuc;
	}

	@JSON
	@Override
	public long getId_loaivanban() {
		return _id_loaivanban;
	}

	@Override
	public void setId_loaivanban(long id_loaivanban) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id_loaivanban = id_loaivanban;
	}

	@JSON
	@Override
	public long getId_capbanhanh() {
		return _id_capbanhanh;
	}

	@Override
	public void setId_capbanhanh(long id_capbanhanh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id_capbanhanh = id_capbanhanh;
	}

	@JSON
	@Override
	public long getId_coquanbanhanh() {
		return _id_coquanbanhanh;
	}

	@Override
	public void setId_coquanbanhanh(long id_coquanbanhanh) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id_coquanbanhanh = id_coquanbanhanh;
	}

	@JSON
	@Override
	public String getNguoiky() {
		if (_nguoiky == null) {
			return "";
		}
		else {
			return _nguoiky;
		}
	}

	@Override
	public void setNguoiky(String nguoiky) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoiky = nguoiky;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Vanbanphapquy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vanbanphapquy toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Vanbanphapquy>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VanbanphapquyImpl vanbanphapquyImpl = new VanbanphapquyImpl();

		vanbanphapquyImpl.setId(getId());
		vanbanphapquyImpl.setCompanyId(getCompanyId());
		vanbanphapquyImpl.setGroupId(getGroupId());
		vanbanphapquyImpl.setSohieu(getSohieu());
		vanbanphapquyImpl.setTrichyeu(getTrichyeu());
		vanbanphapquyImpl.setNoidung(getNoidung());
		vanbanphapquyImpl.setNgay_banhanh(getNgay_banhanh());
		vanbanphapquyImpl.setNgay_hieuluc(getNgay_hieuluc());
		vanbanphapquyImpl.setNgay_hethieuluc(getNgay_hethieuluc());
		vanbanphapquyImpl.setNgay_xuatban(getNgay_xuatban());
		vanbanphapquyImpl.setId_linhvuc(getId_linhvuc());
		vanbanphapquyImpl.setId_loaivanban(getId_loaivanban());
		vanbanphapquyImpl.setId_capbanhanh(getId_capbanhanh());
		vanbanphapquyImpl.setId_coquanbanhanh(getId_coquanbanhanh());
		vanbanphapquyImpl.setNguoiky(getNguoiky());
		vanbanphapquyImpl.setStatus(getStatus());
		vanbanphapquyImpl.setType(getType());

		vanbanphapquyImpl.resetOriginalValues();

		return vanbanphapquyImpl;
	}

	@Override
	public int compareTo(Vanbanphapquy vanbanphapquy) {
		int value = 0;

		value = DateUtil.compareTo(
			getNgay_xuatban(), vanbanphapquy.getNgay_xuatban());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Vanbanphapquy)) {
			return false;
		}

		Vanbanphapquy vanbanphapquy = (Vanbanphapquy)object;

		long primaryKey = vanbanphapquy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Vanbanphapquy> toCacheModel() {
		VanbanphapquyCacheModel vanbanphapquyCacheModel =
			new VanbanphapquyCacheModel();

		vanbanphapquyCacheModel.id = getId();

		vanbanphapquyCacheModel.companyId = getCompanyId();

		vanbanphapquyCacheModel.groupId = getGroupId();

		vanbanphapquyCacheModel.sohieu = getSohieu();

		String sohieu = vanbanphapquyCacheModel.sohieu;

		if ((sohieu != null) && (sohieu.length() == 0)) {
			vanbanphapquyCacheModel.sohieu = null;
		}

		vanbanphapquyCacheModel.trichyeu = getTrichyeu();

		String trichyeu = vanbanphapquyCacheModel.trichyeu;

		if ((trichyeu != null) && (trichyeu.length() == 0)) {
			vanbanphapquyCacheModel.trichyeu = null;
		}

		vanbanphapquyCacheModel.noidung = getNoidung();

		String noidung = vanbanphapquyCacheModel.noidung;

		if ((noidung != null) && (noidung.length() == 0)) {
			vanbanphapquyCacheModel.noidung = null;
		}

		Date ngay_banhanh = getNgay_banhanh();

		if (ngay_banhanh != null) {
			vanbanphapquyCacheModel.ngay_banhanh = ngay_banhanh.getTime();
		}
		else {
			vanbanphapquyCacheModel.ngay_banhanh = Long.MIN_VALUE;
		}

		Date ngay_hieuluc = getNgay_hieuluc();

		if (ngay_hieuluc != null) {
			vanbanphapquyCacheModel.ngay_hieuluc = ngay_hieuluc.getTime();
		}
		else {
			vanbanphapquyCacheModel.ngay_hieuluc = Long.MIN_VALUE;
		}

		Date ngay_hethieuluc = getNgay_hethieuluc();

		if (ngay_hethieuluc != null) {
			vanbanphapquyCacheModel.ngay_hethieuluc = ngay_hethieuluc.getTime();
		}
		else {
			vanbanphapquyCacheModel.ngay_hethieuluc = Long.MIN_VALUE;
		}

		Date ngay_xuatban = getNgay_xuatban();

		if (ngay_xuatban != null) {
			vanbanphapquyCacheModel.ngay_xuatban = ngay_xuatban.getTime();
		}
		else {
			vanbanphapquyCacheModel.ngay_xuatban = Long.MIN_VALUE;
		}

		vanbanphapquyCacheModel.id_linhvuc = getId_linhvuc();

		vanbanphapquyCacheModel.id_loaivanban = getId_loaivanban();

		vanbanphapquyCacheModel.id_capbanhanh = getId_capbanhanh();

		vanbanphapquyCacheModel.id_coquanbanhanh = getId_coquanbanhanh();

		vanbanphapquyCacheModel.nguoiky = getNguoiky();

		String nguoiky = vanbanphapquyCacheModel.nguoiky;

		if ((nguoiky != null) && (nguoiky.length() == 0)) {
			vanbanphapquyCacheModel.nguoiky = null;
		}

		vanbanphapquyCacheModel.status = getStatus();

		vanbanphapquyCacheModel.type = getType();

		String type = vanbanphapquyCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			vanbanphapquyCacheModel.type = null;
		}

		return vanbanphapquyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Vanbanphapquy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Vanbanphapquy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vanbanphapquy, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Vanbanphapquy)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Vanbanphapquy, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Vanbanphapquy, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Vanbanphapquy, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Vanbanphapquy)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Vanbanphapquy>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private long _companyId;
	private long _groupId;
	private String _sohieu;
	private String _trichyeu;
	private String _noidung;
	private Date _ngay_banhanh;
	private Date _ngay_hieuluc;
	private Date _ngay_hethieuluc;
	private Date _ngay_xuatban;
	private long _id_linhvuc;
	private long _id_loaivanban;
	private long _id_capbanhanh;
	private long _id_coquanbanhanh;
	private String _nguoiky;
	private int _status;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Vanbanphapquy, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Vanbanphapquy)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("sohieu", _sohieu);
		_columnOriginalValues.put("trichyeu", _trichyeu);
		_columnOriginalValues.put("noidung", _noidung);
		_columnOriginalValues.put("ngay_banhanh", _ngay_banhanh);
		_columnOriginalValues.put("ngay_hieuluc", _ngay_hieuluc);
		_columnOriginalValues.put("ngay_hethieuluc", _ngay_hethieuluc);
		_columnOriginalValues.put("ngay_xuatban", _ngay_xuatban);
		_columnOriginalValues.put("id_linhvuc", _id_linhvuc);
		_columnOriginalValues.put("id_loaivanban", _id_loaivanban);
		_columnOriginalValues.put("id_capbanhanh", _id_capbanhanh);
		_columnOriginalValues.put("id_coquanbanhanh", _id_coquanbanhanh);
		_columnOriginalValues.put("nguoiky", _nguoiky);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("sohieu", 8L);

		columnBitmasks.put("trichyeu", 16L);

		columnBitmasks.put("noidung", 32L);

		columnBitmasks.put("ngay_banhanh", 64L);

		columnBitmasks.put("ngay_hieuluc", 128L);

		columnBitmasks.put("ngay_hethieuluc", 256L);

		columnBitmasks.put("ngay_xuatban", 512L);

		columnBitmasks.put("id_linhvuc", 1024L);

		columnBitmasks.put("id_loaivanban", 2048L);

		columnBitmasks.put("id_capbanhanh", 4096L);

		columnBitmasks.put("id_coquanbanhanh", 8192L);

		columnBitmasks.put("nguoiky", 16384L);

		columnBitmasks.put("status", 32768L);

		columnBitmasks.put("type_", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Vanbanphapquy _escapedModel;

}